### ISSUE TITLE
Tela de Cadastro do Atendimento - EXEMPLO

### ISSUE THREAD

**Issue by rvnovaes** [gestaolegalufmg/gestaolegal#1]
![task details](https://user-images.githubusercontent.com/374578/65723045-f65ae380-e083-11e9-8049-d4c4c6fde6d7.png)
EU Estagiário de Atendimento de Plantão, PRECISO DE uma tela para cadastro do primeiro atendimento do assistido, PARA direcionar os assitidos e extrair relatórios posteriormente.

Atualmente, o cadastro dos assistidos é feito por meio de um Google Form. (colocar link)

Desenvolver uma tela para cadastro no sistema equivalente.

https://www.quant-ux.com#/share.html?h=a2aa10ab7Fcj1AxDyYGpYW8f2OzrOlzStNydFcYHpMBPjX6cyZtIVpXgyRoe

**Comment by Alex19-tech** [comment]
Ainda estou aprendendo a usar o Pencil.  As imagens abaixo foram o resultado de um brainstorm de como o programa poderia ser. **Ainda falta muito para melhorar** e ficar bacana.

![pgina_inicial](https://user-images.githubusercontent.com/55855366/67015119-6df0c100-f0cc-11e9-84c6-5972ca2a08c4.png)
![cadastro_de_assistido](https://user-images.githubusercontent.com/55855366/67015125-721cde80-f0cc-11e9-8b14-d84c83a1d80b.png)
![prosseguimento_com_assistido](https://user-images.githubusercontent.com/55855366/67015133-73e6a200-f0cc-11e9-8301-d117fb5e1a81.png)

**Comment by rvnovaes** [comment]
Ficou legal demais! Parabéns!

**Comment by Alex19-tech** [comment]
Pessoal, resolvi melhorar o desenho para que vocês possam usar na apresentação de sábado, acho que vai ajudar a convencer os jurados. Espero que tenha ficado melhor. 

![pgina_inicial](https://user-images.githubusercontent.com/55855366/67068200-b8675180-f14f-11e9-9655-36dc629e74dc.png)
![cadastro_de_assistido](https://user-images.githubusercontent.com/55855366/67068374-45120f80-f150-11e9-9aaa-bae9390cee56.png)
![prosseguimento_com_assistido](https://user-images.githubusercontent.com/55855366/67068204-bbfad880-f14f-11e9-918f-a8bb80d87cc0.png)
![gerao_de_relatrio](https://user-images.githubusercontent.com/55855366/67068219-c5844080-f14f-11e9-84a2-63c44f10244d.png)

Segue abaixo link do Google Drive contendo o arquivo do Pencil para que vocês possam editar, caso eu não consiga.
https://drive.google.com/file/d/1GHTpDJxAQIlVDYGK_ZwjbJA9w_ggElel/view?usp=sharing
