### ISSUE TITLE
Detalhamento do Fluxo "Minhadaj" - Acesso Estagiário

### ISSUE THREAD

**Issue by ailtongomess** [gestaolegalufmg/gestaolegal#10]
Desenhar no Bizagi os fluxos do assistido pelo site "Minhadaj".

**Comment by AmandaFuso** [comment]
Segue prints das telas do Sistema MinhaDAJ com o acesso de estagiário:  
![Página inicial](https://user-images.githubusercontent.com/55855410/67438919-32be2880-f5cb-11e9-8aa9-a5a3a3da16d8.jpg) 

Essa é a página inicial na qual o estagiário insere o seu login e senha cadastrados. 
Esse login e senha são criados ao tomar posse no estágio, pelo Chefe de Secretaria

**Comment by AmandaFuso** [comment]
![Lista de casos](https://user-images.githubusercontent.com/55855410/67439058-9ea09100-f5cb-11e9-9eb5-cfb8052264c8.png)

O estagiário é logo redirecionado a página em que consta a lista de "Casos em destaque", no qual ele tem acesso aos: 
a. Casos sem Estagiário 
Casos que foram anotados mas o Chefe da Secretaria ainda não designou o estagiário responsável

b. Casos sem Orientador 
Casos que foram anotados mas o Chefe da Secretaria ainda não designou o orientador responsável

c. Casos Aguardando Deferimento
Casos que foram anotados mas que ainda não foram deferidos ou inferidos. Possíveis razões: 
- Cível: A Professora Tereza Thibau não avaliou 
- Penal, Trabalho e Administrativo: O Grupo de orientadores da área não avaliou

**Comment by AmandaFuso** [comment]
![Lista de casos](https://user-images.githubusercontent.com/55855410/67439499-c6442900-f5cc-11e9-80de-f0e500492186.png)

Ao selecionar a opção de casos, é possível visualizar todos os casos cadastrados no sistema, seja: 
- Aguardando deferimento 
- Ativo 
- Indeferido 
- Solucionado 
- Arquivado

**Comment by gabriellasaffioti** [comment]
![Fluxograma - Acompanhamento de caso MinhaDAJ ](https://user-images.githubusercontent.com/55855370/67804579-f3ca2000-fa6d-11e9-9dd5-d2a4b3727707.png)
 
Fluxo do Acompanhamento de casos no MinhaDAJ pelo Estagiário
