### ISSUE TITLE
Não é possível criar lembrete

### ISSUE THREAD

**Issue by Math-carvalho** [gestaolegalufmg/gestaolegal#100]
i) Navegador: Google Chrome 
ii) Usuário: Estagiário de Direito 

Ao tentar criar um lembrete, não é possível preencher o campo obrigatório "Usuário a ser notificado" (no momento da busca, uma mensagem permanente de "Searching" aparece). Todos os outros campos - "Lembrete" e "Data de notificação" - podem ser preenchidos.

![image](https://user-images.githubusercontent.com/71521066/111170912-32894900-8583-11eb-8888-37a3d78a4509.png)
![image](https://user-images.githubusercontent.com/71521066/111170947-3ae18400-8583-11eb-92c4-19f6b54cf338.png)

**Comment by rvnovaes** [comment]
Qual o caminho para acessar a tela de criar lembretes?

**Comment by rvnovaes** [comment]
#100 #101 #103 #104 
Erro semelhante. Bloqueio de requisição AJAX para carregar lista do dropdown.

Status da requisição (blocked:mixed-content)
