### ISSUE TITLE
Não é possível criar caso - campo assistidos não carrega

### ISSUE THREAD

**Issue by Math-carvalho** [gestaolegalufmg/gestaolegal#101]
i) Navegador: Google Chrome 
ii) Usuário: Estagiário de Direito 

Ao tentar criar um caso na opção "Cadastrar Novo Caso", os campos de "Área do Direito" e "Descrição" podem ser modificados. Porém, ao tentar completar a área de "Assistidos", uma mensagem de "Searching" aparece e impede a conclusão da tarefa.

![image](https://user-images.githubusercontent.com/71521066/111172290-7466bf00-8584-11eb-9a1f-a73fcf5026ad.png)

**Comment by rvnovaes** [comment]
Reproduzido com usuário administrador em https://gestaolegalapp.direito.ufmg.br/

**Comment by rvnovaes** [comment]
#100 #101 #103 #104 
Erro semelhante. Bloqueio de requisição AJAX para carregar lista do dropdown.

Status da requisição (blocked:mixed-content)
