### ISSUE TITLE
Não consigo selecionar dias para fazer plantão como colaborador externo.

### ISSUE THREAD

**Issue by shevah7** [gestaolegalufmg/gestaolegal#102]
Ao selecionar "Página do Plantão", aparece a mensagem "O plantão não está aberto!" e não tenho acesso à seleção dos dias.

- Navegador: Google chrome.
- Usuário: colaborador externo
- 
![Captura de Tela (53)](https://user-images.githubusercontent.com/71346842/111201275-5e1b2c00-85a1-11eb-84bb-b54857a420a0.png)

**Comment by rvnovaes** [comment]
Com usuário administrador é possível acessar o calendário e criar o plantão. 

![Screenshot from 2021-03-16 10-23-33](https://user-images.githubusercontent.com/374578/111317208-b1918680-8642-11eb-912a-34cb0c50735a.png)

**Comment by Ale-eloy** [comment]
Estamos averiguando essa questão. Até então não conseguimos testar a funcionalidade reportada porque havia um erro na hora de abrir o plantão como administrador. Vamos testar novamente assim que for possível e retornar com a resposta para essa questão.

**Comment by Ale-eloy** [comment]
Agora que a página de plantão foi corrigida, consegui averiguar a situação a fundo. Cadastrei um novo issue com as informações completas sobre o problema, o issue #137 .
Sugiro fechar esse issue.
