### ISSUE TITLE
Não consigo selecionar área do direito para criar relatório

### ISSUE THREAD

**Issue by shevah7** [gestaolegalufmg/gestaolegal#103]
Na criação de relatório, as opções de áreas do direito não carregam. Quando tento escrever uma área, o texto redigido é apagado.

- Navegador: Google chrome
- Usuário: colaborador externo
![Captura de Tela (59)_LI](https://user-images.githubusercontent.com/71346842/111202212-60ca5100-85a2-11eb-9a1a-bf3ecbbfb5e5.jpg)

**Comment by rvnovaes** [comment]
Não é possível selecionar a área do direito como qualquer tipo de colaborador. Reproduzido o erro como administrador.

**Comment by rvnovaes** [comment]
#100 #101 #103 #104 
Erro semelhante. Bloqueio de requisição AJAX para carregar lista do dropdown.

Status da requisição (blocked:mixed-content)
