### ISSUE TITLE
Não consigo associar um caso a um colaborador externo.

### ISSUE THREAD

**Issue by shevah7** [gestaolegalufmg/gestaolegal#104]
Na Gestão de Casos, as opções para associar colaborador externo a um caso não carregam.

- Navegador: Google chrome
- Usuário: Colaborador externo

![Captura de Tela (60)](https://user-images.githubusercontent.com/71346842/111202679-ea7a1e80-85a2-11eb-8b27-4f2a07e01b6e.png)

**Comment by rvnovaes** [comment]
O mesmo problema acontece com associação a outros papéis (Orientador e Estagiário). Mesmo tendo usuários cadastrados com os papéis de orientador, estagiário e colaborador externo, ao clicar nos respectivos dropdowns não é realizada a busca de nomes e, portanto, impossível a associação;

![Screenshot from 2021-03-16 10-17-13](https://user-images.githubusercontent.com/374578/111315320-06340200-8641-11eb-8049-96cd1e7313a6.png)
![Screenshot from 2021-03-16 10-17-09](https://user-images.githubusercontent.com/374578/111315334-08965c00-8641-11eb-9e91-da7af66362a9.png)

**Comment by rvnovaes** [comment]
#100 #101 #103 #104 
Erro semelhante. Bloqueio de requisição AJAX para carregar lista do dropdown.

Status da requisição (blocked:mixed-content)
