### ISSUE TITLE
Separação dos ambientes de desenvolvimento e produção

### ISSUE THREAD

**Issue by rvnovaes** [gestaolegalufmg/gestaolegal#109]
No código atual, as configurações de ambiente estão hard coded. Além de dificultar o deploy, senhas e variáveis de ambiente não devem ser comitadas para repositórios.

Elas serão separadas para arquivos de configuração.

Serão criados também arquivos para o docker-compose separando os ambientes.

Será criado Makefile com os atalhos correspondentes.

No manual de Instalação deverá ser acrescentada a documentação respecitva.

**Comment by Ale-eloy** [comment]
@rvnovaes como está o progresso desse issue? Ele foi implementado?
