### ISSUE TITLE
Correções na parte de "Renda e Patrimônio do Assistido" após "Tornar Assistido"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#111]
Logado como administrador no navegador chrome, notamos algumas pequenas incorreções na parte de Renda e Patrimônio que aparece para cadastro depois de Tornar um Atendido em um Assistido, mais especificamente:

1. Ao selecionar a opção "Outro" dentro de "Recebe algum benefício social", seria interesse abrir um novo checkbox para inserir qual o benefício recebido:

![WhatsApp Image 2021-03-20 at 15 12 42](https://user-images.githubusercontent.com/55855366/111881453-2b9d7480-898f-11eb-9eef-325e126b3abe.jpeg)

2. Dentro da pergunta "Recebe algum benefício social", a opção "Valegás" deve ser escrita como "Vale Gás":

![WhatsApp Image 2021-03-20 at 15 12 35](https://user-images.githubusercontent.com/55855366/111881454-2ccea180-898f-11eb-831e-b4a25d852ab6.jpeg)

3. Dentro de "Qual a sua posição em relação à renda familiar?", excluir a opção "Não contribuinte" (explicação: "Não contribuinte" e "Dependente" na prática significam a mesma coisa)

![WhatsApp Image 2021-03-20 at 15 14 15](https://user-images.githubusercontent.com/55855366/111881657-4b816800-8990-11eb-9b45-c5e6ecc11adf.jpeg)

4. Dentro de "Pessoa doente", excluir a opção "Não se aplica", porque esse dropdown apenas aparece se selecionado acima "Há pessoas com doença grave na família" (logo, há contradição)

![WhatsApp Image 2021-03-20 at 15 15 54](https://user-images.githubusercontent.com/55855366/111881642-31478a00-8990-11eb-9397-dd555b9fdb45.jpeg)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e:

1. não foi aberto um novo checkbox para especificar o benefício social recebido 
![image](https://user-images.githubusercontent.com/71521066/119428768-eb86a500-bce3-11eb-82dd-7941b15f46d4.png)

2. a opção "Valegás" não foi escrita corretamente 
![image](https://user-images.githubusercontent.com/71521066/119428903-2557ab80-bce4-11eb-8244-79348bbb5325.png)

3. a opção "Não contribuinte" não foi excluída
![image](https://user-images.githubusercontent.com/71521066/119428985-4e783c00-bce4-11eb-9866-47f6e0a6a0ab.png)

4. a opção "Não se aplica" não foi excluída 
![image](https://user-images.githubusercontent.com/71521066/119429081-82536180-bce4-11eb-8e40-8e52b3b2a76c.png)

**Comment by Lucardoso06** [comment]
Realizei testes no issue e:

1. A aba para informar qual outro benefício foi inserida :
![image](https://user-images.githubusercontent.com/89036394/134350162-4749ce70-caf2-428c-b454-b21e3ad7c492.png)

2. "Vale Gás" está escrito corretamente:
![image](https://user-images.githubusercontent.com/89036394/134350482-8d9a1948-f055-48f0-9b64-26ddbbf916c4.png)

3. A opção "Não contribuinte" foi devidamente excluída:
![image](https://user-images.githubusercontent.com/89036394/134350810-476ad9e7-bc01-4188-adab-bab0b4ff8c4e.png)

4. A opção "Não se aplica" foi devidamente excluída.
![image](https://user-images.githubusercontent.com/89036394/134351077-b791fa1f-2122-47b0-a23f-3dc128492081.png)

Ao que tudo indica, o issue foi resolvido por completo.
