### ISSUE TITLE
Perguntar quantos imóveis em Renda e Patrimônio após tornar assistido

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#112]
Ao transformar um atendido em um assistido, dentro de Renda e Patrimônio (questionário socioecônomico) há a pergunta "A família possui outros imóveis?" que é levada em consideração para verificar se a pessoa se enquadra no critério de pessoa carente. Ocorre que é importante para o fluxo de enquadramento socioecônomico acrescentar a pergunta "Quantos outros imóveis a família tem?" logo abaixo caso seja respondido "Sim" na pergunta de imóveis:

![1](https://user-images.githubusercontent.com/55855366/111906470-71117e80-8a2f-11eb-824c-8fe5d32a6f24.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e não foi acrescentado o complemento "Quantos outros imóveis a família tem?" (na hipótese de selecionar a opção "Sim" para a  pergunta "A família possui outros imóveis?")

![image](https://user-images.githubusercontent.com/71521066/119429545-6b613f00-bce5-11eb-8611-6c6be2bcd4af.png)

**Comment by elisacostab** [comment]
Conferido em 24/01/2022
