### ISSUE TITLE
Opções em dropdown de "Situação Perante a Receita" em "Dados Jurídicos" de PJ dentro de "Tornar Assistido"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#113]
Após tornar um atendido em um assistido do tipo Pessoa Jurídica, dentro do trecho "Dados Jurídicos" (questionário socioeconômico), a pergunta "Situação perante a Receita Federal" tem um campo livre de preenchimento. Ocorre que, segundo os requisitos contratuais (print abaixo), precisamos de um dropdown com as seguintes opções predefinidas: "ativa", "baixada" e "outras".

![image](https://user-images.githubusercontent.com/55855366/111906697-981c8000-8a30-11eb-8035-52f2152f3076.png)

![2](https://user-images.githubusercontent.com/55855366/111906664-5e4b7980-8a30-11eb-8401-e3bb5395c98f.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e a pergunta "Situação perante a Receita Federal" não oferece um dropdown (o campo para livre preenchimento permanece como opção).

![image](https://user-images.githubusercontent.com/71521066/119430695-9a78b000-bce7-11eb-8bbe-861cae883c20.png)

**Comment by RaphaGg** [comment]
Reproduzi o relato e o problema parece ter sido resolvido.

![iaaa](https://user-images.githubusercontent.com/89051386/133864167-c0213d62-c19c-430c-8bff-39a963670b32.png)
