### ISSUE TITLE
Opção de "Não se aplica" dentro de dropdown de "O balanço patrimonial do último ano foi negativo" em Dados Jurídicos em Tornar Assistido

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#115]
Após clicar em "Tornar Assistido" para tornar uma PJ Atendida em Assistida, dentro da parte de "Dados Jurídicos", a pergunta "O balanço patrimonial do último ano foi negativo?" falta a opção "Não se aplica", conforme definida nos requisitos (print abaixo):

![image](https://user-images.githubusercontent.com/55855366/111907510-745b3900-8a34-11eb-8ed5-2d0f953c96b4.png)

![5](https://user-images.githubusercontent.com/55855366/111907482-4b3aa880-8a34-11eb-844e-55b39ec93832.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e a pergunta "O balanço patrimonial do último ano foi negativo?" não foi atualizada (a opção "Não se aplica" não foi incluída).

![image](https://user-images.githubusercontent.com/71521066/119513352-8619cf00-bd4a-11eb-9dbc-3f61787c3a8e.png)

**Comment by RaphaGg** [comment]
Reproduzi o relato e o problema parece ter sido resolvido.

![fiiioo](https://user-images.githubusercontent.com/89051386/133863955-599020b0-d074-44a7-8c14-36508773a69e.png)
