### ISSUE TITLE
Tamanho do campo "Breve descrição da Orientação Jurídica dada" dentro de "Cadastrar Orientação Jurídica"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#116]
Ao clicar em "Cadastrar Orientação Jurídica" dentro de Orientação Jurídica, é preciso que o textbox de "Breve descrição da Orientação Jurídica dada" seja (i) um pouco maior por padrão; e (ii) seja livremente dimensionável pelo usuário (atualmente a dimensão dele é bloqueada; embora haja uma barra de rolagem, ela é pouco prática para esse campo)

![6](https://user-images.githubusercontent.com/55855366/111907666-1ed35c00-8a35-11eb-8e47-a84149b03c40.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e me parece que a demanda foi corretamente atualizada. O tamanho do text box é maior que o dos outros campos e a barra de rolagem aparece apenas quando muitos caracteres são inseridos. @Ale-eloy o issue está correto?

![image](https://user-images.githubusercontent.com/71521066/119514427-6636db00-bd4b-11eb-9c7a-46520327b317.png)

**Comment by Ale-eloy** [comment]
Ainda não, @Math-carvalho. Pelo que testei aqui, a dimensão do textbox ainda é bloqueada, de forma que se o texto for grande eu não consigo expandir ela para ver tudo de uma vez.

**Comment by Lucardoso06** [comment]
![image](https://user-images.githubusercontent.com/89036394/134354821-3e3af64b-3f0d-4ff8-bcc0-370c28ec3743.png)

Issue parece ter sido corrigido. É possível expandir a "breve" descrição até toda a extensão da página.
