### ISSUE TITLE
"Encaminhamento para outras Assistências Judiciárias" dentro de "Visualizar" Orientação Jurídica não funciona

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#117]
Na página "Orientação Jurídica", ao clicar em "Visualizar" em qualquer uma das Orientações, aparecem os dados da Orientação. Em seguida, dentro do card "Encaminhamento para outras Assistências Judiciárias", há um botão "Encaminhar" que em tese deveria permitir associar uma Orientação Jurídica a uma Assistência.
Ocorre que, ao clicar em "Encaminhar" e depois escolher uma Assistência Judiciária, a Orientação Jurídica em questão continua mostrando "O caso não foi encaminhado para nenhuma assistência judiciária.", como se a associação não tivesse sido feita.

![7](https://user-images.githubusercontent.com/55855366/111907929-12033800-8a36-11eb-8581-a875e8aa59cd.png)

**Comment by babilima** [comment]
![Captura de Tela (45)](https://user-images.githubusercontent.com/71464467/119427603-acefeb00-bce1-11eb-94a2-841c2d55a1bb.png)
![Captura de Tela (46)](https://user-images.githubusercontent.com/71464467/119427605-ae211800-bce1-11eb-9c32-bb5bed47730b.png)

Issue corrigido, porém é necessário atualizar a página.

**Comment by gabriela-lp** [comment]
A issue de fato foi corrigida, mas ainda é necessário atualizar a página para que apareça a assistência judiciária para a qual foi encaminhada. 
![image](https://user-images.githubusercontent.com/70505460/134773836-52cd141e-b701-484c-91cf-dcd91f6c80d5.png)
![image](https://user-images.githubusercontent.com/70505460/134773841-2f5a018a-bc1a-402f-a7ba-06cf8bceb62a.png)

**Comment by diegopabulo** [comment]
Conferido em 26/01/2022.
