### ISSUE TITLE
Sub-área do Direito em "Cadastrar Orientação Jurídica" não está aparecendo no momento do cadastro, mas aparece depois na visualização

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#118]
Dentro de "Cadastrar Orientação Jurídica", a pergunta "Área do Direito" previa em requisito que deveria aparecer uma outra pergunta de "Sub-área do Direito" para permitir selecionar as opções Consumidor, Contratos, Responsabilidade Civil,
Reais, Família, Sucessões (requisito em print abaixo)

![image](https://user-images.githubusercontent.com/55855366/111908247-44f9fb80-8a37-11eb-9420-ba1c79e54f26.png)

![8](https://user-images.githubusercontent.com/55855366/111908205-1b40d480-8a37-11eb-943f-c8c25fb92c2e.png)

Curiosamente, nos parece que as Orientações Jurídicas em que selecionamos "Cível" em "Área do Direito" estão aparecendo como "Consumidor" por padrão na hora de visualizar a Orientação Jurídica depois de cadastrada. Em outras palavras, a opção parece existir em termos de programação mas não está sendo mostrada.

![9](https://user-images.githubusercontent.com/55855366/111908342-a1f5b180-8a37-11eb-8e62-f0b94a7158a8.png)

**Comment by babilima** [comment]
![Captura de Tela (47)](https://user-images.githubusercontent.com/71464467/119427797-140d9f80-bce2-11eb-8716-43879dbc5c02.png)
![Captura de Tela (48)](https://user-images.githubusercontent.com/71464467/119427798-14a63600-bce2-11eb-8dc7-229d2f122478.png)

Issue persiste.

**Comment by shevah7** [comment]
Testei a issue e agora as sub-áreas estão aparecendo devidamente, tanto na opção de direito cível, quanto de direito administrativo: 
![Captura de Tela (153)](https://user-images.githubusercontent.com/71346842/134390901-542eb358-fc47-48bb-ae7d-a98658531853.png)
![Captura de Tela (154)](https://user-images.githubusercontent.com/71346842/134390914-52fc2028-16ee-4757-bddf-7cd6d7d00fbb.png)

A situação me parece resolvida. 
I
