### ISSUE TITLE
Acrescentar sub-area "Administrativo" dentro de Área do Direito "Administrativo" em "Cadastrar Orientação Jurídica"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#119]
Ao entrar em "Cadastrar Orientação Jurídica" e em seguida selecionar "Administrativo" dentro de "Àrea do Direito", há atualmente as opções "Previdenciário" e "Tributário". Precisamos que seja acrescentada a opção "Administrativo" também em "Sub-área do Direito" para os casos que não se enquadram nas opções já existentes.

![10](https://user-images.githubusercontent.com/55855366/111908622-acfd1180-8a38-11eb-8ead-7525bc47e7d0.png)

**Comment by babilima** [comment]
![Captura de Tela (41)](https://user-images.githubusercontent.com/71464467/119426783-3bfc0380-bce0-11eb-97a8-f0a3571876ad.png)

Ainda não foi adicionado.

**Comment by RaphaGg** [comment]
Reproduzi o relato e o problema parece ter sido resolvido.

![issssssu](https://user-images.githubusercontent.com/89051386/133863603-757258c7-cc0f-484b-b853-c13375c4ea7a.png)
