### ISSUE TITLE
Adição de opção de "Desassociar" Atendido de "Orientação Jurídica para o Administrador

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#120]
Dentro de "Orientações Jurídicas", ao clicar em "Visualizar" em qualquer Orientação Jurídica temos a opção de "Associar Novo Atendido". Ocorre que, uma vez associado, não há a opção de "Desassociar" um Atendido nem mesmo para o Administrador - o que seria importante para os casos em que há erro ou equívoco.

![12](https://user-images.githubusercontent.com/55855366/111908962-03b71b00-8a3a-11eb-89ed-1fd90dfe77d3.png)

**Comment by babilima** [comment]
![Captura de Tela (42)](https://user-images.githubusercontent.com/71464467/119426881-71a0ec80-bce0-11eb-9f0b-e7f4cf610552.png)

Issue não resolvido.

**Comment by Math-carvalho** [comment]
Usuário: Administrador
Navegador: Google Chrome 

@Ale-eloy aparentemente, ainda não há a opção de "Desassociar" um Atendido 

![image](https://user-images.githubusercontent.com/71521066/134497103-ffc139f8-15b7-4d8c-aca0-c9f691b47664.png)

**Comment by diegopabulo** [comment]
Conferido em 26/01/2022.
