### ISSUE TITLE
Adição de dropdown de "Sub-área do Direito" em "Área do Direito" dentro de "Cadastrar Novo Caso" 

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#121]
Em "Casos", e em seguida "Cadastrar Novo Caso", há a pergunta "Área do Direito" com um dropdown com várias opções reunidas. 

![14](https://user-images.githubusercontent.com/55855366/111909289-7aa0e380-8a3b-11eb-8c26-30ab1da7dcd6.png)

Ocorre que precisamos que esse dropdown seja quebrado em dois dropdowns de "Área do Direito" e "Sub-área do Direito", tal qual no "Cadastro de Orientação Jurídica" exemplificado abaixo:

![image](https://user-images.githubusercontent.com/55855366/111909383-d8353000-8a3b-11eb-8098-ea44e3b5104d.png)

Isso é importante porque um dos principais problemas enfrentados atualmente pela DAJ é o cadastro impreciso de área do Direito, o que dificulta a posterior geração de relatórios e acompanhamento. Assim, a referida melhoria irá aprimorar o fluxo de trabalho da DAJ.

Obs.: ao tratar esse issue, gentileza observar também as melhorias já sugeridas no Issue #118 e #119.

**Comment by Math-carvalho** [comment]
Realizei testes no issue e o drop-down "Área do Direito" não foi dividido em "Área do Direito" e "Sub-área do Direito"

![image](https://user-images.githubusercontent.com/71521066/119515870-9b8ff880-bd4c-11eb-90cd-8aac94186706.png)

**Comment by Math-carvalho** [comment]
Usuário: Administrador
Navegador: Google Chrome

Aparentemente, a melhoria sugerida foi implementada: o dropdown agora disponibiliza uma nova seleção em determinadas opções. 

![image](https://user-images.githubusercontent.com/71521066/134496574-5e60c399-db91-4b62-9e78-fb31e6a1e4b8.png)

**Comment by gabriela-lp** [comment]
Conferido em 31/01/2022
