### ISSUE TITLE
Erro 500 ao "Editar Caso" dentro de "Casos" sem associar um Colaborador Externo

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#122]
Erro 500 ao tentar "Editar Caso" dentro de "Casos".
Reprodução: editando o caso 4, atribuimos "Orientador", um "Estagiário", **mas não associamos um "Colaborador Externo"**. Obs.: não colocamos arquivo nem editamos texto. Testamos com caso 2 e deu a mesma coisa. Ao clicar “salvar”, dá erro. 
Trata-se de erro grave, pois o colaborador externo é opcional nos casos. 

![15](https://user-images.githubusercontent.com/55855366/111909654-ecc5f800-8a3c-11eb-8e7f-c94f79520a05.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e o Erro 500 não foi corrigido. Testei a edição do Caso 21 e do Caso 20 e ambos apresentaram o referido erro após a tentativa de salvar as alterações em "Orientador" e "Estagiário" (os campos "Colaborador Externo" e "Descrição" não foram preenchidos ou modificados).

![image](https://user-images.githubusercontent.com/71521066/119516835-7780e700-bd4d-11eb-9286-73c75c991e47.png)

**Comment by shevah7** [comment]
Testei nos casos 2, 4, 20 e 21 e o Erro 500 persiste depois de tentar salvar as alterações feitas.
![Captura de Tela (161)](https://user-images.githubusercontent.com/71346842/134394284-22576bc9-13e5-4d48-a02d-7f516bd12669.png)

Além disso, na página de edição só estão aparecendo os campos "Orientador" e "Estagiário". Os campos "Colaborador Externo" e "Descrição" não aparecem, como pode ser visto no print: 
![Captura de Tela (162)](https://user-images.githubusercontent.com/71346842/134394267-24feb1a7-95c8-4891-854d-71c9d58f3bbf.png)

@Ale-eloy

**Comment by Ale-eloy** [comment]
@shevah7 eu tentei reproduzir o erro aqui, mas no meu caso funcionou normalmente tanto a edição do caso como também apareceram os campos "Orientador" e "Estagiário". Os campos "Colaborador Externo" e "Descrição".

Poderia tentar reproduzir o problema novamente, por favor? Estou tentando entender o que exatamente está dando origem a esses problemas.

**Comment by Ale-eloy** [comment]
Problema resolvido.
