### ISSUE TITLE
Dados do questionário socioecônomico não aparecem em "Visualizar" dentro de "Atendidos e Assistidos"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#123]
Ao tornar um "Atendido" em um "Assistido" por meio da opção "Tornar Assistido", o sistema abre uma nova página para o cadastro de uma série de informações relacionadas ao questionário econômico social (seções "Renda e Patrimônio" e "Dados Jurídicos")
Ocorre que esses dados do questionário econômico social não são mostrados na visualização do Assistido ao ir em "Assistidos e Atendidos" e depois em "Visualizar", ou seja, não há nenhum card na página do Assistido que mostre esses dados. Onde eles estão? O input deles está sendo gravado? Eles são essenciais para o fluxo de trabalho da DAJ.

![16](https://user-images.githubusercontent.com/55855366/111909811-7d9cd380-8a3d-11eb-91e1-4f417a8c4cf9.png)

**Comment by shevah7** [comment]
Os dados do questionário econômico social ainda não aparecem na visualização do Assistido em "Assistidos e Atendidos":
![Captura de Tela (101)](https://user-images.githubusercontent.com/71346842/119359869-733ac800-bc80-11eb-884c-b7ec43cf1d73.png)

Usuário: Administrador
Navegador: Chrome

**Comment by diegopabulo** [comment]
Usuário: Administrador
Navegador: Chrome

Os dados do questionário econômico-social agora estão aparecendo quando clica em "visualizar" os dados do assistido.

![image](https://user-images.githubusercontent.com/89043822/133907668-03931a26-0772-4930-b0b7-97427f485de7.png)
