### ISSUE TITLE
"Editar Caso" sem anexar nenhum arquivo apaga o arquivo anteriormente anexado

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#125]
Ao ir em "Editar Caso" dentro de "Casos", e editar as informações **sem subir um novo arquivo** e, em seguida, clicar em salvar, o sistema apaga o arquivo originalmente anexado. Em outras palavras, o Caso que antes tinha um arquivo passa a ficar sem arquivo nenhum. 
Sugestão: uma vez anexado um arquivo, somente ser possível substituir o arquivo por outro, mas não excluir.

![18](https://user-images.githubusercontent.com/55855366/111910312-a3c37300-8a3f-11eb-8e3c-8f23f8e5b20b.png)
![19](https://user-images.githubusercontent.com/55855366/111910314-a4f4a000-8a3f-11eb-8ef6-a5120770c2ea.png)
![20](https://user-images.githubusercontent.com/55855366/111910315-a4f4a000-8a3f-11eb-83f4-21718a8c59ed.png)

**Comment by shevah7** [comment]
Testei e o problema persiste, o arquivo anterior é excluído assim que ocorre qualquer tipo de edição no caso.

**Comment by ryanemmanuel** [comment]
O mesmo erro acontece quando **subimos um novo arquivo**, o anterior é substituído.

![image](https://user-images.githubusercontent.com/4334173/119374214-b2244a00-bc8f-11eb-8b98-bfbbe9aa06c4.png)


![image](https://user-images.githubusercontent.com/4334173/119374386-e566d900-bc8f-11eb-8952-fae91518a0bc.png)

**Comment by Math-carvalho** [comment]
Usuário: Administrador
Navegador: Google Chrome

Após fazer algumas edições no Caso, os arquivos originalmente anexados aparentemente foram mantidos.

![image](https://user-images.githubusercontent.com/71521066/134494089-725b4461-83d8-4f5b-9c41-93efc5cdef62.png)

![image](https://user-images.githubusercontent.com/71521066/134494103-809b1e1c-deab-4b65-8586-ea56c425f61f.png)

![image](https://user-images.githubusercontent.com/71521066/134494321-cd90f077-4d56-4deb-b68c-2292d69dc3db.png)

![image](https://user-images.githubusercontent.com/71521066/134494330-5c8252a6-d864-4a56-8e72-f74d7d18ef90.png)
