### ISSUE TITLE
Acrescentar opção "Documentos" dentro de "Tipo de Evento" em "Novo Evento"

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#126]
Na opção "Criar evento" dentro de um "Caso", sugerimos acrescentar a categoria “documentos” no dropdown. 
Convém mencionar que já havia um requisito “anexar arquivo PDF” para esse dropdown, que não foi colocado como tipo de evento. 
**Ao acrescentar, sugerimos então adicionar "Documentos" ao invés “anexar arquivo PDF” que não foi acrescentado** porque é importante ter esse tipo de evento para indicar documentos apresentados pelo assistido que não estejam nas demais categorias, e é mais específico que “outros”. 

![image](https://user-images.githubusercontent.com/55855366/111910603-cbffa180-8a40-11eb-87e3-bd9bb249a997.png)
![21](https://user-images.githubusercontent.com/55855366/111910502-68757400-8a40-11eb-982c-e42ab4c3125a.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e a sugestão "Documentos" não foi adicionada ao drop-down "Tipo de Evento".

![image](https://user-images.githubusercontent.com/71521066/119518560-004c5280-bd4f-11eb-9313-2fb49517c95d.png)

**Comment by elisacostab** [comment]
Reproduzi o relato e o problema parece ter sido resolvido, tendo em vista o acréscimo de "Documentos" no dropdown.

![Drop-down](https://user-images.githubusercontent.com/89033709/133826480-5e11083d-27e6-40c1-9920-d57dbee3291b.png)
