### ISSUE TITLE
Pop-up de "Mude sua senha | Sua senha foi exposta" aparece em login como administrador e outros

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#128]
Ao fazer login como Administrador (já reportado também em outros usuários), o Google Chrome mostra o seguinte aviso de alerta:

![senha exposta](https://user-images.githubusercontent.com/55855366/111911638-213db200-8a45-11eb-90aa-a4cc53fdff3b.png)

**Comment by babilima** [comment]
![Captura de Tela (40)](https://user-images.githubusercontent.com/71464467/119426651-fb9c8580-bcdf-11eb-9f21-8cf6c68c3dae.png)

Erro persiste

**Comment by torresnatela** [comment]
Esse aviso ocorre devido a uma verificação feita pelo google aos bancos de senhas roubadas. Não tem relação com o sistema do DAJ em si. Quer dizer que sua senha ja foi vazada em algum serviço. Mude a senha do administrador.
