### ISSUE TITLE
Orientador consegue editar Arquivos quando em tese não deveria

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#130]
**Logado como Orientador**, navegador Chrome, percebo que consigo editar os arquivos da seção de "Arquivos" quando em tese eu não deveria poder segundo a tabela de permissões.

1. Tabela de permissões:
![image](https://user-images.githubusercontent.com/55855366/113635593-4df9e800-9647-11eb-9253-e4cdd5f919e4.png)

2. Exemplo de arquivo original:
![image](https://user-images.githubusercontent.com/55855366/113635768-9addbe80-9647-11eb-9719-01f125592671.png)

3. Informações do arquivos editadas com sucesso mesmo não podendo em tese:
![image](https://user-images.githubusercontent.com/55855366/113635839-bc3eaa80-9647-11eb-9c73-052c59cd0853.png)

**Comment by babilima** [comment]
![Captura de Tela (39)](https://user-images.githubusercontent.com/71464467/119426413-9052b380-bcdf-11eb-8eaf-4a1c7a3ae22c.png)

Erro persiste

**Comment by Lucardoso06** [comment]
![image](https://user-images.githubusercontent.com/89036394/134355427-0b475ae2-e249-4263-9e5e-0cd1e0ae50b4.png)

![image](https://user-images.githubusercontent.com/89036394/134355470-e289a125-2167-444b-8b01-1a4fe8775138.png)

Não consigo encontrar a opção de editar arquivo. Desse modo, issue parece ter sido corrigido.
