### ISSUE TITLE
Relatórios são gerados desformatados

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#131]
Logado como administrador no navegador Chrome, percebo que os relatórios gerados estão desformatados e estão sendo emitidos vazios, apesar de haver informações (fizemos o teste com o relatório de "horário de chegada e saída de estagiários", mas o problema apontado aqui vale para **todos** os relatórios):

- O site gera um preview funcional e correto das informações:
![image](https://user-images.githubusercontent.com/55855366/113636685-5e12c700-9649-11eb-9e71-83734f54a110.png)

- As informações até são incluidas no relatório, mas é impossível tratá-las porque estão numa mesma célula e estão desformatadas:
![image](https://user-images.githubusercontent.com/55855366/113636732-75ea4b00-9649-11eb-8690-edbd6077f0f6.png)

**Comment by Ale-eloy** [comment]
Esse issue pode ser tratado conjuntamente com o issue #132

**Comment by Ana-Rafaela** [comment]
Usuário: Administrador
Navegador: Chrome

Ao que parece, o erro persiste. Porém, não sei se contribui em algo, mas percebi que, pelo Google Planilhas, a formatação fica correta.

Preview:
![image](https://user-images.githubusercontent.com/71299300/119572030-85a02900-bd88-11eb-8ec1-a1fcc7cf491d.png)

Google Planilhas:
![image](https://user-images.githubusercontent.com/71299300/119572723-9309e300-bd89-11eb-8e64-3aa25b29dd22.png)

Excel:
![image](https://user-images.githubusercontent.com/71299300/119572748-9e5d0e80-bd89-11eb-9c29-a76d873205c8.png)

**Comment by Math-carvalho** [comment]
Usuário: Administrador
Navegador: Google Chrome 

Aparentemente, o erro ainda não foi solucionado.

![image](https://user-images.githubusercontent.com/71521066/134493046-c73c2a60-db66-4c89-875f-97ea76e932a7.png)

**Comment by diegopabulo** [comment]
Conferido em 26/01/2022.
