### ISSUE TITLE
Sugestão de geração de relatório de presença com indicação de todos os usuários e seus cargos

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#132]
Durante os testes nós percebemos que a planilha gerada pelo relatório de presença de estagiários precisa de alguns ajustes para ser realmente funcional para o fluxo de trabalho atual. Atualmente, o relatório de presença gerado abrange apenas os estagiários, mas a DAJ possui vários outros colaboradores (professor, colaborador de projeto, etc.), todos os quais também batem ponto. Pensando nisso, elaboramos duas abordagens para a situação:

### **1. Sugestão n° 1:** 
Produzir um relatório com registros de presença de **todos** os usuários, ao invés de só relatórios de estagiários. Isso é importante porque (i) na prática a DAJ precisa verificar de mais colaboradores do que somente os estagiários; (ii) percebemos que sem esse relatório todas as informações de presença de outros usuários que não os estagiários vão para o limbo, ou seja, não geram nenhum output (em outras palavras, tanto faz se o um professor bate ponto ou não, porque não saberemos no final do mês). 
Com base nisso, nossa sugestão é gerar um planilha de presença abrangendo todos os usuários, e deixar indicado (a) o cargo e (b) se foi no plantão ou não. Não precisa gerar tabela no site, basta apenas o arquivo para download e já estaria ótimo.

### **2. Sugestão n° 2:** 
Nós entendemos que a Sugestão n° 1 seja o melhor cenário para absorver 100% o fluxo de trabalho e o que pretendiamos com essa funcionalidade. Subsidiriamente, apenas na hipótese de não ser possível ou não ser de forma alguma prático implementá-la, nós pensamos numa hipótese alternativa: adicionar apenas uma coluna de plantão (do tipo "sim" ou "não") para indicar se a presença marcada foi feita em dia do plantão do estagiário ou não. Esse dado já é colhido na página de confirmação de presença, que faz a diferenciação das presenças normais e das presenças em dia de plantão, então na prática é uma consulta de banco de dados com um campo a mais. Não precisa gerar tabela no site, basta apenas o arquivo para download e já estaria ótimo.

![image](https://user-images.githubusercontent.com/55855366/113639231-155e0c80-964f-11eb-85a7-d764ed74b549.png)

![image](https://user-images.githubusercontent.com/55855366/113639922-a1bcff00-9650-11eb-8702-9b7babdbb08c.png)

**Comment by Ale-eloy** [comment]
Esse issue pode ser tratado conjuntamente com o issue #131

**Comment by Ana-Rafaela** [comment]
Não houve implementação de nenhuma das sugestões até a presente data.

![image](https://user-images.githubusercontent.com/71299300/119573590-dca6fd80-bd8a-11eb-9f03-aa69c451a9bf.png)

![image](https://user-images.githubusercontent.com/71299300/119573781-1ed03f00-bd8b-11eb-96d1-ea38a6327261.png)

**Comment by BrunoMoReis** [comment]
**Conferido em 02/02/2022.** 

**Houve a implementação de relatório com registros de presença de todos os usuários, ao invés de só relatórios de estagiários(SUGESTÃO 1).** 


![Captura de tela 2022-02-02 214733a](https://user-images.githubusercontent.com/86381837/152262436-cea804c5-dd69-4712-8196-5132afefa249.png)


**Gerado uma planilha de presença abrangendo todos os usuários, e deixar indicado (a) o cargo e (b) se foi no plantão ou não**


![SSS](https://user-images.githubusercontent.com/86381837/152262797-6b545703-7c58-4127-adab-2933a552e6e5.png)
