### ISSUE TITLE
Erro 500 ao tentar cadastrar Arquivo sem ter um arquivo anexado

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#133]
Logado como administrador, navegador chrome, dentro da aba "Arquivos" ao tentar "Adicionar Arquivo" sem ter um arquivo anexado o sistema mostra um erro 500 conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/55855366/113640939-f2cdf280-9652-11eb-9f95-e26c22601bb0.png)

Embora não seja crítico, seria importante aparecer só uma mensagem de erro.

**Comment by shevah7** [comment]
Testei e o sistema dá o mesmo erro 500:
![Captura de Tela (102)](https://user-images.githubusercontent.com/71346842/119361182-c2352d00-bc81-11eb-820e-7454dc08caf6.png)

Usuário: Administrador
Navegador: Chrome

**Comment by diegopabulo** [comment]
Usuário: Administrador
Navegador: Chrome

Fiz o mesmo processo e o sistema não apresentou o erro 500.

![image](https://user-images.githubusercontent.com/89043822/133907437-7df893fa-62e6-44b7-9ab5-ed63d018fb9a.png)
