### ISSUE TITLE
Datas de início e fim de bolsa incoerentes durante cadastro de novo usuário/ erro 500 ao editar usuário

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#134]
Logado como administrador, navegador chrome, durante o "Cadastro de Usuário", percebemos que seria interessante na parte do cadastro das datas de início e fim da bolsas impedir que o usuário cadastre datas incoerentes, isto é, início da bolsa posterior ao fim da bolsa:

![image](https://user-images.githubusercontent.com/55855366/113642681-c4eaad00-9656-11eb-8ecc-dc8a16ad8bcf.png)

**Comment by Ana-Rafaela** [comment]
O sistema permanece permitindo o cadastro de usuário com datas de bolsas incompatíveis, bem como com datas de entrada e saída incoerentes.

![image](https://user-images.githubusercontent.com/71299300/119495633-fc153a80-bd38-11eb-8db5-820728966e09.png)

**Comment by Lucardoso06** [comment]
Utilizando navegador google, logado como administrador, na aba meu usuário, logo após clicar em editar, ocorreu o erro 500.

![image](https://user-images.githubusercontent.com/89036394/152270981-0f524a0b-3baf-4bf2-ab21-a9ff0a4efea5.png)

Problema não resolvido.

**Comment by Ale-eloy** [comment]
@Lucardoso06 poderia descrever melhor como chegou nesse Erro 500? Imagino que possa ter algo a ver com usuários antigos do sistema que, depois de migrado o Banco de Dados, dão Erro 500. Eu fiz o teste com um usuário criado recentemente e funcionou. 


> Utilizando navegador google, logado como administrador, na aba meu usuário, logo após clicar em editar, ocorreu o erro 500.
> 
> ![image](https://user-images.githubusercontent.com/89036394/152270981-0f524a0b-3baf-4bf2-ab21-a9ff0a4efea5.png)
> 
> Problema não resolvido.

Pelo que testei aqui, me parece que o issue inicialmente reportado foi devidamente corrigido, como se vê na imagem abaixo:

![image](https://user-images.githubusercontent.com/55855366/152344975-f47e706b-ca4c-481b-94bf-c2f06e251fde.png)

**Comment by Lucardoso06** [comment]
O erro 500 se deu seguindo os seguintes passos:

No navegador google, logado como administrador, na aba "meu perfil", cliquei na opção editar função.

![image](https://user-images.githubusercontent.com/89036394/152348514-a2d78cc1-401a-4864-bd3d-f2cf56e75354.png)

A próxima página aberta foi o erro 500.

![image](https://user-images.githubusercontent.com/89036394/152348578-2b9cd866-55cf-4ed2-92b8-fc9e0891ab60.png)

**Comment by rvnovaes** [comment]
Na página de cadastro aparece o pop up de datas incoerentes, mas na página de edição não.

**Comment by vicvital** [comment]
- inconsistências nas datas de início e final da bolsa corrigidas: só é possível selecionar data de fim posterior à data de inícios 
- administrador não consegue editar a conta de outro administrador, porém é possível editar outros usuários 
- encontrei outras inconsistências nos dados de cadastro de usuário, que cadastrei como novo issue

**Comment by IsaBettine** [comment]
Testei essa issue pelo navegador do Firefox e constatei que foi resolvida.

**Comment by IsaBettine** [comment]
Testei essa issue pelo navegador do chrome e do firefox, logado como administrador e constatei que foi resolvida.
