### ISSUE TITLE
Numeração dos Eventos dentro dos Casos começa incorretamente

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#138]
Como Administrador, eu criei um caso novo de n° 17, e em seguida criei o primeiro Evento do caso. Ocorre que o primeiro evento já começou numerado a partir do número '10', ao invés de começar do '1'.

![image](https://user-images.githubusercontent.com/55855366/119283877-aa738f80-bc14-11eb-9efe-15f3bc6fb0af.png)

Em seguida, eu apaguei o Evento criado anteriormente (que ficou numerado como '10') e então criei um novo Evento, que foi numerado pelo sistema como '11'. Em resumo a numeração está incorreta.

![image](https://user-images.githubusercontent.com/55855366/119284340-dcd1bc80-bc15-11eb-8b0e-a2df94da7cab.png)

**Comment by Lucardoso06** [comment]
Numeração consertada com sucesso. Conferido em 27/01/2022
