### ISSUE TITLE
Esclarecimento: página Meus Casos parece não funcionar ou suas regras de funcionamento não estão claras

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#139]
Fizemos alguns testes com a página "Meus Casos" e estamos em dúvida sobre como ela foi programada para funcionar. Até o momento, não conseguirmos ver ela ser preenchida em nenhum cenário. A pergunta é: o que o sistema olha para checar se um caso entra nessa página? Precisamos saber como vocês programaram essa página para podermos testar se está funcionando de acordo.

Exemplo: testei como Orientador (orientador2@daj.com), e mesmo tendo um caso atribuído a esse usuário, o sistema não mostra o caso na página "Meus Casos".

![image](https://user-images.githubusercontent.com/55855366/119286559-0ccf8e80-bc1b-11eb-8c04-f94bae124213.png)

![image](https://user-images.githubusercontent.com/55855366/119286688-5324ed80-bc1b-11eb-9125-c21388831d52.png)

**Comment by Ale-eloy** [comment]
Conferi novamente e me parece que a página "Meus Casos" foi retirada do sistema. Não encontrei ela mais dentro de "Casos".
![image](https://user-images.githubusercontent.com/55855366/152338291-747eba01-2da9-4076-aae0-9434e78167f0.png)

Todavia, eu utilizei a mesma URL que aparece no comentário de 23/05/21 ( _/casos/meus_casos_ ) e descobri que a página ainda existe no sistema, ela só foi retirada do acesso do usuário.
![image](https://user-images.githubusercontent.com/55855366/152338212-acfd47da-b2ec-4edd-893a-0dbad84fe917.png)

Realizei mais testes e descobri que o contador "Total de casos: " não está funcionando. Fiz login como estagiário de direito e atribui 2 casos a mim como estagiário. Apesar disso, a página "Meus Casos" continuava monstrando "Total de casos: 0". Logo, a página está inoperante.

**Comment by vicvital** [comment]
- página "meus casos" continua desindexada da visão do usuário (orientador afonso), mas pode ser acessada digitando o endereço. ainda assim, nenhum caso atribuído ao orientador (3 casos) entra na página. 

![image](https://user-images.githubusercontent.com/108194685/188449809-213157b6-2caa-40fa-ac98-49dffcf74806.png)

**Comment by vicvital** [comment]
- "internal server error" na página "meus casos", tentando acessar tanto pelo endereço quanto clicando no botão dos usuários. 

![image](https://user-images.githubusercontent.com/108194685/193356420-a046aff1-c48e-44a0-aec9-c3d4161665e0.png)

**Comment by Ale-eloy** [comment]
Issue corrigido. Novo problema reportado no issue #204
