### ISSUE TITLE
"Estagiário de direito responsável" dentro de "Dados do caso" parece não corresponder a realidade

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#140]
O card "Dados do Caso" dentro de "Visualizar" algum caso está mostrando errado o nome do Estagiário de Direito envolvido.

1. Abrir um caso (no meu exemplo, o caso n° 18) e clicar em "Editar";
2. Alterar o "Estagiário de direito responsável" dentre as alterações possíveis;
3. Depois de salvar, é possível ver que a parte "Dados do caso" está mostrando o Orientador ao invés do Estagiário de Direito inserido anteriormente.
4.  Apesar disso, a página do card dentro de "Gestão de Casos" parece estar mostrando os dados corretos do Estagiário de Direito".

(1)
![image](https://user-images.githubusercontent.com/55855366/119287101-2a512800-bc1c-11eb-8632-9499651eb3fe.png)
(2)
![image](https://user-images.githubusercontent.com/55855366/119287153-46ed6000-bc1c-11eb-9823-6d1ef9127d47.png)
(3)
![image](https://user-images.githubusercontent.com/55855366/119287182-579dd600-bc1c-11eb-9fdf-9c9f9e0c80b6.png)
(4)
![image](https://user-images.githubusercontent.com/55855366/119287269-8ae06500-bc1c-11eb-9658-66b4c4583cc0.png)

**Comment by ryanemmanuel** [comment]
Pelo que percebi, no campo Estagiário de Direito responsável está sendo exibido o mesmo usuário listado como "usuário responsável"

![image](https://user-images.githubusercontent.com/4334173/119360767-55ba2e00-bc81-11eb-92d3-fc2fc17980db.png)

**Comment by gabriela-lp** [comment]
Conferido em 02/02/2022.
