### ISSUE TITLE
Treinamento Luca

### ISSUE THREAD

**Issue by Lucardoso06** [gestaolegalufmg/gestaolegal#143]
![ativ 01](https://user-images.githubusercontent.com/89036394/131591059-8a8c4b7f-7fab-49f5-8c8e-bf7ed112e2e6.png)
![Atividade 01](https://user-images.githubusercontent.com/89036394/131591068-dd4dee3d-59ba-41f7-a8af-e2e47df71678.png)

Como visto nos prints, consegui facilmente cadastrar orientações, descrevê-las e associar atendidos a elas. Os comandos foram claros e os gifs úteis.
Notei algumas coisas:
1°- BUG: Por vezes, foi necessário clicar em "Sair" duas vezes para sair da página do cadastro da Orientação. Frescura, mas como foi notável digo que pessoalmente tirou fluidez da navegação.
2°- Não é possível retirar pessoas já associadas à Orientação. Desse modo, caso eu associe a Orientação ao atendido errado, não conseguiria desfazer o processo: precisaria cadastrar tudo de novo.
Assim, gostaria de propor de modo geral uma reformulação da associação da orientação a um atendido. Seria mais interessante que, desde a primeira etapa de associação, ficasse evidente na tela quais atendidos estão sendo associados à Orientação na medida em que clico nos seus nomes na barrinha de busca. Também, colocar um "Xzinho" no nome para que seja possível excluir a associação de uma vez tanto no momento de associação original quanto na hora de editar - num modelo parecido com a criação de grupo no whatsapp. Os membros vão aparecendo na busca e posso marcar mais de um por vez e desmarcar uma pessoa se quiser.

**Comment by Ale-eloy** [comment]
Valeu Luca! Vamos manter essa sua sugestão na memória ai pra sugerirmos certinho na próxima rodada de desenvolvimento!
