### ISSUE TITLE
Treinamento Diego

### ISSUE THREAD

**Issue by diegopabulo** [gestaolegalufmg/gestaolegal#144]
PASSO 1. Acessei o menu arquivos e cliquei em visualizar.

![image](https://user-images.githubusercontent.com/89043822/132102181-c8f4b487-16c6-4e95-998e-ecdd6dd522ef.png)

PASSO 2. Apareceram os seguintes dados. Cliquei em baixar.

![image](https://user-images.githubusercontent.com/89043822/132102211-cb883184-4e90-498f-9c34-be2deb494a2c.png)
 

PASSO 3. O arquivo em PDF abriu no navegador.

![image](https://user-images.githubusercontent.com/89043822/132102266-199c06e0-3f05-4e48-bbfa-fad16bf3f624.png)

 
PASSO 4. Em arquivos cliquei no botão adicionar arquivo, validei cada campo. O único que foi opcional foi o campo da descrição. Depois preenchi as informações abaixo e cliquei em enviar.
 
![image](https://user-images.githubusercontent.com/89043822/132102270-bf8d3805-ab24-4542-ba91-598e49d51b76.png)

PASSO 5. Arquivo enviado e gravado com sucesso.

![image](https://user-images.githubusercontent.com/89043822/132102275-f297a03f-00a7-4ba7-8f5c-83d34bcd5d95.png)

 
PASSO 6. Em arquivos também exclui alguns arquivos.

![image](https://user-images.githubusercontent.com/89043822/132102278-f535d2a4-f6ee-496e-a79d-f02e5e8bb11c.png)

**Observação: Quando clico em baixar o documento, o PDF abre na mesma aba do sistema. Pensando na usabilidade, o ideal é abrir uma nova aba.**

**Comment by Ale-eloy** [comment]
Obrigado, Diego! Sua sugestão faz sentido, vamos guardar ela para sugerir na próxima rodada de desenvolvimento!
