### ISSUE TITLE
Treinamento Bruno

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#145]
**Eventos**

**1 - Visualizar eventos de um caso**
- _Na barra lateral, vá em "Casos" e depois "Gestão de Casos"_
- Em seguida, localize o caso desejado para fazer a visualização.
- Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
- Por fim, clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".

![Home - Gestão Legal - Google Chrome 2021-09-04 22-53-51 (3)](https://user-images.githubusercontent.com/86381837/132112523-2d219f06-7cea-432a-9a43-99c5c0cd7bc4.gif)

A etapa "Visualizar eventos de um caso" apresentou erro 500 na primeira etapa.

**2 - Criar eventos**
_-Na barra lateral, vá em "Casos" e depois "Gestão de Casos"_
-Em seguida, localize o caso desejado para fazer a visualização.
-Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
-Aperte a opção "Criar evento", localizada na parte superior direita.
-Preencha as informações requeridas e aperte em "Enviar".

![Home - Gestão Legal - Google Chrome 2021-09-04 22-53-51 (3)](https://user-images.githubusercontent.com/86381837/132112631-d1956b13-f4a3-4175-bf04-203d7a5b26f0.gif)

Apresentou erro 500 na primeira etapa do processo "Criar eventos".

**3 - Editar eventos**
_-Na barra lateral, vá em "Casos" e depois "Gestão de Casos"_
-Em seguida, localize o caso desejado para fazer a visualização.
-Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
-Clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".
-Selecione o botão "Editar" ao lado do evento que deseja editar.
-Após realizar as edições necessárias, aperte em "Enviar".

![Home - Gestão Legal - Google Chrome 2021-09-04 22-53-51 (3)](https://user-images.githubusercontent.com/86381837/132112653-884363f2-ee89-4e88-ad95-a91eebf63d1d.gif)

Apresentou erro 500 na primeira etapa do processo "Editar eventos".

**4 - Excluir eventos**
_-Na barra lateral, vá em "Casos" e depois "Gestão de Casos"_
-Em seguida, localize o caso desejado para fazer a visualização.
-Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
-Clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".
-Selecione o botão "Excluir" ao lado do evento que deseja excluir.

![Home - Gestão Legal - Google Chrome 2021-09-04 22-53-51 (3)](https://user-images.githubusercontent.com/86381837/132112704-e53b59f9-7c77-498a-849b-922fe7743b10.gif)

Apresentou erro 500 na primeira etapa do processo "Excluir eventos".

É evidente um erro da etapa inicial do tópico de eventos, tal erro afeta todas as etapas e apresenta-se como erro **500 Internal Server Error,**

**Comment by Ale-eloy** [comment]
Ei Bruno, obrigado pelo post! Vamos resolver o erro 500!
