### ISSUE TITLE
Treinamento Elisa

### ISSUE THREAD

**Issue by elisacostab** [gestaolegalufmg/gestaolegal#146]
### **Treinamento referente aos casos:**

1- Fui na barra lateral, em Casos, onde solicitei para cadastrar novo caso e preenchi as informações solicitadas, clicando para criar novo caso.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/89033709/132129594-4bcc8858-5940-49a6-8473-2b8f5ef642cc.png)

Entretanto, ao tentar criar novo caso, deu erro 500, tanto para criar novos casos, quanto para ver os meus casos, consequentemente não consegui editar 

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/89033709/132129657-fc528470-8007-414c-9468-22586f9269eb.png)

2- Com relação à gestão de roteiros, consegui acessar e adicionar um:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89033709/132129838-8b80d086-2501-4a5b-98b1-1115708f4710.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/89033709/132129901-9e3ac362-8773-4ff1-9711-063f90886530.png)

3- Depois consegui excluí-lo utilizando o comando no próprio site, foi tranquilo 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/89033709/132129975-31f6e9b3-21cf-45ae-af53-fa1e3194cad4.png)

 
### **Treinamento referente à gestão de usuários** 

1- Fui em gestão de usuário e solicitei para adicionar um novo, preenchendo os dados solicitados

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/89033709/132130175-0f280ec8-a560-4d21-9ba1-56d7d562de4c.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/89033709/132130181-cb541743-4ced-42eb-842b-33c4210f0727.png)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/89033709/132130319-f8aa9f14-52be-4661-8e33-89806318ba4d.png)
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/89033709/132130336-049ebbda-1d47-408e-bf67-a18432dc07d3.png)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/89033709/132130338-a490ce53-3058-49b5-a594-72d27391f500.png)
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/89033709/132130340-3bcb6901-0f6d-4bd4-9def-a8075568e29a.png)

2- Foi muito tranquilo. Apenas uma sugestão que deixo, com relação à criação de senha, em dados de acesso ao sistema, seria colocar os critérios solicitados para a senha logo abaixo, pois apenas descobria a ausência de algum (ex: necessidade de caracteres especiais), quando, ao preencher tudo e tentar criar o novo usuário, recarregava a página, de modo a acusar a necessidade do caractere, ou alguma outra necessidade faltante na senha.

**Comment by Ale-eloy** [comment]
Ei Elisa, obrigado! Faz sentido sua sugestão, vamos manter ela gaurdada para sugerirmos na próxima rodada de desenvolvimento!
