### ISSUE TITLE
Treinamento Guilherme 

### ISSUE THREAD

**Issue by guisouza3** [gestaolegalufmg/gestaolegal#147]
### Controle de atendidos e assistidos

1- Preenchi os campos com dados teste.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/89096123/132130111-d17291c3-c0d2-443b-bb13-f4a4f7fe9531.png)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89096123/132130110-1882b5c6-3631-4a32-bd3b-14c562fd1add.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/89096123/132130109-c433c20b-5702-464f-8000-60d339b4935e.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/89096123/132130112-60d16e55-c4ac-4960-9526-a926a37ad1ee.png)

- No campo "Como ficou sabendo da DAJ?", selecionei a opção "Outros". Porem, senti falta da abertura de um novo espaço para detalhar o que seria esse "outros".

2- No entanto, não foi possível realizar o cadastro devido ao Erro interno do servidor. 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/89096123/132130384-a516c98f-3246-4849-aa77-202eb95fdf18.png)

3- Mesmo tentando o cadastro com dados reais (dados preenchidos corretamente, obedecendo numerações e etc), o erro persistiu. 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/89096123/132130425-fab2525f-543e-4b87-bba8-82daa1879aff.png)

4- Ao realizar o preenchimento, não localizei as lacunas sobre Dados Pessoais, Dados sociais e Renda e Patrimônio, visualizado após minha consulta nos cadastros já realizados.

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/89096123/132130450-4a10c4da-e4f7-4153-b476-3f95ca34ae3e.png)

5 - Fiquei em dúvida no motivo pelo qual não aparece "Tornar assistido" em alguns casos. Talvez o motivo seria que nos casos em que não aparecem essa opção os mesmos já estariam sendo assistidos? 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/89096123/132130590-0e48aae9-625c-4932-b31d-8f26b91cb6f5.png)

6- Acredito ser interessante padronizar o formato das numerações e dos campos numéricos na realização dos cadastros. 

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/89096123/132130623-e4c4fe57-e61c-4edf-b709-b9664acf2a24.png)

###  **Escala do plantão**

1- Selecionei a data e preenchi a abertura e fechamento do plantão.
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/89096123/132131054-f5fde587-55c7-4dbf-a7a1-069bc8b2cf9b.png)

2- Cadastro realizado com sucesso. 
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/89096123/132131077-d88a43d9-08d4-4341-b33b-6485d6906c72.png)

3- Senti falta de um "resumo" ao selecionar o dia marcado descrevendo as informações mais pertinentes do plantão. 

![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/89096123/132131136-21f9b0b1-aa15-4f9b-a26b-45a9ff1b22b2.png)

4- Tentei editar o plantão mas a opção que apareceu foi apagar tudo.. acho que seria interessante ter uma opção que editasse o cadastro e não excluísse por completo. Não tentei excluir devido ao receio de apagar tudo. 
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/89096123/132131173-3adc2325-fc33-4bc2-bdc7-571f81af5fd7.png)

**Comment by Ale-eloy** [comment]
EI Guilherme, obrigado! Vamos manter suas sugestões guardadas para a próxima rodada de desenvolvimento!
Apenas para me lembrar depois quando eu voltar aqui, a sugestão de "4- Ao realizar o preenchimento, não localizei as lacunas sobre Dados Pessoais, Dados sociais e Renda e Patrimônio, visualizado após minha consulta nos cadastros já realizados." já foi identificada como um problema antes e já pedimos a correção dela, então em tese a próxima versão vai vir com isso corrigido. Precisaremos ficar atentos quanto a isso!

**Comment by gabriela-lp** [comment]
Erro 500 corrigido, foi possível cadastrar novo atendido sem complicações. Informações presentes no manual estão claras.
![image](https://user-images.githubusercontent.com/70505460/134355421-a0c1d5be-fe4e-4c2a-9aaf-fb0c646110fc.png)

**Comment by guisouza3** [comment]
@Ale-eloy 

Continua não aparecendo, no ato do preenchimento,  as lacunas sobre Dados Pessoais, Dados sociais e Renda e Patrimônio, 

![image](https://user-images.githubusercontent.com/89096123/134451960-a733bf8b-31f5-44db-b856-78bf4bbc7fea.png)

![image](https://user-images.githubusercontent.com/89096123/134451982-7c6eb517-5691-419c-9a17-c18cf4927e36.png)

Muitas lacunas que requerem informações em números ainda estão podendo ser preenchidas com letras, sem ao menos espaço de caracteres definidos, Acho que seria interessante padronizar esses quadrantes. 

Por fim, conforme relatado pela @gabriela-lp , o cadastro pode ser concluído sem o ERRO 500.

**Comment by Ale-eloy** [comment]
Ei @guisouza3 ! Obrigado pelo feedback. 

1. Vamos deixar mais pra frente a inclusão do campo a ser aberto em "outros".
2. Já resolvido.
3. Já resolvido.
4. Quanto a isso, a parte de renda não apareceu para você porque ela só é ativada depois que você clica em tornar o atendido em um assistido. Como ali você estava só criando um atendido, não apareceu.
5. O "Tornar assistido" não aparece porque eles já são assistidos.
6. Acredito que apenas os cadastros mais antigos não estão padronizados, porque são da época que não havia máscaras no preenchimento. Pelo que percebi no cadastro as máscaras existem agora, então todos os usuários novos aparecerão corretamente.

Por fim, sobre o apagar do plantão, nós decidimos deixar como está mesmo porque pode ser resolvido com treinamento mesmo.

Muito obrigado!!
