### ISSUE TITLE
Treinamento Raphael

### ISSUE THREAD

**Issue by RaphaGg** [gestaolegalufmg/gestaolegal#148]
(i) Conforme as instruções contidas no manual, acessei, de início, a aba plantão para realizar o registro de entrada e saída do plantão, informando horários aleatórios. Após essa etapa, fui novamente na aba plantão, para confirmar a presença. Selecioneii o dia desejado e fiz a confirmação. A seguir, é possível verificar os horários de entrada e saída, bem com a confirmação de tais operações.

![Print confirmação](https://user-images.githubusercontent.com/89051386/132252092-c4cab624-1b3d-4b35-a5e0-f2735d752c8b.png)

(ii) Achei a forma como o manual está estruturado bem didática e simples de compreender, os gifs estão nítidos e facilitam bastante a visualização da operação, porém, não consegui acessar a aba 6.3 "confirmar plantão dos colaboradores", motivo pelo qual não fui capaz de realizar essa tarefa no treinamento.

(iii) Na minha experiência, não encontrei nenhum problema durante o uso do software.

**Comment by Ale-eloy** [comment]
Ei Raphael, que bom que curtiu o manual! Obrigado pelo post. O ponto 6.3 realmente está faltando, vou acrescentar e mandar completo para vocês!
