### ISSUE TITLE
Horário de criação/modificação do caso não bate com o horário do sistema

### ISSUE THREAD

**Issue by elisacostab** [gestaolegalufmg/gestaolegal#149]
1- Por meio das instruções no manual consegui facilmente criar um novo caso
![caso criado](https://user-images.githubusercontent.com/89033709/133792024-db7da46a-6351-4dc5-9a1d-b70b16199353.png)

A única ressalva que tive foi que o horário de criação/modificação está errado.

2- Consegui editá-lo facilmente, assim como gerenciar os assistidos, de modo a excluir o assistido e substituir por outro.
![editar caso](https://user-images.githubusercontent.com/89033709/133792253-14f8160d-f338-41b7-a880-c7a2140d12fc.png)
![consegui gerenciar assitidos](https://user-images.githubusercontent.com/89033709/133792312-b72a98b1-292a-41b1-8b91-44e3b7f6a9b8.png)
![consegui trocar o assistido](https://user-images.githubusercontent.com/89033709/133792345-c7541fbb-d7c8-42b6-b613-2ec5deff96b9.png)

3- Consegui facilmente, por meio das instruções, indeferir o caso, assim como posteriormente deferi-lo.
![indeferimento](https://user-images.githubusercontent.com/89033709/133793714-46326c66-f604-432a-be4c-ca7a8a7466bb.png)
![editar para tentar deferir](https://user-images.githubusercontent.com/89033709/133792492-27b60cce-adba-4c88-936d-8e38f14780d6.png)
![consegui deferir](https://user-images.githubusercontent.com/89033709/133792535-dd9f4a71-69b9-43a1-a597-686b7ca17d0c.png)

4- Tive apenas problema para excluir o caso em questão (caso 22). Tentei depois com outro caso, que criei, e consegui exclui-lo facilmente, todavia o erro 500 persiste quando tento excluir o caso 22. 
![erro ao tentar excluir caso](https://user-images.githubusercontent.com/89033709/133792772-7414faaa-01be-44ee-9509-5cff8c2af1eb.png)

5- Quanto à sugestão, acho que apenas acrescentaria no manual de instruções a possibilidade de depois de indeferir/deferir um caso, isso ser possível de mudança. De modo que, ao clicar em editar o caso, após indeferi-lo, por exemplo, é possível mudar o status para ativo (deferido). Não sei se seria algo óbvio, quando fiz fiquei em dúvida e buscando consegui editar e mudar o status de forma fácil, mas não sei se seria para todo mundo.

**Comment by gabriela-lp** [comment]
O erro 500 para exclusão do Caso 22 persiste @Ale-eloy 
![image](https://user-images.githubusercontent.com/70505460/134354101-f71aac6e-e904-4ea7-958e-7ea686d7acd2.png)
Quanto à sugestão apresentada, referente à indicação de possibilidade de mudança do status deferido/indeferido, ainda não houve inclusão no manual.

**Comment by Ale-eloy** [comment]
@elisacostab essa questão do horário ainda tá dando problema? Se sim, podemos gerar um novo issue pra ela!

**Comment by elisacostab** [comment]
@Ale-eloy fiz um teste aqui agora modificando um caso já existente e o erro persiste quanto ao horário.

![erro hora](https://user-images.githubusercontent.com/89033709/135323466-89b2ac0b-3a7d-4822-9d5a-604a22c46c4a.png)
![hora errada](https://user-images.githubusercontent.com/89033709/135323489-02eac0ca-4323-451e-9554-56faa9cb73fe.png)

**Comment by Ale-eloy** [comment]
Entendido, precisaremos então corrigir esse problema do horário incongruente.

**Comment by gabriela-lp** [comment]
Conferido em 02/02/2022.
