### ISSUE TITLE
Treinamento Bruno 2 - Eventos

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#150]
**Eventos**

 Os problemas apresentados anteriormente foram solucionados . 
 O Manual foi super efetivo para a resolução das etapas juntamente com as etapas em tópicos.

**1. Visualizar eventos de um caso**
Na barra lateral, vá em "Casos" e depois "Gestão de Casos"
Em seguida, localize o caso desejado para fazer a visualização.
Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
Por fim, clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".

![visualizar](https://user-images.githubusercontent.com/86381837/133834880-158ebf28-1196-4b35-be87-df2a82908af1.gif)

**2. Criar eventos**
Na barra lateral, vá em "Casos" e depois "Gestão de Casos"
Em seguida, localize o caso desejado para fazer a visualização.
Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
Aperte a opção "Criar evento", localizada na parte superior direita.
Preencha as informações requeridas e aperte em "Enviar".

![criar](https://user-images.githubusercontent.com/86381837/133834915-7669530f-45b6-4334-83a8-7dea2ba8e67c.gif)

**3. Editar eventos**
Na barra lateral, vá em "Casos" e depois "Gestão de Casos"
Em seguida, localize o caso desejado para fazer a visualização.
Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
Clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".
Selecione o botão "Editar" ao lado do evento que deseja editar.
Após realizar as edições necessárias, aperte em "Enviar".

![Home - Gestão Legal - Google Chrome 2021-09-17 15-19-09 (1)](https://user-images.githubusercontent.com/86381837/133836121-601b7898-31bd-4679-9332-3c129bfad24f.gif)

**4. Excluir eventos**
Na barra lateral, vá em "Casos" e depois "Gestão de Casos"
Em seguida, localize o caso desejado para fazer a visualização.
Selecione o botão "Visualizar", que encontra-se na parte inferior da descrição do caso.
Clique na opção "Ver eventos", localizada ao lado do tópico "Eventos".
Selecione o botão "Excluir" ao lado do evento que deseja excluir.

![exclusão](https://user-images.githubusercontent.com/86381837/133835112-7d01f99a-bbc4-40c4-95d5-8907a8a685e9.gif)

**Comment by Ale-eloy** [comment]
Show! Valeu Bruno!
