### ISSUE TITLE
Acréscimo de especificações quanto aos caracteres para criação de senha 

### ISSUE THREAD

**Issue by elisacostab** [gestaolegalufmg/gestaolegal#151]
Gestão de usuários> Cadastrar usuário> Dados de acesso ao sistema> Senha

Com relação à criação de senha, em dados de acesso ao sistema, seria interessante colocar os critérios solicitados para a senha logo abaixo, pois apenas fica evidente a ausência de algum (ex: necessidade de caracteres especiais), quando, ao preencher tudo e tentar criar o novo usuário, recarrega a página, acusando a necessidade do caractere ou alguma outra necessidade faltante na senha. Melhoria para experiência do usuário. 

![sugestão de senha](https://user-images.githubusercontent.com/89033709/133835448-52819e5a-1aba-42dd-ba63-8654820ff188.png)

Navegador: Google Chrome
Usuário: Administrador

**Comment by RaphaGg** [comment]
Conferido em 24/01/2022.
