### ISSUE TITLE
Página de marcação de plantão não é atualizada depois de plantões anteriores

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#152]
Logado como Estagiário de Direito, em 18/09/2021, percebi que a página de plantão ainda mostrava que meu usuário estava com datas de plantão marcadas para os dias 22/05/2021 e 25/05/2021, referentes à última vez que configuramos a abertura do plantão.
Em outras palavras, o sistema não é "limpo" depois que a data do plantão passa. Exemplo do problema:

1. No mês de maio eu configurei a abertura do plantão e os usuários marcaram as datas de interesse.
2. O plantão é aberto e fechado mensalmente. No mês de junho eu irei configurar novamente a abertura do plantão. 
3. Ao tentar selecionar as datas de interesse, o colaborador irá perceber que o sistema ainda tem registrado as datas de maio, quando na verdade era para o sistema estar "limpo" para o usuário registrar novas datas em junho, referentes à nova abertura.

Apenas um detalhe: as informações do plantão de maio precisam ficar salvas, assim como as de junho, julho, etc. O sistema não pode simplesmente apagar as datas de maio para registrar as datas de junho. Em outras palavras, o sistema deve salvar as informações de cada abertura de plantão feita.

![Captura de Tela (16)](https://user-images.githubusercontent.com/55855366/133892791-49a51c96-f339-49c2-babb-8020cdef15dc.png)

Navegador: chrome.

**Comment by vicvital** [comment]
funcionalidade do plantão já está ok

- abri plantão como administrador (04/09 a 11/09, permitindo escolher data entre 05/09 - 09/09) e selecionei data de interesse como estagiário de direito
- refiz login como administrador: a configuração de plantão permanece salva
- refiz login como estagiário: a seleção das datas permanece salva

**Comment by Ale-eloy** [comment]
Ao reproduzir o passo a passo, as datas dos plantões anteriores apareceram salvas para mim. Logo, entendo como resolvido o issue.
