### ISSUE TITLE
Gabriela Treinamento

### ISSUE THREAD

**Issue by gabriela-lp** [gestaolegalufmg/gestaolegal#154]
- No campo de data de nascimento, na página de edição do usuário, não aparece o quarto dígito do ano. A data aparece completa na área de visualização do usuário.
- Campo férias confuso quanto o que deve ser preenchido (data?).
- É alegado apenas um erro de preenchimento por vez (Ex.: ao criar a senha 12345678, me foi informada da necessidade de uma letra maiúscula ao menos. Criei a senha G1234567 e me foi informada da necessidade de utilização de um caractere especial).
- No campo "dia da semana e horário de atendimento" há apenas um campo para ser preenchido com as duas informações. Porém, na área de visualização do usuário, aparecem dois campos "dia do atendimento" (que fica em branco) e "horário de início de atendimento" (no qual aparece as informações preenchidas - dia e horário)
![GL - treinamento Gabriela](https://user-images.githubusercontent.com/70505460/134009194-95b4bfd2-9d10-4d58-91c7-f5f4b23dc6a9.png)

**Comment by Ale-eloy** [comment]
Ei @gabriela-lp ! Obrigado pelo feedback. Vamos ter de transformar algumas dessas questões em issues para correção.

1. No campo de data de nascimento, na página de edição do usuário, não aparece o quarto dígito do ano. A data aparece completa na área de visualização do usuário. -> pode virar um issue
2. Campo férias confuso quanto o que deve ser preenchido (data?). -> vamos deixar como está mesmo.
3. É alegado apenas um erro de preenchimento por vez (Ex.: ao criar a senha 12345678, me foi informada da necessidade de uma letra maiúscula ao menos. Criei a senha G1234567 e me foi informada da necessidade de utilização de um caractere especial). -> olha pra mim por favor se o issue #151 relata o mesmo problema que você. Eu acredito que vocês tenham se deparado com o mesmo problema. Se não, me avise!
4. No campo "dia da semana e horário de atendimento" há apenas um campo para ser preenchido com as duas informações. Porém, na área de visualização do usuário, aparecem dois campos "dia do atendimento" (que fica em branco) e "horário de início de atendimento" (no qual aparece as informações preenchidas - dia e horário) -> realmente! Já relatei isso em outro issue e pedi para corrigirem.

Muito obrigado!

**Comment by gabriela-lp** [comment]
Ei, @Ale-eloy! Realmente o issue #151 refere-se ao mesmo problema.

**Comment by Ale-eloy** [comment]
Entendido, obrigado @gabriela-lp ! Poderia por favor transformar o "No campo de data de nascimento, na página de edição do usuário, não aparece o quarto dígito do ano. A data aparece completa na área de visualização do usuário." em um novo issue, com um print?
