### ISSUE TITLE
Não consigo excluir partes envolvidas já cadastradas em uma orientação jurídica.

### ISSUE THREAD

**Issue by Lucardoso06** [gestaolegalufmg/gestaolegal#155]
Logado como Administrador no navegador Google:
1. Após realizar o cadastro completo de uma nova orientação jurídica, associar uma pessoa a esta orientação e visualizar a orientação, não há opção para desassociá-la. Deste modo, caso a pessoa errada seja associada, ou seja necessário fazer modificações nas partes envolvidas à Orientação, o cadastro terá que ser totalmente refeito.
![image](https://user-images.githubusercontent.com/89036394/134358683-519ae169-e68e-4f80-b889-6d2454e5982e.png)
Para isso, sugiro a adição de uma opção para "excluir associado" na página acima. Quem sabe colocando um "xizinho" do lado do nome.

2. Durante o cadastro de uma nova orientação, no momento de associar uma pessoa a esta orientação, não é possível visualizar qual pessoa acabou de ser associada. 
![image](https://user-images.githubusercontent.com/89036394/134359280-ea463aee-ec79-429d-8f64-5b22ad49f54f.png)
Veja que na tela acima uma pessoa acabou de ser associada, mas não é possível saber qual e nem quantas pessoas já foram associadas. Desse modo, caso haja um clique errado na tela, uma pessoa erroneamente associada pode passar despercebida.
Para isso, sugiro reformular a associação de pessoas à Orientação Jurídica, de modo que a pessoa recém associada apareça na tela acima- de maneira parecida com a criação de um grupo no whatsapp.

**Comment by RaphaGg** [comment]
Conferido em 24/01/2022.
