### ISSUE TITLE
Dado de CNPJ dentro de cadastro de novo atendido não tem máscara de preenchimento

### ISSUE THREAD

**Issue by guisouza3** [gestaolegalufmg/gestaolegal#156]
Foi possível executar o cadastro sem erros, mas sugeriria duas questões: 

1) A fim de evitar envio de dados equivocados com a inserção de letras bem como deixar o cadastro mais prático, acredito que os campos que requerem preenchimento com números deveriam aceitar **apenas** números, na sua quantidade necessária e obedecendo um formato pré-estabelecido para a específica numeração. 

2) Sinto falta da informação que diz respeito à data do cadastro ou a última data de sua alteração. 

![image](https://user-images.githubusercontent.com/89096123/134450023-f66f2e7f-a2f2-42db-893d-b908fd5a6a75.png)

A edição seguiu sem qualquer tipo de erro.

![image](https://user-images.githubusercontent.com/89096123/134450674-b55a3644-055d-4540-af48-00e444dc3b28.png)

Em Tornar Assistido, o Campo para RG aceita caracteres em letras além de não apresentar nenhum limite.
![image](https://user-images.githubusercontent.com/89096123/134450868-205bf0b6-b474-4846-bf93-0278b4496654.png)

Não está habilitado o formato moeda nos campos que requerem informação em valores, 
![image](https://user-images.githubusercontent.com/89096123/134451011-ad4fb4f4-c175-4abc-b84f-cb2ad58d0fae.png)

Por fim, ao concluir o "Tornar Assistido", o erro veio a tona

![image](https://user-images.githubusercontent.com/89096123/134451202-506e2661-197e-4fbc-abd2-3dfd59b5f17d.png)

**Comment by Ale-eloy** [comment]
Ei @guisouza3 , você poderia por favor:

1. especificar em relação ao item (1) quais campos exatamente você acha que deveriam aceitar apenas informações em formato de números? E, além disso, qual o formato/padrão que eles deveriam aceitar?
2. detalhar melhor a que informação você se refere? Você viu isso em alguma outra parte do sistema? 
3. Detalhar melhor como fez para chegar no erro 500 descrito no final da sua mensagem? Você tentou tornar assistido um usuáro novo ou antigo? Qual?

**Comment by guisouza3** [comment]
Olá @Ale-eloy ,

1) Deveria ser mas não está somente em formato de número: 

- Campo do CNPJ
- Campo da numeração do endereço (Aqui acho válido manter a inserção de dados com números e letras, visto que existe algumas numerações residenciais que também possuem letras)

- Veja que os campos de Data de nascimento, CPF e telefone fixo só aceitam números e possuem a quantidade de caracteres limitada para inserção dos dados. Por exemplo: O formato real do CPF é composto somente por números e por 11 números. Dessa forma, o campo em questão só aceita algarismos com sua quantidade limitada a 11.

Obs: Acho interessante esse ajuste para evitar erros "bobos" com a inserção de letras onde deveria ser números e vice versa. 

![image](https://user-images.githubusercontent.com/89096123/135640940-7211f2b6-f21b-4dab-9add-d4fd46a2cff5.png)

2) Geralmente nos cadastros é colocado uma data para saber o dia em que as informações foram cadastradas e/ou a última atualização feita no cadastro. Ainda não vi essa opção em nosso sistema, mas já vi em outros programas externos ao GL e acredito que poderíamos incluir essa possibilidade em nosso projeto.  

3) Tentei novamente "Tornar assistido" e agora deu certo e não apareceu o Erro 500. Tornei assistido o usuário Guilherme Eustáquio T Souza, mas ainda não sei precisar se é um usuário antigo ou novo (se puder me ajudar a identificar um usuário novo e um usuário antigo seria ótimo).

**Comment by Ale-eloy** [comment]
Obrigado!

Resumindo, precisamos que o campo "CNPJ" dentro do cadastro de novo atendido também tenha máscara de CNPJ 00.000.000/0000-00:
![image](https://user-images.githubusercontent.com/55855366/135859595-428ac573-df6e-4ec6-bfb1-aea5621e1677.png)

**Comment by diegopabulo** [comment]
1. Nas telas "Tornar Assistido" e "Editar Assistido" os campos que se referem a valores monetários, **embora não salve quando o campo possui letra**, está permitindo a inserção da letra "e".

2. Os campos de valores monetários estão sem a máscara de moeda nas telas de "Tornar Assistido" e "Editar Assistido".

![image](https://user-images.githubusercontent.com/89043822/151151256-ad363d65-f7ab-49b0-b4e1-41ee2e2f6d6e.png)
![image](https://user-images.githubusercontent.com/89043822/151151341-fbd3fab5-2d11-481a-b680-a726cdb6084a.png)

3. Ao clicar em "Tornar Assistido", apareceu o erro 500.

![image](https://user-images.githubusercontent.com/89043822/151151934-658ccb2e-c92b-47b4-9b3f-5e8036e1287a.png)

**Comment by gabriela-lp** [comment]
Conferido em 31/01/2022

**Comment by gabriela-lp** [comment]
Conferido em 31/01/2022
