### ISSUE TITLE
Ao editar/criar os casos, horário salvo está incorreto

### ISSUE THREAD

**Issue by elisacostab** [gestaolegalufmg/gestaolegal#158]
1- Ao modicar caso já existente, o horário de modificação salvo, conforme print abaixo,  está errado.  

![erro hora](https://user-images.githubusercontent.com/89033709/135327160-d117951b-c8f9-4dfb-9dcc-7bcf6f922b1f.png)

![hora errada](https://user-images.githubusercontent.com/89033709/135328000-a09b67d2-96c3-41a7-9d9c-3acefab8c687.png)

 
2- O mesmo ocorre para o horário de criação do caso

3- Para além, seria interessante colocar a data no formato dd/mm/aaaa, para ficar mais fácil para o usuário.

**Comment by RaphaGg** [comment]
Conferido em 24/01/2022.
