### ISSUE TITLE
Consulta das Necessidades do "Minhadaj"(plantão) - Chefe da Secretaria 

### ISSUE THREAD

**Issue by AmandaFuso** [gestaolegalufmg/gestaolegal#16]

**Comment by AmandaFuso** [comment]
Consultar o Wellerson para ver se um formulário é o instrumento ideal para coletar as sugestões dele ao sistema. 
Outras opções: entrevista gravada ou relatório

**Comment by gabriellasaffioti** [comment]
Entrevista com o Wellerson sobre os requisitos de software elaborados.
