### ISSUE TITLE
Dados dos usuários do sistema estão abertos para visualização

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#160]
Ao acessar o sistema logado como qualquer usuário, os dados pessoais de todos os outros usuários ficam abertos para visualização por qualquer pessoa logada no sistema. No exemplo abaixo, um mero colaborador externo (função de mais baixo nível do sistema) consegue visualizar **dados sensíveis** de identidade, cpf e estado civil de um administrador, por exemplo.

![image](https://user-images.githubusercontent.com/55855366/135331075-c084cfb8-39b9-459e-856e-1da89b1d3c5d.png)

**_Isso é crítico porque põe em risco os dados dos usuários, o que pode gerar multas de acordo com a LGPD._** 
Minha sugestão é a seguinte: 

1. permitir que apenas os administradores consigam visualizar todos os cards.
2. todos os outros usuários poderão apenas ver os cards de "Dados Cadastrais" e "Agenda de atendimento".
3. excluir o dado "estado civil" que é coletado dos usuários.

Estamos abertos para conversar sobre essa questão.

**Comment by BrunoMoReis** [comment]
Conferido em 25/01/2022
