### ISSUE TITLE
Erro de "Assistência Judiciária não encontrada" ao tentar visualizar Assistência Judiciária após encaminhar

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#162]
Após associar uma orientação jurídica à uma assistência judiciária, o site mostra a informação no card dentro da orientação jurídica.

![image](https://user-images.githubusercontent.com/55855366/135851271-ed4583f6-ba0f-4c9c-8faa-325c37638a14.png)

Ocorre que, ao clicar no botão de visualizar, ele direciona para a página de "Assistências Judiciária" e em seguida mostra um pop-up dizendo "Assistência judiciária não encontrada", mesmo ela existindo no sistema, conforme print abaixo.

![image](https://user-images.githubusercontent.com/55855366/135851417-3d8ab996-dcb1-4d79-95d5-d7c056ff7cd1.png)

**Comment by gabriela-lp** [comment]
Conferido em 31/01/2022
