### ISSUE TITLE
Não filtro ao encaminhar orientação jurídica para assistência judiciária por meio do card

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#163]
Usuário: administrador
Navegador: chrome

Ao encaminhar uma orientação jurídica para uma assistência judiciária **durante o processo de criação** o sistema filtra as assistência disponíveis para mostrar apenas aquelas que correspondem à área do caso.

- No exemplo abaixo, criei um caso do tipo "Cível" e "Consumidor". Perceba que a assistência "teste cível" aparece para mim porque tem como áreas "Cível" e Consumidor", ao passo que a assistência "libero voluptas" não aparece, porque não tem em suas áreas a "Cível".

![image](https://user-images.githubusercontent.com/55855366/135852339-505aed8e-01fa-4b03-8275-1bfaf505f4e4.png)
![image](https://user-images.githubusercontent.com/55855366/135852428-5ee327c9-5dd0-41fc-af9d-20aeed2faf7b.png)
![image](https://user-images.githubusercontent.com/55855366/135852495-9ff3b486-d27e-41a5-a606-2dd09011fdea.png)

Com base nisso, nós inferimos que haja um filtro por área durante o processo de encaminhamento da orientação jurídica **durante sua criação**.

Entretanto, o mesmo não acontece quando estamos encaminhando uma orientação jurídica por meio do card da orientação jurídica. 

![image](https://user-images.githubusercontent.com/55855366/135852810-9a42ad7c-673f-45b1-8c34-bfe0631fd211.png)
![image](https://user-images.githubusercontent.com/55855366/135852864-d777601c-5eff-4984-a453-55ced4d6d99b.png)
![image](https://user-images.githubusercontent.com/55855366/135852904-cb9d9078-d950-433a-8c48-b5196de28bc9.png)

Conforme imagens acima, foi possível encaminhar a orientação jurídica para a assistência "libero voluptas" mesmo sabendo que ela não tinha a área "cível". Isso nos permitiu concluir que não há filtro de área dentro do card.

Precisamos que o filtro de encaminhamento também seja implementado dentro do card da orientação jurídica.

**Comment by Lucardoso06** [comment]
Issue corrigido. Conferido em 27/01/2022
