### ISSUE TITLE
Problemas no layout das páginas de encaminhamento de orientação jurídica à assistência judiciária e associar atendidos

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#164]
Identificamos vários problemas de layout e preenchimento nas etapas de encaminhamento de orientação jurídica às assistências judiciárias:

### **1. Ordem confusa**
Após criar uma orientação jurídica, a ordem das etapas de associar atendidos e encaminhar para assistência judiciária está confusa e aleatória.

Atualmente, a ordem que foi programada no sistema é a seguinte:

![antes](https://user-images.githubusercontent.com/55855366/135854740-b4363b62-5490-460d-9a51-ad75e373e3d6.png)

1. Primeiramente o usuário seleciona uma assistência judiciária para encaminhar (é a primeira coisa que aparece apesar de ser opcional)
2. Em seguida, o usuário tem que rolar para baixo na página para selecionar o atendido.
3. Depois o usuário tem que rolar a página para cima de volta para conferir se selecionou o atendido corretamente.
4. Por fim, para confirmar todo o processo o usuário tem que clicar em "Confirmar Associação" que, apesar de estar localizado do lado da assistência judiciária, confirma todo o processo de associação de atendido também.
5. A outra opção do usuário é clicar em "Sair", que volta para a página inicial do sistema.

Como se pode perceber, a ordem dos botões é completamente aleatória e provavelmente foi criada durante a etapa de desenvolvimento, mas não foi ajustada para o usuário final. **A ordem que mais faz sentido é a seguinte**:

![depois](https://user-images.githubusercontent.com/55855366/135855886-49488bd1-4638-4877-94b8-06baf6d0057d.png)

1. A primeira função que deve aparecer para o usuário é a seleção de atendidos. Ela é obrigatória e se não feita o sistema dá erro. 
2. Em seguida, deve aparecer a caixa que confirma os atendidos selecionados.
3. Depois, deve aparecer a opção de encaminhar para assistências judiciárias, que é opcional.
4. Por fim, os botãos de "Confirmar Associação" e "Sair" devem estar no fim da página, porque o primeiro confirma todo o processo de seleção, ao passo que o segundo sai definitivamente da página.

### **2. Forma de associar atendidos**

Atualmente, só é possível selecionar um atendido apenas durante o processo de criação da orientação jurídica.

![image](https://user-images.githubusercontent.com/55855366/135856624-fadc6dfc-deff-4739-9657-cd72d55832e1.png)

Seria interessante poder transformar a página em algo parecido com o que ocorre com a página de criação de assitência judiciária, em que posso selecionar várias áreas do direito para uma mesma assistência judiciária.

![image](https://user-images.githubusercontent.com/55855366/135856806-1ef9c13d-f4b8-45e2-b647-3ac5a9a1cef3.png)

### **3. Botão de sair**

Atualmente o botão de "sair" leva o usuário para a página inicial do sistema, quando na verdade **deveria voltar o usuário para a página da orientação jurídica criada**.
![image](https://user-images.githubusercontent.com/55855366/135857163-3caf8010-7f55-40c2-a2d8-ec59b78239d4.png)
![image](https://user-images.githubusercontent.com/55855366/135857193-216d6d08-9e7a-4888-bd04-272c385c4df4.png)

**Comment by Lucardoso06** [comment]
Problema 1 foi resolvido totalmente.

Problema 2 foi parcialmente resolvido. Agora, é possível associar mais de um atendido no momento de criação de uma orientação jurídica. Contudo, é necessário que se faça um por vez: o nome dos vários associados não aparecem juntos no momento da criação, como foi requisitado.

Problema 3 não foi resolvido.

**Comment by Ale-eloy** [comment]
@Ale-eloy  Separar cada os problemas 2 e 3 em novos issues diferentes; fechar o issue em relação ao problema 1.

**Comment by Ale-eloy** [comment]
Bifurcado nos issues #177 #178 para melhor visualização.
