### ISSUE TITLE
Data de nascimento incompleta na edição do usuário

### ISSUE THREAD

**Issue by gabriela-lp** [gestaolegalufmg/gestaolegal#165]
No campo de edição, o ano de nascimento aparece incompleto. Ao visualizar os dados, o mesmo erro não ocorre.
![image](https://user-images.githubusercontent.com/70505460/136211901-39b9de4b-b271-4554-a750-97044b42708e.png)
![image](https://user-images.githubusercontent.com/70505460/136212016-78fd058b-bfad-4f3a-abd0-3dddeff77892.png)

**Comment by RaphaGg** [comment]
Conferido em 24/01/2022.
