### ISSUE TITLE
Erro ao entrar em "Assistências Jurídicas"

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#166]
**Erro 500 para entrar em "Plantão" na parte "Assistências Jurídicas"**

![Home - Gestão Legal - Google Chrome 2021-10-23 22-47-59 (online-video-cutter com)](https://user-images.githubusercontent.com/86381837/138576926-ab622fd2-4264-4e8e-99f7-f06736ad58e7.gif)

**Comment by gabriela-lp** [comment]
Conferido em 31/01/2022
