### ISSUE TITLE
Busca de CEP no cadastro / edição do atendido / assistido

### ISSUE THREAD

**Issue by rvnovaes** [gestaolegalufmg/gestaolegal#168]
Ao se realizar o cadastro do atendido:
Mover o campo de CEP para a primeira posição dentro do título endereço.
Ao preencher o campo de CEP, consultar webservice online e preencher automaticamente os campos que podem ser preenchidos, isto é, logradouro, bairro, cidade, UF.  Exemplo: https://viacep.com.br/
Ficariam faltando apenas os campos número e complemento que, como não são definidos pelo CEP, ficam a cargo do usuário.
Efetuar a melhoria tanto na tela de cadastro (inicial) quando na de edição.

**Comment by RaphaGg** [comment]
Além disso, seria oportuno que o campo de estados fosse dropbox, a fim de facilitar a experiência do usuário.

**Comment by GabriJunq** [comment]
Validado implementação na plataforma de teste com a senha de administrador. 

![Issue168](https://github.com/gestaolegalufmg/gestaolegal/assets/148815517/5b56decd-8184-4cba-9d8b-1348ea952ae5)
