### ISSUE TITLE
Erro 500 - Cadastro de eventos de casos | Limite de caracteres

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#170]
Ao tentar cadastrar um evento em um caso, o site dá erro 500 quando a descrição do evento tem muitos caracteres.
Deverá ser alterado para permitir descrição com textos longos.

![image](https://user-images.githubusercontent.com/55855366/157239084-71f3a7c6-861d-4f20-83c7-44579d6f42ea.png)

**Comment by OsvaldoUFMG** [comment]
Não há mais a existência do erro relatado. 
Primeiramente, realizei o teste com a criação de um evento com poucos caracteres.  
![GL1](https://user-images.githubusercontent.com/100303278/187994776-6326dd69-e081-487d-9e71-4d37941630a5.png)
Foi salvo.
Depois, realizei o teste com a criação de um evento com muitos caracteres.
![GL 2 ](https://user-images.githubusercontent.com/100303278/187994915-e1614951-4283-4a2b-91d6-44623afa081c.png)
Também foi salvo.
![Screenshot 2022-09-01 160857](https://user-images.githubusercontent.com/100303278/187994987-6ad358e7-99e9-4385-8210-aed8b7d75a16.png)
Após a testagem, excluí os dois eventos de teste.
O erro não persiste
