### ISSUE TITLE
Erro 500 - Associar Processo

### ISSUE THREAD

**Issue by RaphaGg** [gestaolegalufmg/gestaolegal#171]
Estava realizando a migração do caso 3042 (MinhaDAJ) para o Gestão Legal (caso 44), quando ocorreu o erro 500, no momento de associar o processo. Após migrar o cliente, realizar o cadastro do caso e de todos os eventos, fui finalizar o procedimento realizando o cadastro dos processos, porém, o sistema do GL não permite que eu realize essa operação. Encaminho, em anexo, os prints do erro (vale destacar que no processo do Minha DAJ não se encontra: probabilidade de ganho; posição do assistido; data da distribuição; data do trânsito em julgado. Por isso, preenchi a "data da distribuição" como a data de criação do processo no MinhaDAJ e os outros campos como formalidade).

Tentativa de associar processo:
![Captura de tela 2022-03-08 212930](https://user-images.githubusercontent.com/89051386/157349268-bbdd2759-6a87-4a31-b4e9-f1f4da1cac37.png)

Erro encontrado:
![Captura de tela 2022-03-08 213008](https://user-images.githubusercontent.com/89051386/157349339-6850215b-063d-4800-ad01-79fb9335532d.png)

**Comment by pedrohf03** [comment]
Acabei de realizar o teste do 171 e consegui registrar o caso, apesar do assistido que eu criei não ter aparecido para ser adicionado ao caso criado.

**Comment by Ale-eloy** [comment]
Não consegui reproduzir o erro 404.

**Comment by pedrohf03** [comment]
Problema resolvido.
