### ISSUE TITLE
Erro 500 ao tentar associar processo

### ISSUE THREAD

**Issue by elisacostab** [gestaolegalufmg/gestaolegal#172]
Não consegui  associar processo ao caso 51, pois ao salvar dava erro 500

![associar processo](https://user-images.githubusercontent.com/89033709/157711837-3362a957-8e37-4016-b247-2116ff912f7f.png)

![erro500](https://user-images.githubusercontent.com/89033709/157711880-b5966c58-f5a5-4892-8980-42d67144c4ae.png)

**Comment by elisacostab** [comment]
Tive o mesmo erro ao tentar associar processo ao caso 52

![image](https://user-images.githubusercontent.com/89033709/157734098-b7b69778-a027-4d53-946e-6683656f0da7.png)

**Comment by Ale-eloy** [comment]
Issue duplicado no issue #171 e, por isso, fechado.
