### ISSUE TITLE
Designar Orientador / Estagiário / Colaborador ao Cadastrar Caso

### ISSUE THREAD

**Issue by ryanemmanuel** [gestaolegalufmg/gestaolegal#174]
Ao cadastrar um caso, o sistema não grava o orientador, estagiário e colaborador externo vinculados. Depois de salvar o caso, temos que clicar em editar para então reassociar e o sistema gravar essas informações.

**Comment by LuisGGJardim** [comment]
Na aba "orientador responsável" e "estagiário de direito responsável" ainda não consta nada após criação de novo caso, não há aba de "colaborador externo", que também não aparece (observar caso 6 na primeira captura de tela anexada). Após clicar em editar, os dados desaparecem, e é preciso adicionar os dados novamente. Após tal procedimento, passam a constar no caso as informações. (observar caso 6 na segunda captura de tela anexada)
![Captura de Tela (14)](https://user-images.githubusercontent.com/108702499/188330476-7773264c-6187-400b-bf44-380d03808681.png)
![Captura de Tela (15)](https://user-images.githubusercontent.com/108702499/188330480-cc1750e8-f1e9-46b2-87c7-8f5f039bebc4.png)
