### ISSUE TITLE
Botão sair ao associar atendidos

### ISSUE THREAD

**Issue by Lucardoso06** [gestaolegalufmg/gestaolegal#178]
Atualmente o botão de "sair" leva o usuário para a página inicial do sistema, quando na verdade deveria voltar o usuário para a página da orientação jurídica criada
![image](https://user-images.githubusercontent.com/55855366/135857163-3caf8010-7f55-40c2-a2d8-ec59b78239d4.png)
![image](https://user-images.githubusercontent.com/55855366/135857193-216d6d08-9e7a-4888-bd04-272c385c4df4.png)

**Comment by Ale-eloy** [comment]
Não resolvido. A página continua igual:
![image](https://user-images.githubusercontent.com/55855366/190275435-0073f86e-e2a2-4ec1-986e-7b6b98db0b76.png)

Conforme explicado no título, o layout da página está mal feito. O botão "Sair" deve se chamar "Concluir" e ele deve redirecionar para a página "Orientações Jurídicas", e não para a página principal.

**Comment by Ale-eloy** [comment]
O sistema atualmente foi ajustado para levar para a página de Assistências Jurídicas, o que ao meu ver é um comportamento ok.
