### ISSUE TITLE
Não há mais botão para deferir ou indeferir casos

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#181]
A opção de deferir ou indeferir casos sumiu do sistema. Antes ela ficava tanto no card do caso quanto dentro da edição do caso. Alterar para voltar a aparecer a funcionalidade.

(i) Imagem dos cards sem opção de deferir/indeferir.
![image](https://user-images.githubusercontent.com/55855366/160383088-c9c73f8c-78de-491e-81d8-1c2226ede54b.png)

(ii) Imagem da edição sem opção de deferir/indeferir.
![image](https://user-images.githubusercontent.com/55855366/160383134-f3d94b15-cbc3-4803-afbd-d5d4b706c45e.png)

**Comment by stephaniegsantos** [comment]
A opção de deferimento ou indeferimento dos casos ainda não aparece no sistema. 
(i) Imagem de cards sem a opção de deferir/indeferir 

![2022-09-03](https://user-images.githubusercontent.com/108653963/188290043-095bfd5d-f920-4f04-babd-6f080338f51d.png)

(ii) Imagem da edição sem a opção de deferir/indeferir

![2022-09-03 (1)](https://user-images.githubusercontent.com/108653963/188290056-0e60a972-5786-40fe-95a9-2fe9f6a34584.png)

**Comment by Ale-eloy** [comment]
Ainda sem correção. Acredito que seja um problema de permissionamento. Testei com um usuário do tipo Professor e a opção não apareceu. Ao corrigir, levar em conta issue #179

**Comment by stephaniegsantos** [comment]
Testei com um usuário de administrator e a opção de deferir ou indeferir o caso ainda não apareceu.

**Comment by Ale-eloy** [comment]
Issue muito grande. Vou recriar outro explicando o ponto principal aqui #203
