### ISSUE TITLE
Campo de arquivo deve se chamar Questionário Socioeconômico

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#182]
Na página do caso, há um card chamado "Arquivos anexados". Porém, ele deve ser chamado "Questionário Socioecônomico". O nome atual está causando confusão nos usuários do sistema com outras funcionalidades (Eventos).

![image](https://user-images.githubusercontent.com/55855366/160385443-af519c23-ab09-4f3e-8edd-4ef1b854ff10.png)

**Comment by patrickads0** [comment]
Issue ainda não corrigida na versão de testes. Low priority. Funcionalidades parecidas.

usuário: Admin 
navegador: Chrome

**Comment by Math-carvalho** [comment]
Issue corrigido por Roberto durante a aula.
