### ISSUE TITLE
Modificar o campo "quantidade de pessoas que moram na mesma casa" no GL

### ISSUE THREAD

**Issue by RaphaGg** [gestaolegalufmg/gestaolegal#187]
No formulário socioeconômico antigo, o número de pessoas que moram com o assistido está delimitado por uma faixa média de pessoas, já no GL, é necessário colocar um número exato. Deve-se colocar o número menor da faixa.

Formulário socioeconômico:
![Captura de tela 2022-04-25 201700](https://user-images.githubusercontent.com/89051386/165189708-94c67896-3d18-455f-9b77-02bc652f7360.png)

GL:
![Captura de tela 2022-04-25 201744](https://user-images.githubusercontent.com/89051386/165189791-2594b070-309f-48e7-b140-ad36f7caa136.png)

**Comment by RaphaGg** [comment]
Além disso, vale ressaltar que a mesma situação ocorre para os campos de "salário", "valor da renda familiar" e "qual o ano do veículo". No formulário socioeconômico, todos esses três campos são informados em torno de uma faixa de média, mas no GL é obrigatório fornecer um valor exato, conforme prints abaixo. Acredito que as mesmas providências sejam devidas para esses casos também.



Salário:

![aaa](https://user-images.githubusercontent.com/89051386/165191990-93196627-e699-4940-a68c-941596037cda.png)

![abbb](https://user-images.githubusercontent.com/89051386/165192009-44115cd8-02c7-4c49-b613-ea93de290c31.png)



Valor da renda familiar:

![accc](https://user-images.githubusercontent.com/89051386/165192157-be6dd0d5-d20a-4532-8585-8c633fec59dc.png)

![adddd](https://user-images.githubusercontent.com/89051386/165192171-210f989a-9363-444e-824f-786e3df7e539.png)



Qual o ano do veículo:

![aeeeee](https://user-images.githubusercontent.com/89051386/165192305-03de9905-d458-40a2-b6d2-91b378b71035.png)

![afffff](https://user-images.githubusercontent.com/89051386/165192315-536898c8-b9e5-4a1e-a25d-49e139e3e8c5.png)

**Comment by Ale-eloy** [comment]
Acredito que esse problema se limita ao legado que usava o questionario socioeconomico antigo, nos quais temos que recadastrar dados do legado no software. Nos novos casos - que são a prioridade do software -, iremos cadastrar o valor exato, o que é melhor para fins de qualidade de dados e precisão.
