### ISSUE TITLE
Cadastro de usuários - aceita inconsistência na data de nascimento, e somente texto em campos numéricos/número em campos de texto 

### ISSUE THREAD

**Issue by vicvital** [gestaolegalufmg/gestaolegal#198]
Conferindo o issue #134 , encontrei outras inconsistências no cadastro de usuários:

1. Data de nascimento aceita data futura
![image](https://user-images.githubusercontent.com/108194685/188483261-697f3ddc-0a89-4783-a0fd-ee98778205ac.png)

2. É possível passar apenas caracteres nos campos RG e OAB
![image](https://user-images.githubusercontent.com/108194685/188483339-44f86074-6a73-40bd-b855-bc3c3bca75f9.png)

3. Campo "endereço": é possível passar apenas caracteres para "número" "CEP" etc, e apenas dígitos para "cidade" etc.
![image](https://user-images.githubusercontent.com/108194685/188482997-7079764d-d94b-4fe4-b72b-9485adddbf0b.png)

**Comment by Ale-eloy** [comment]
Ao meu ver, os pontos sugeridos podem ser despriorizados por enquanto. Irei fechar o issue.
