### ISSUE TITLE
Detalhamento do Fluxo de Cadastramento do Assistido

### ISSUE THREAD

**Issue by rvnovaes** [gestaolegalufmg/gestaolegal#2]
Separar do fluxo inicial e fazer fluxo apartado no Bizagi do cadastramento do assistido.

- [x] Fluxo de cadastramento do assistido pelo Estagiário da Secretaria vinculado à DAJ
- [x] Fluxo de atendimento do Estagiário do direito vinculado à DAJ

**Comment by ailtonadvti** [comment]
![image](https://user-images.githubusercontent.com/55855407/65931572-a0b66c00-e3e0-11e9-8110-99680ac6822f.png)

**Comment by ailtonadvti** [comment]
![Cadastramento pelo DAJ](https://user-images.githubusercontent.com/55855407/65931752-613c4f80-e3e1-11e9-8e48-2cb151090b7f.png)
