### ISSUE TITLE
Cadastro de usuários: Agenda de atendimento com campos incongruentes

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#206]
A incongruência continua existindo.

1. Durante o cadastro, o sistema exige a informação de "dia da semana e horário de atendimento":

![image](https://user-images.githubusercontent.com/55855366/152336612-060a9a8a-6c63-42ab-ab05-4b1902dc3582.png)

2. Porém, após cadastrado, o card mostra o dia da semana separado horário de atendimento:

![image](https://user-images.githubusercontent.com/55855366/152336768-02637e33-142a-4398-aabf-bfa2911c9067.png)

Sugestão: a solução mais prática seria mudar o card de exibição para aglutinar dia da semana e horário de atendimento em um campo apenas, ou seja, excluir o campo"Dia de atendimento" que aparece no card de visualização. Obs.: eu sugiro antes conferir se não existe no Banco de Dados um campo específico pro dia do atendimento, porque se tiver, podemos excluir.

_Originally posted by @Ale-eloy in https://github.com/gestaolegalufmg/gestaolegal/issues/70#issuecomment-1028910445_

**Comment by marcelomrad** [comment]
Esta issue também está no Pull Request
