### ISSUE TITLE
413 Request Entity Too Large - Upload de arquivo maior que 10MB

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#207]
_O problema abaixo já havia sido relatado no issue #44, mas não foi resolvido. Recadastrei como novo issue para facilitar a organização._

Ao tentar upar um arquivo muito grande, na página de `criar/editar casos`, sou levado para esse `Request Entity Too Large`.
O sistema não faz controle no frontend do tamanho do arquivo. O erro aparece somente depois de clicar em cadastrar, ou seja, o sistema tenta subir todo o arquivo para somente depois dar o erro.

![image](https://user-images.githubusercontent.com/55855366/198840378-ea58a0f2-a6da-4ec7-8c64-a5e8561eff20.png)

**Comment by marcelomrad** [comment]
O pull request com a resolução dessa e de outras issues já está aberto desde 25 de Agosto. É necessária a aprovação dele para que a resolução entre no sistema.
