### ISSUE TITLE
Em "editar casos", o Orientador não consegue editar os arquivos anexados

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#210]
Em _gestão de casos_, Ao clicar em _editar caso_, o **ORIENTADOR** consegue upar, excluir e visualizar, porém **não consegue editar os arquivos pdf anexados em cada caso**

![ORIENTADOR](https://user-images.githubusercontent.com/86381837/198843712-4ed42969-1aab-479a-9f8c-225425fd478a.png)

**Comment by Ale-eloy** [comment]
Acho que a funcionalidade está OK como está. O arquivo do caso será o questionário socioeconomico do assistido. O questionário não deverá ser modificado posteriormente a não ser por razões excepcionais. Caso seja modificado, o controle atual de visualizar e excluir já é suficiente para a tarefa.
