### ISSUE TITLE
Em "editar casos", o Estagiário de direito não consegue editar os arquivos anexados

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#211]
Em _gestão de casos_, Ao clicar em _editar caso_, o **ESTAGIÁRIO DE DIREITO** consegue visualizar, porém **é impossibilitado de upar qualquer arquivo no caso**

_Para que o estagiário consiga upar, ele precisa ter permissão para editar o caso._

https://user-images.githubusercontent.com/86381837/198844467-c4caff3e-8fb2-4531-9458-18c445698f28.mp4

**Comment by Ale-eloy** [comment]
A funcionalidade está certa. O estagiário não deve conseguir upar arquivos diretamente na página do caso, já que aquele upload foi pensado apenas para o questionário socioeconomico inicial. Para upar arquivos ou anotar novidades, o estagiário deverá cadastrar eventos ou lembretes.
