### ISSUE TITLE
Em "editar casos", o Colaborador externo não consegue upar os arquivos anexados

### ISSUE THREAD

**Issue by BrunoMoReis** [gestaolegalufmg/gestaolegal#212]
Ao clicar em _editar caso_, no caso do **COLABORADOR EXTERNO**, acontece _Erro500_ (internal server error) ou impossibilidade de acesso.
Colaborador Externo: **não consegue upar, quando deveria**
_Para conseguir upar, precisa permitir "editar caso_

https://user-images.githubusercontent.com/86381837/198845234-ac47cc65-c06d-41f9-8ac8-934fc4be5733.mp4

**Comment by Ale-eloy** [comment]
A funcionalidade está certa. O colaborador externo não deve ter permissão de editar o caso, ainda que seja para fins de subir arquivos.
