### ISSUE TITLE
Lista de usuário deve ser exibida em ordem alfabética

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#232]
A lista de usuário hoje é exibida na ordem de criação dos usuários (/usuario/listar_usuarios). Queremos que ela seja exibida em ordem alfabética.

![image](https://github.com/gestaolegalufmg/gestaolegal/assets/55855366/b029e970-fe26-4791-8812-f8d2e96018c5)

**Comment by GabriJunq** [comment]
Validado implementação na plataforma de teste com a senha de administrador. 

![Issue232](https://github.com/gestaolegalufmg/gestaolegal/assets/148815517/1cb8e684-316c-4220-956e-af8e3d036c78)
