### ISSUE TITLE
Acrescentar data e horário da orientação e usuário responsável

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#236]
Na página de visualização da orientação jurídica, precisamos que sejam acrescentados 2 novas informações no início do card:
- Data e horário da orientação: puxado direto do BD do momento de criação da orientação
- Usuário responsável: puxado direto do BD do usuário que tiver criado a orientação. **PS.: o sistema já está em produção. Se isso não puder ser puxado para as orientações legadas, será preciso uma exceção que mostre algo como "-" ou "n/a"** 

PS.: já aproveitem e consertem o typo em **_Jurídica_**.

![image](https://github.com/gestaolegalufmg/gestaolegal/assets/55855366/07b98d65-6e0c-4001-8b87-1ac2d77dc291)

**Comment by GabriJunq** [comment]
Validado implementação na plataforma de teste com a senha de administrador.

Um ponto observado foi o horário registrado, o teste foi realizado as 15:06 e hora apresentada foi 18:06. Necessário verificar se o erro esta no código ou no hora configurado no servidor. 

Quanto a solicitação de concertar o typo "jurídica" esta não foi implementada. As demais solicitações estão conforme a demanda. 

![Issue236](https://github.com/gestaolegalufmg/gestaolegal/assets/148815517/416392ac-cff3-4f97-97b8-8dcb3a6faac5)

**Comment by Ale-eloy** [comment]
Pontos corrigidos.
