### ISSUE TITLE
Data dos atendimentos não aparece em nenhum lugar.

### ISSUE THREAD

**Issue by ryanemmanuel** [gestaolegalufmg/gestaolegal#243]
**O teste foi realizado estando logado com todos as categorias de usuário.**

Ao buscar as orientações realizadas aos atendidos, percebemos que não há informação sobre a data e horário do atendimento.

Cliquei, na página inicial, em "Plantão" e em "Orientações Jurídicas".

![image](https://github.com/gestaolegalufmg/gestaolegal/assets/4334173/e8443aba-34c5-4560-9875-04621e66d421)

Na listagem, não há o campo data do atendimento. Seria importante para, em caso de múltiplos atendimentos, escolhermos o correto.

Vejamos, como exemplo, o atendido Axxx . Ao realizar a busca, não temos informação sobre a data do atendimento. O mesmo ocorre quando abrimos cada um deles.

![image](https://github.com/gestaolegalufmg/gestaolegal/assets/4334173/9d913f9b-60ac-4517-8990-6ae4cbb528fa)

![270191727-7cd8d6ae-ca82-4516-85b3-338ea1fe2556](https://github.com/gestaolegalufmg/gestaolegal/assets/4334173/ce423c37-1c07-4916-b6b7-6c0b2fd7d32b)

*Dados cobertos em atenção à LGPD e ao sigilo profissional.*

**Comment by Ale-eloy** [comment]
Desde a ultima atualização a orientação jurídica agora tem marcação de data e horário.
