### ISSUE TITLE
Elaboração dos requisitos do software (Anexo do Edital de Programador) 

### ISSUE THREAD

**Issue by AmandaFuso** [gestaolegalufmg/gestaolegal#29]

**Comment by ailtongomess** [comment]
![tela presença](https://user-images.githubusercontent.com/55855407/68828181-89c39480-0683-11ea-9e29-4141c43f0955.png)
A ideia: deve ser registrada a presença nos plantões (horário de chegada e saída) dos ES, ED e orientadores. 
1 papel/raia: Quem faz é o ES
Questões pendentes:
Será feito o registro de presença dos estagiários da clínica e de Psicologia? 
Possibilidade do próprio estagiário registrar sua presença, fazendo o login e o ES só certificar

**Comment by Alex19-tech** [comment]
A ideia: os assistidos serão notificados via e-mail ou SMS acerca de prazos, reuniões e providencias a serem tomadas. 
1 papel/raia: quem faz é o estagiário da secretaria
Questões pendentes: 
O estagiário do plantão seria melhor como ator desse procedimento?
Notificações somente para assistidos ou outros atores também?

![Bizagi Email SMS](https://user-images.githubusercontent.com/55855366/70404434-d1d29e80-1a18-11ea-8234-850ec117d3e5.PNG)
![assistid](https://user-images.githubusercontent.com/55855366/70404528-21b16580-1a19-11ea-8faa-fab7de79a93f.png)

**Comment by gabriellasaffioti** [comment]
![Busca por CPF](https://user-images.githubusercontent.com/55855370/70488859-c2b32580-1ad8-11ea-868a-0876ca9a622b.jpeg)

Descrição:

1 - O Estagiário da Secretaria antes de começar a Triagem do Atendido verifica no sistema através do CPF se aquela pessoa já esteve presente antes alguma vez no Plantão.

2 - Se a pessoa já é registrada no sistema não é necessário realizar novo cadastro das informações básicas que já foram preenchidas na 1ª vez. O Estagiário da Secretaria apenas descreve de maneira simples o motivo desta nova visita.

**Comment by gabriellasaffioti** [comment]
![Cadastrar atendido](https://user-images.githubusercontent.com/55855370/70488945-fc842c00-1ad8-11ea-8a48-768ec14cf444.jpeg)
![Cadastro atendido](https://user-images.githubusercontent.com/55855370/70488955-086fee00-1ad9-11ea-8411-9387e2ce7dd0.jpeg)

Descrição:

1 - Se o Atendido não possui cadastro no sistema, ou seja, nunca veio ao Plantão de atendimento, o Estagiário da Secretaria anota as informações básicas.

**Comment by gabriellasaffioti** [comment]
![Orientação jurídica ou Anotação do caso](https://user-images.githubusercontent.com/55855370/70489067-613f8680-1ad9-11ea-8a8d-558f7f3d3c5a.jpeg)

Descrição:

1- Orientação Jurídica - Se a DAJ não for atuar no caso, apenas para registro simples daquele atendimento.

2- Cadastrar Caso - Se a DAJ for atuar juridicamente no caso.

**Comment by gabriellasaffioti** [comment]
![cadastro orientação jurídica](https://user-images.githubusercontent.com/55855370/70489131-8f24cb00-1ad9-11ea-9cff-33860eb2cf02.jpeg)

Descrição:

1 - Se for uma situação de apenas orientação jurídica o Estagiário de Direito irá complementar a o cadastro do Atendido que o Estagiário da Secretaria já havia realizado no plantão.

2 - Não será necessário informações detalhadas, essa descrição é apenas o registro interno do Plantão da DAJ.

**Comment by gabriellasaffioti** [comment]
![Cadastro do caso](https://user-images.githubusercontent.com/55855370/70489240-ea56bd80-1ad9-11ea-941e-2e7ec054c561.jpeg)

Descrição:

1 - Se for um caso no qual a DAJ pode atuar juridicamente o Estagiário de Direito irá cadastrar as informações pertinentes de maneira detalhada com a possibilidade do Roteiro de Anotação.

**Comment by gabriellasaffioti** [comment]
![encaminhamento para outras AJ'S](https://user-images.githubusercontent.com/55855370/70489366-589b8000-1ada-11ea-85f4-489a174c6f0e.jpeg)

Descrição:

1 - Caso a DAJ não possa atuar juridicamente no caso do Atendido, há a possibilidade de encaminhar para outra assistência judiciárias de outras Faculdades.

2 - O Estagiário de Direito escolherá a área jurídica do caso.

3 - O sistema irá disponibilizar as Assistências Jurídicas que têm disponibilidade para receber o caso e que atuam naquela área.

4 - Seria desejável que a lista de Assistências Judiciárias disponíveis aparecesse na ordem de local mais próximo à moradia do Atendido.

5 - A ideia é que mensalmente os Estagiários da Secretaria atualizem o sistema de acordo com o status de cadastramento de casos das outras Assistências Judiciárias.

**Comment by gabriellasaffioti** [comment]
![Tela registro de presença](https://user-images.githubusercontent.com/55855370/70489642-20e10800-1adb-11ea-8109-ad824c3649f5.jpeg)

Descrição:

1 - Ao chegar no Plantão de Atendimento o Estagiário de Direito deverá entrar no sistema e registrar o horário de sua chegada.

2 - Da mesma maneira devem proceder o Estagiário da Secretaria e o Orientador que estiver escalado para aquele dia de Plantão.

3 - Ao final do Plantão, os atendentes (estagiários de direito e de secretaria e orientadores) devem registrar no sistema seu horário de saída.

4 - Ao final do Plantão, o Estagiário da Secretaria deverá confirmar no sistema se os horários de chegada e saída declarados pelo Estagiário de Direito e Orientador correspondem à realidade.

**Comment by gabriellasaffioti** [comment]
![Escala do plantão](https://user-images.githubusercontent.com/55855370/70489893-ae245c80-1adb-11ea-9096-fc7f0b46afb3.jpeg)

Descrição:

1 - Toda última semana do mês o sistema enviará um e-mail para os Estagiários de Direito e Orientadores escolherem seus dias de Plantão.

2 - O sistema abrirá um calendário para cada usuário escolher o dia.

3 - Orientadores deverão participar de 1 dia de Plantão no mês não podendo haver mais de 2 escalados por dia.

4 - Estagiários de Direito deverão participar de no mínimo 2 Plantões no mês, não podendo haver menos de 3 ou mais que 6 escalados por dia.

5 - Para os Estagiários de Direito é desejável que o sistema permita, inicialmente, o registro de 3 por dia. Quando houver, no mínimo, 3 Estagiários de Direito escalados em cada dia do plantão, o sistema permitirá que outros escolham esses dias que já tenham 3 pessoas escaladas.

**Comment by gabriellasaffioti** [comment]
![Relatórios](https://user-images.githubusercontent.com/55855370/70493750-82a76f00-1ae7-11ea-8c99-100c9cc4406b.PNG)

**Comment by gabriellasaffioti** [comment]
![Sugestão de Roteiro](https://user-images.githubusercontent.com/55855370/70493791-a5d21e80-1ae7-11ea-9e5d-443068cc8e3a.PNG)

**Comment by gabriellasaffioti** [comment]
Cadastro do Caso com Roteiro
![Cadastro do Caso com Roteiro](https://user-images.githubusercontent.com/55855370/70493834-d31ecc80-1ae7-11ea-83f0-b6be75d2cf96.PNG)

**Comment by gabriellasaffioti** [comment]
Cadastro do Caso sem Roteiro

![Cadastro do Caso sem Roteiro](https://user-images.githubusercontent.com/55855370/70493957-4a546080-1ae8-11ea-9b06-522c689d1170.PNG)

**Comment by gabriellasaffioti** [comment]
Fluxo Registro de presenças Plantão
![Fluxo do Registro de Presenças](https://user-images.githubusercontent.com/55855370/70494074-b1721500-1ae8-11ea-81e8-ff98a9234e09.jpeg)

**Comment by gabriellasaffioti** [comment]
![Tela de editar permissões de usuário](https://user-images.githubusercontent.com/55855370/72103511-2020d900-3308-11ea-883d-fe2237ecc114.png)

**Comment by gabriellasaffioti** [comment]
![Tela de Cadastro de usuário](https://user-images.githubusercontent.com/55855370/72103537-29aa4100-3308-11ea-9fab-a87cbf4ca52f.png)

**Comment by gabriellasaffioti** [comment]
![Consulta de atendido (a)](https://user-images.githubusercontent.com/55855370/73027656-a06c3180-3e12-11ea-9072-9c3a60dc58f7.png)

**Comment by gabriellasaffioti** [comment]
![Encaminhamento para outras assistências judiciárias](https://user-images.githubusercontent.com/55855370/73027741-c09bf080-3e12-11ea-819f-4aad431f4eb2.png)

**Comment by gabriellasaffioti** [comment]
![Tela de Login](https://user-images.githubusercontent.com/55855370/73139437-b9602700-404c-11ea-9d22-7e6f3e5c21da.PNG)

**Comment by gabriellasaffioti** [comment]
![tela de início](https://user-images.githubusercontent.com/55855370/73139985-8751c380-4052-11ea-8daa-6ed038374393.PNG)

**Comment by gabriellasaffioti** [comment]
![Atendidos e Assistidos](https://user-images.githubusercontent.com/55855370/73140253-a9991080-4055-11ea-97bb-a4fe0a21d6f2.PNG)

**Comment by gabriellasaffioti** [comment]
![Adicionar pessoa](https://user-images.githubusercontent.com/55855370/73305132-44315500-41f8-11ea-8c60-796c680e4adb.png)

**Comment by gabriellasaffioti** [comment]
![Busca por pessoas](https://user-images.githubusercontent.com/55855370/73305283-8ce90e00-41f8-11ea-849e-9e19de857f00.png)

**Comment by gabriellasaffioti** [comment]
![Exibição de casos](https://user-images.githubusercontent.com/55855370/73308824-dab54480-41ff-11ea-8937-a584946820ad.png)

**Comment by gabriellasaffioti** [comment]
![Meus casospng](https://user-images.githubusercontent.com/55855370/73309890-eb66ba00-4201-11ea-8313-aa211f2eb49f.png)

**Comment by gabriellasaffioti** [comment]
![Meus casospng](https://user-images.githubusercontent.com/55855370/73310193-88295780-4202-11ea-8576-f6cdbf47950d.png)

**Comment by gabriellasaffioti** [comment]
![caso aguardando deferimento](https://user-images.githubusercontent.com/55855370/73311143-8cef0b00-4204-11ea-9333-6229bfe90190.PNG)

**Comment by gabriellasaffioti** [comment]
![E 1](https://user-images.githubusercontent.com/55855370/73312359-418a2c00-4207-11ea-806b-853195a3fe41.png)
![E 2](https://user-images.githubusercontent.com/55855370/73312360-418a2c00-4207-11ea-8381-3242ba9a2fad.png)
![E 3](https://user-images.githubusercontent.com/55855370/73312361-4222c280-4207-11ea-86a4-54b4d7dc5c54.png)

**Comment by gabriellasaffioti** [comment]
![Ações](https://user-images.githubusercontent.com/55855370/73312910-98dccc00-4208-11ea-8691-cf7fa1a6dcc0.png)

**Comment by gabriellasaffioti** [comment]
![tela de início](https://user-images.githubusercontent.com/55855370/73315407-ca589600-420e-11ea-9426-c936a8e86fa9.png)

**Comment by Alex19-tech** [comment]
![JURIS](https://user-images.githubusercontent.com/55855366/73898545-8269ec80-4868-11ea-9d9f-5674408f6d23.PNG)

**Comment by Alex19-tech** [comment]
![caso2](https://user-images.githubusercontent.com/55855366/73899269-e55c8300-486a-11ea-86e3-441cfe47b714.PNG)

**Comment by gabriellasaffioti** [comment]
![tela de início](https://user-images.githubusercontent.com/55855370/74002571-48731600-494e-11ea-9b44-ab3b8a32af37.PNG)

**Comment by gabriellasaffioti** [comment]
![tela de início](https://user-images.githubusercontent.com/55855370/74002899-6725dc80-494f-11ea-8f1b-1bd2002ebfef.PNG)
