### ISSUE TITLE
Redação do Glossário do Plantão de Atendimento

### ISSUE THREAD

**Issue by rvnovaes** [gestaolegalufmg/gestaolegal#3]
Criar página na WIKI, como o título Glossário.

Esta página deverá ser organizada por verbertes em ordem alfabética.

Cada verbete deverá ter uma descrição/explicação dos termos.

Deverão ser cadastrados termos em geral.

**Comment by gabriellasaffioti** [comment]
não estou encontrando a página do glossário, onde está @Giuliana-Rezende?

**Comment by Giuliana-Rezende** [comment]
https://github.com/rvnovaes/gestaolegal/wiki/Gloss%C3%A1rio :)
