### ISSUE TITLE
Edição do contrato de prestação de serviços do programador

### ISSUE THREAD

**Issue by AmandaFuso** [gestaolegalufmg/gestaolegal#31]
Requisitos: 
- Cláusula NDA e previsão sobre Direitos autorais

**Comment by ailtongomess** [comment]
[Contrato de Prestação de Serviço_Modelo.docx](https://github.com/rvnovaes/gestaolegal/files/3844548/Contrato.de.Prestacao.de.Servico_Modelo.docx)
