### ISSUE TITLE
Instruções de postagens de erros e bugs

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#35]
### Instruções de postagem de erros
Oi, pessoal! 
Esse issue foi criado pelo Gestão Legal com o objetivo de reportar os bugs encontrados no site desenvolvido. Para isso, achei melhor estabelecermos algumas regras para os reports feitos.

### Instruções de Postagem
1. **Pense bem**. Ao escrever um relatório de um problema, tente se colocar na posição do desenvolvedor e se perguntar: "_O que eu gostaria de saber para ser capaz de investigar e consertar esse problema?_"
2. **Exclusividade**. Cada problema encontrado deve ser reportado em uma mensagem própria. Diferentes problemas, diferentes mensagens.
3. **Título**. Insira um título objetivo e claro: ao invés de "problema no cadastro de assistidos", experimente "não consigo cadastrar um assistido PJ como administrador";
4. **Numeração**. Inclua um passo a passo detalhado de como você chegou no erro, de preferência numerados. 
5. **Descrição**. Descreva o (i) problema em si, (ii) o tipo de login utilizado (administrador, estagiário, etc.), (iii) o navegador utilizado, (iv) e tudo mais que for ajudar a quem for resolver o problema.
6. **Imagens**. Use e abuse de capturas de tela, legendas para elas, highlights na captura e etc.

### Q&A de erros encontrados

1. **Permissões dos usuários**. Os usuários do sistema um significado: cada um deles têm poderes próprios no sistema. O **principal erro cometido** na primeira issue foi ter marcado como erro o que na verdade era a falta de permissão de um determinado usuário para fazer a tarefa. Para relembrar, a planilha de permissões pode ser encontrada [neste link aqui](https://docs.google.com/spreadsheets/d/1djrXHYvBX3rlsWaLkry5tmsnhX_NiEDDbwnfTplbGRY/edit?usp=sharing). Separei abaixo um pedacinho só pra vocês visualizarem já como é:

![image](https://user-images.githubusercontent.com/55855366/102016760-41245200-3d41-11eb-8927-14263c4e3e06.png)

### Funcionalidades já testadas (porém precisam de um double check):
- A.1. Login
- A.2. Tela de Funcionalidades
- B.1.1. Busca por nome ou CPF do atendido
- B.1.2. Cadastro de novo atendido
- B.1.3. Registro de Atendimento
- B.1.4. Cadastrar Caso - Continuação (faltam alguns detalhes apontados na reunião 21/08).
- B.1.5. Roteiros para Cadastro de Casos
- B.1.6. Encaminhamento para outras Assistências Jurídicas (foi finalizado?)
- B.2.1. Ativação/Indeferimento de um Caso
- B.2.2. Telas de rolagem dos casos a) e b)

### Funcionalidades recém desenvolvidas (e que devem ser analisadas com rigor):
- B.3. Tela individual do caso (com dados e ações)
- C.2. Planilha do Cronograma mensal de Plantão
- C.3. Registro de Presença no Plantão
- C.4. Arquivos Importantes
- C.1. Gerar Relatórios

### Como postar um erro?
- A partir de agora, **cada erro deverá ser postados como uma Issue separada**, para facilitar o acompanhamento:
![image](https://user-images.githubusercontent.com/55855366/110985390-2dda5000-834b-11eb-82d3-d8061da082e7.png)

- Depois de clicar em 'New Issue', basta preencher os campos seguindo as instruções acima. 
![image](https://user-images.githubusercontent.com/55855366/110985770-99bcb880-834b-11eb-9f63-75a9fdc1b366.png)

_Disclaimer jurídico: o relatório de qualquer erro ou a ausência de relatório de quaisquer erros não constitui abstenção do exercício do direito do Gestão Legal de exigir o devido cumprimento do contrato e seus anexos a qualquer tempo, nos termos da cláusula trigésima sexta do Contrato._

**Comment by taynaraginacio** [comment]
Erro ao associar um processo

Estou na conta do Orientador e tentei associar um processo para um caso aleatório, pois não há casos associados. Consegui fazer isso, mas não lembrava para qual caso tinha sido e tentei novamente no caso 38. Como já existe processos com o número 123, 1234, tentei o número 123456789123 e apareceu a seguinte mensagem na tela:
![image](https://user-images.githubusercontent.com/71410583/111080021-44afac80-84db-11eb-9204-a213b1392901.png)

**Comment by taynaraginacio** [comment]
Criação de processos - Necessidade de data para o trânsito em julgado

Tentei associar um processo ao caso 36 imaginando a situação hipotética de uma causa judicial em curso. Porém, para associar um processo é necessário inserir uma data final. Acho que a exigência dessa data para o cadastro de um novo processo não é ideal, pois o trânsito em julgado é o momento final de uma causa. 
![image](https://user-images.githubusercontent.com/71410583/111080174-05ce2680-84dc-11eb-80ce-7badfaed140b.png)

**Comment by taynaraginacio** [comment]
Editar um processo criado por outro usuário

Ao entrar no caso 35 e editar o processo, não há a opção de salvar as edições. O salvamento das minhas alterações até ocorreu, mas após eu ter tentado associar o processo, aparecendo uma tela de erro e, ao retornar para a página anterior, a mensagem de que as alterações foram salvas:
1. 
![image](https://user-images.githubusercontent.com/71410583/111080322-b805ee00-84dc-11eb-82d4-946c6fc8886d.png)
2.
![image](https://user-images.githubusercontent.com/71410583/111080335-c6eca080-84dc-11eb-97f9-07b1a3ff0baf.png)
3. 
![image](https://user-images.githubusercontent.com/71410583/111080345-d4a22600-84dc-11eb-8bd4-910277a8cd55.png)

**Comment by taynaraginacio** [comment]
Cadastro de usuário a ser notificado - Novo Lembrete

Ao criar um lembrete para um dos casos, não consegui associar outros usuários. Com isso, não consegui criar um lembrete para o caso. 

OBS: tentei encontrar o termo "Professor" e o termo "Alcione", que era a assistida do caso. 
![image](https://user-images.githubusercontent.com/71410583/111080485-73c71d80-84dd-11eb-99e1-ea51dff2292a.png)

**Comment by taynaraginacio** [comment]
Edição de evento criado pelo Orientador

Criei um evento para o caso 35. Inicialmente, ao visualizar esse evento não há opção de editá-lo, sendo necessário retornar à opção anterior para editar o evento. 
Ah, o arquivo anexado abriu normalmente, na mesma guia. Particularmente, acho que seria melhor abrir em uma guia distinta. 

![image](https://user-images.githubusercontent.com/71410583/111080772-bd643800-84de-11eb-9b97-f04c0913e722.png)

**Comment by taynaraginacio** [comment]
Edição de evento criado pelo orientador

Ao tentar editar o evento criado na mensagem anterior, não consegui adicionar um usuário responsável pois não aparecem opções na busca. Antes de tentar o termo "adm", tentei "Estagiário". 

![Uploading image.png…]()

**Comment by taynaraginacio** [comment]
Edição de evento criado pelo orientador - arquivo anexado 

O arquivo anexado na criação do evento desapareceu quando eu tentei editar esse evento:
![image](https://user-images.githubusercontent.com/71410583/111080865-49765f80-84df-11eb-82fa-3df3e1e50cb0.png)
Apos salvar a ediçao, o arquivo inicialmente anexado não consta no evento: 
![image](https://user-images.githubusercontent.com/71410583/111080889-66ab2e00-84df-11eb-8efb-780020b27798.png)

**Comment by taynaraginacio** [comment]
Edição de casos - Associar orientador ou assistido

Não consegui associar um orientador ou um assistido ao caso 42 pois não encontrei usuários.
![Uploading image.png…]()

**Comment by taynaraginacio** [comment]
> Edição de casos - Associar orientador ou assistido
> 
> Não consegui associar um orientador ou um assistido ao caso 42 pois não encontrei usuários.

O mesmo problema ocorreu com o colaborador externo.

**Comment by taynaraginacio** [comment]
Edição de casos - Associar Assistido
 
Na edição do caso não encontrei a opção relativa ao assistido. 
![image](https://user-images.githubusercontent.com/71410583/111081408-f94ccc80-84e1-11eb-93b9-f3b2aee8d658.png)

Ao entrar no perfil de assistido aleatório também não encontrei opções para associa-lo a um caso:
![image](https://user-images.githubusercontent.com/71410583/111081458-30bb7900-84e2-11eb-9ee3-a15fbdd0a067.png)

**Comment by taynaraginacio** [comment]
Dias de plantão do Orientador 

Na marcação dos dias de plantão aparecem dois dias, porém o orientador só deve, obrigatoriamente, participar de um plantão. 

![Uploading image.png…]()

**Comment by taynaraginacio** [comment]
Relógio - Registro de presença do orientador

O horário para a presença no Plantão não está acertado com a internet. Será que é possível manter a opção de editar o horário, mas que o horário automático esteja correto?
![image](https://user-images.githubusercontent.com/71410583/111145216-c567ba80-8566-11eb-951c-fe0c52441ec1.png)

**Comment by taynaraginacio** [comment]
Repositório com lembretes e eventos #sugestão

Não encontrei um repositório com os eventos e lembretes criados durante a minha sessão. Pensando no estagiário, acho que seria uma boa opção ter esses eventos e lembretes para ele se organizar. Da forma como está, apenas entrando no caso é possível ver os eventos, o que me deixa um pouco insegura se essa opção será ou não usada por estar meio "inacessível".
![image](https://user-images.githubusercontent.com/71410583/111145425-fea02a80-8566-11eb-9716-a5e1b4a2fc3e.png)

**Comment by taynaraginacio** [comment]
Atendidos e Assistidos - Como identificar o perfil de cada um 

A primeira página de atendidos e assistidos não permite que se identifique qual pessoa tem qual característica. Só entrando no perfil é que é possivel identificar que uma pessoa é assistida pelo fato de uma das caixas conter "Dados de Assistido". Na verdade, não sei se essa frase é genérica e todos naquela página estão identificados como Assistido. Será que é possível inserir uma coluna com "Assistido/Atendido" ou uma com o número do caso?

![image](https://user-images.githubusercontent.com/71410583/111145528-1b3c6280-8567-11eb-8619-9b106cd76ef0.png)

**Comment by taynaraginacio** [comment]
Quadro "Dia do plantão" na Página do Plantão #sugestao 

No quadro "Dia do plantão" há dois número (1º) e (2º) que não trazem informação nenhuma. Eles só mudam de cor quando vamos fazer a escolha dos dias, e depois dessa escolha o quadrinho não tem finalidade. Acho que seria bom unir o quadro "Dia do plantao" com "Seus dias de plantão"

![image](https://user-images.githubusercontent.com/71410583/111145689-4921a700-8567-11eb-9b49-523262acfa53.png)

**Comment by taynaraginacio** [comment]
Editar informações do plantão 

Em alguns casos, o estagiário quer mudar apenas uma das datas de plantão, ou por que já realizou um atendimento ou por ter indisponibilidade em apenas um dia. Não seria melhor a edição de plantão, ao invés de zerar as opções do usuário, perguntar a ele quais dias ele quer mudar?
![image](https://user-images.githubusercontent.com/71410583/111145786-6b1b2980-8567-11eb-8f29-019ec0601feb.png)

**Comment by rvnovaes** [comment]
Acrescida página na wiki com estas instruções (https://github.com/gestaolegalufmg/gestaolegal/wiki/Como-reportar-erros-ou-sugerir-melhorias)
