### ISSUE TITLE
Segurança de senha

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#36]
Atualmente ao cadastrar qualquer tipo de usuário o software não exige nenhum requisito mínimo de caracteres de senha. 
Ocorre que de acordo com a atual Lei Geral de Proteção de Dados, precisamos aumentar a segurança das senhas com as seguintes exigências:
- pelo menos 1 caractere maiúsculo
- pelo menos 1 caractere especial (.,;@#)
- alfanumérico.

![image](https://user-images.githubusercontent.com/55855370/111011421-11084180-8378-11eb-8393-5b1dfe1071a7.png)

**Comment by rvnovaes** [comment]
Você consegue colar o artigo da lei que se refere a esse ponto? Pq na verdade, a adição de caracteres especiais, números, maiúsculas não aumenta a segurança. O que aumenta a segurança é o tamanho da senha. Por exemplo, a senha A@3 é muito menos segura do que uma senha composta longa, composta por palavras comuns e sem relação. Por exemplo ratogrampeadorrelogioubatuba
 Para uma explicação simples: https://xkcd.com/936/

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Fiz testes na parte de cadastrar novo usuário e a issue parece ter sido corrigida. 
Apenas para constar: entre o reply do professor e a correção nós (Gabi, eu e professor) chegamos a conversar internamente sobre o comentário do professor e concluímos que os caracteres especiais não eram necessários. Apesar disso, não atualizamos aqui no Github, e a InfoJr acabou por corrigir o issue com base em nosso relato inicial. 
Já que a situação já foi modificada, sugiro manter como está com a exigência especial na senha.

> Você consegue colar o artigo da lei que se refere a esse ponto? Pq na verdade, a adição de caracteres especiais, números, maiúsculas não aumenta a segurança. O que aumenta a segurança é o tamanho da senha. Por exemplo, a senha A@3 é muito menos segura do que uma senha composta longa, composta por palavras comuns e sem relação. Por exemplo ratogrampeadorrelogioubatuba
> Para uma explicação simples: https://xkcd.com/936/
