### ISSUE TITLE
Máscara nas informações durante cadastro de usuário

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#37]
Durante o cadastro de usuários como administrador, identificamos que várias informações não tem máscaras - o que pode confundir o administrador durante o cadastro. São as seguintes informações:

- Máscara na informação de CPF (999.999.999-99)
![image](https://user-images.githubusercontent.com/55855370/111011851-86284680-8379-11eb-8c7d-ead0abedb1da.png)

- Máscara na informação do CEP (99.999-999)
![image](https://user-images.githubusercontent.com/55855370/111011773-347fbc00-8379-11eb-8bec-008b044635e0.png)

- Máscara nos telefones fixos e celular [para celular: (99) 99999-9999 e para fixo: (99) 9999-9999]
- Adicional: a caixa de data de nascimento pode ser alongada para aparecer a data completa (no momento aparece apenas o mês e o ano)
![image](https://user-images.githubusercontent.com/55855370/111011804-5d07b600-8379-11eb-974a-a5623756108b.png)

**Comment by rvnovaes** [comment]
Este caso e o #40  serão tratados conjuntamente.

**Comment by shevah7** [comment]
Testei e os campos continuam sem apresentar máscaras. Porém, o campo de data de nascimento foi expandido e agora é possível colocar o dia também.

![Captura de Tela (78)](https://user-images.githubusercontent.com/71346842/119346741-fce29980-bc70-11eb-87d1-250f772786b3.png)

Usuário: Administrador
Navegador: Google Chrome

**Comment by elisacostab** [comment]
Os campos aparentemente continuam sem apresentar máscaras.

![máscara cep](https://user-images.githubusercontent.com/89033709/133804296-96b51585-7610-4ca1-b81e-d2d4da729e62.png)
![mascara telefone](https://user-images.githubusercontent.com/89033709/133804300-26ca7415-2904-42f8-98ad-21f3ad6c12c2.png)
![mascarca cpf](https://user-images.githubusercontent.com/89033709/133804304-d8815300-5d25-4973-a853-180cc4f6c226.png)

@Ale-eloy

**Comment by elisacostab** [comment]
Ao que tudo indica as máscaras foram adicionadas aos campos do CPF e dos telefones. Contudo, o campo do CEP permanece sem. @Ale-eloy 

![máscara cep](https://user-images.githubusercontent.com/89033709/133812124-b2908e1b-307b-459a-a205-810379048cd2.png)
![mascara telefone](https://user-images.githubusercontent.com/89033709/133812146-152b0aca-0a38-41cd-8e07-2b2115620a85.png)
![mascarca cpf](https://user-images.githubusercontent.com/89033709/133812155-84403cc8-ed13-4f2c-a81b-5e96048f6232.png)

**Comment by Ale-eloy** [comment]
Mesmo tratamento do issue #40 , precisamos saber então qual a viabilidade técnica da implementação desse autopreenchimento por CEP? Hoje em dia quase todos os sites contam com a funcionalidade, e é bem útil.

**Comment by elisacostab** [comment]
Após logar com o usuário administrador e proceder com o cadastro de usuário, percebe-se a ausência de máscara tanto em CEP quanto em CPF.

![gestão usuarios](https://user-images.githubusercontent.com/89033709/150876017-573903c0-8045-488c-ba51-c02b435757da.png)

![Sem títulogu 2](https://user-images.githubusercontent.com/89033709/150876035-f44c84b5-8a21-4e78-8227-646f336c4445.png)
