### ISSUE TITLE
Tamanho do botão de notificações na tela inicial

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#38]
O botão de notificações na tela inicial está maior do que os outros no layout durante o login como administrador no navegador google chrome. Sugerimos deixar todos os botões em tamanhos iguais:

![image](https://user-images.githubusercontent.com/55855370/111012410-a1e01c80-837a-11eb-94fc-510c1bac83d5.png)

**Comment by rvnovaes** [comment]
O layout é responsivo, ou seja, muda de tamanho conforme o tamanho do dispositivo. Como o texto de "notificações" é mais longo do que "casos", o layout se reacomoda deslocando o ícone para o topo do texto, o que dá a impressão de o botão ser maior.

**Comment by gabriellasaffioti** [comment]
@rvnovaes Professor, testamos em mais de 1 pc e o tamanho do layout continuou desproporcional. Por isso, estou reabrindo a Issue.

**Comment by rvnovaes** [comment]
A questão não é o botão que está maior, mas o tamanho do texto. O que pode ser feito é alterar o CSS com os tamanhos dos textos. Vou deixar o issue aberto mas com prioridade baixa.

**Comment by shevah7** [comment]
Testei e agora os botões aparecem com os mesmos tamanhos: 
![Captura de Tela (88)](https://user-images.githubusercontent.com/71346842/119352158-b5134080-bc77-11eb-9c81-f7dfa4122b81.png)

Usuário: Administrador
Navegador: Google Chrome
