### ISSUE TITLE
Formalização dos Pequenos fluxos do Plantão de Atendimento

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#4]
Desenhar no Bizagi os pequenos fluxos que serão destacados do fluxo maior original

Atendimento Avulso --> Assistido comparece sem hora marcada e demanda atendimento
Psicologia
Clínica de Direitos Humanos
Atendimento dos Orientadores aos alunos

**Comment by ailtonadvti** [comment]
![Atendimento sem hora marcada do assistido](https://user-images.githubusercontent.com/55855407/66947287-033a7980-f029-11e9-8e66-dfb1c386a15b.png)


Atendimento sem hora marcada do assistido

**Comment by ailtonadvti** [comment]
![Auxílio dos orientadores aos estagiários de direito](https://user-images.githubusercontent.com/55855407/66947323-13525900-f029-11e9-863a-135f4652c93f.png)

Auxílio dos orientadores aos estagiários de direito

**Comment by ailtonadvti** [comment]
![Fluxo do estagiário da CDH](https://user-images.githubusercontent.com/55855407/66947360-1f3e1b00-f029-11e9-807b-5b8b98f29423.png)

Fluxo do estagiário da CDH

**Comment by ailtonadvti** [comment]
![Fluxo do estagiário da psicologia](https://user-images.githubusercontent.com/55855407/66947377-29f8b000-f029-11e9-98fb-a95ba07b03f3.png)

Fluxo do estagiário da psicologia

**Comment by ailtonadvti** [comment]
![Fluxo do lançamento das presenças](https://user-images.githubusercontent.com/55855407/66947408-35e47200-f029-11e9-9c8f-bcc094c093ae.png)

Fluxo do lançamento das presenças

**Comment by ailtonadvti** [comment]
![Orientação jurídica e ou Anotação de caso](https://user-images.githubusercontent.com/55855407/66947444-4ac10580-f029-11e9-80bf-447d008fb341.png)

Orientação jurídica e ou Anotação de caso

**Comment by ailtonadvti** [comment]
![Reunião de deferimento civil](https://user-images.githubusercontent.com/55855407/66947480-60cec600-f029-11e9-9095-d8001fc244f2.png)

Reunião de deferimento Civil

**Comment by ailtonadvti** [comment]
![Triagem do plantão](https://user-images.githubusercontent.com/55855407/66947538-704e0f00-f029-11e9-8eff-c984eefac412.png)

Triagem do plantão

**Comment by ailtonadvti** [comment]
![Triagem do plantão](https://user-images.githubusercontent.com/55855407/66950453-c2ddfa00-f02e-11e9-902c-fddee51719fb.png)

Triagem do plantão

**Comment by ailtonadvti** [comment]
![Fluxo da planilha de escala do plantão](https://user-images.githubusercontent.com/55855407/66950467-cf625280-f02e-11e9-822a-44d95254d207.png)

Fluxo da planilha de escala do plantão

**Comment by gabriellasaffioti** [comment]
> ![Orientação jurídica e ou Anotação de caso](https://user-images.githubusercontent.com/55855407/66947444-4ac10580-f029-11e9-80bf-447d008fb341.png)
> 
> Orientação jurídica e ou Anotação de caso

Quando fui fazer a descrição do fluxo percebi que falta uma possibilidade: "Caso não é judicializado". Nesta opção, o caso não é cadastrado pela DAJ nem o atendido é encaminhado para outra instituição, apenas há a resposta para a dúvida jurídica.

**Comment by Alex19-tech** [comment]
> ![Fluxo da planilha de escala do plantão](https://user-images.githubusercontent.com/55855407/66950467-cf625280-f02e-11e9-822a-44d95254d207.png)
> 
> Fluxo da planilha de escala do plantão

@ailtonadvti acabei de fazer o detalhamento deste fluxo na wiki e percebi uma incompatibilidade entre o fluxo e o que está descrito na wiki. 
Exemplo: a wiki diz que a planilha é aberta nos último dias do mês e fechada após os 5 dias subsequentes. Por outro lado, o fluxo apenas diz sobre os 5 ultimos dias do mês.

Sugiro que levante essa questão e confirme qual a versão correta. Uma vez solucionado, responda-me com o fluxo correto para que eu atualize a descrição do fluxo na Wiki.

- [ ] Verificar qual a versão correta do fluxo de elaboração de planilhas de 

- [ ] Atualizar .img do fluxo e sua respectiva descrição na Wiki

**Comment by Alex19-tech** [comment]
> ![Fluxo do estagiário da psicologia](https://user-images.githubusercontent.com/55855407/66947377-29f8b000-f029-11e9-98fb-a95ba07b03f3.png)
> 
> Fluxo do estagiário da psicologia

Dúvida: @ailtonadvti , quem é encaminhado para outros locais no atendimento da psicologia? O  assistido ou o relatório? São necessários mais detalhes ou este fluxo é de menor importância?

**Comment by gabriellasaffioti** [comment]
@Alex19-tech, o assistido é encaminhado para outros locais de atendimento como por exemplo o posto de saúde ou lhe é indicado psicólogos que atendem com preço social. Os estagiários da psicologia fazem um controle interno dos relatórios deles. Esse fluxo é de menor importância.
