### ISSUE TITLE
Máscaras nos textbox durante o cadastro de atendido

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#40]
Durante o cadastro de Novo Atendido, as textbox de CPF, telefone fixo e telefone celular não tem máscara. Sugerimos a implementação de máscara nesses dados:

Máscara na informação de CPF (999.999.999-99)
Máscara nos telefones fixos e celular [para celular: (99) 99999-9999 e para fixo: (99) 9999-9999]

![image](https://user-images.githubusercontent.com/55855370/111013234-6dba2b00-837d-11eb-9fcf-c257fe43ad1b.png)

Passo a passo: dentro de Plantão -> Atendidos e Assistidos -> Cadastrar novo Atendido (navegador chrome, usuário administrador)

**Comment by rvnovaes** [comment]
#37 Relacionado

**Comment by Ale-eloy** [comment]
### Sugestão adicional

No caso do cadastro das informações de endereço, sugerimos ir um passo além da simples utilização de máscaras: utilizar o banco de dados público de estados, municípios e CEPs para encontrar o nome da cidade a partir dessas informações. Nesse caso, ficaria da seguinte forma:

1. CEP (usuário digita o CEP e o sistema busca online o endereço para aquele CEP)
2. Estado (automaticamente pelo CEP ou manualmente pelo usuário)
3. Município (automaticamente pelo CEP ou manualmente pelo usuário)
4. Logradouro e número (automaticamente pelo CEP ou manualmente pelo usuário)

![image](https://user-images.githubusercontent.com/55855366/111881170-18d67000-898e-11eb-9d38-f93356a82330.png)

**Comment by Ale-eloy** [comment]
> ### Sugestão adicional
> No caso do cadastro das informações de endereço, sugerimos ir um passo além da simples utilização de máscaras: utilizar o banco de dados público de estados, municípios e CEPs para encontrar o nome da cidade a partir dessas informações. Nesse caso, ficaria da seguinte forma:
> 
> 1. CEP (usuário digita o CEP e o sistema busca online o endereço para aquele CEP)
> 2. Estado (automaticamente pelo CEP ou manualmente pelo usuário)
> 3. Município (automaticamente pelo CEP ou manualmente pelo usuário)
> 4. Logradouro e número (automaticamente pelo CEP ou manualmente pelo usuário)
> 
> ![image](https://user-images.githubusercontent.com/55855366/111881170-18d67000-898e-11eb-9d38-f93356a82330.png)

Sugerimos as mesmas melhorias também na página de "Cadastrar Assistências Judiciárias" em https://gestaolegalapp.direito.ufmg.br/plantao/nova_assistencia_judiciaria/

**Comment by shevah7** [comment]
Assim como no caso #37 , as máscaras ainda não foram implementadas. Da mesma forma, ainda não há uso dos bancos de dados públicos sugeridos pelo Ale para as localidades. 
![Captura de Tela (86)](https://user-images.githubusercontent.com/71346842/119348879-d2461000-bc73-11eb-8c1c-115e7a66afc9.png)

Usuário: Administrador
Navegador: Google Chrome

**Comment by elisacostab** [comment]
1- Ao que tudo indica, as máscaras para o campo do CPF e dos telefones foram implementadas. 

![presença de máscaras ao cadastrar novo atendido](https://user-images.githubusercontent.com/89033709/133816569-3a338a34-9f59-494c-b2e5-783ef1d24eef.png)

2- No que diz respeito à sugestão adicional sugerida pelo Alessandro, parece não ter sido implementado o uso do banco de dados públicos, tanto para o cadastro de novo atendido, quanto para o cadastro em assistência judiciária. 

**Cadastro de novo atendido**:
![campo do cep sem máscara e sugestão adicional](https://user-images.githubusercontent.com/89033709/133816971-1b03dbb9-9940-4bb3-a974-98b784143420.png)

**Cadastro de assistência judiciária**:
![nova assitência](https://user-images.githubusercontent.com/89033709/133817094-c4457a24-3105-4ff9-af40-6ec5e6f8dde3.png)

3- Inclusive, acho que seria legal adicionar máscara para o campo do CEP em ambos os casos.

@Ale-eloy

**Comment by Ale-eloy** [comment]
Beleza! Precisamos saber então qual a viabilidade técnica da implementação desse autopreenchimento por CEP? Hoje em dia quase todos os sites contam com a funcionalidade, e é bem útil.

**Comment by elisacostab** [comment]
Ao entrar com o usuário administrador e requisitar o cadastro de um novo atendido, percebe-se que as máscaras para os telefones, cpf e cep foram devidamente adicionadas. 

![a 1](https://user-images.githubusercontent.com/89033709/150877648-2c32f2ae-6a7a-47f0-b6b7-b77619a8ba06.png)

Contudo, observa-se que não houve modificação quanto à sugestão feita pelo @Ale-eloy 

![a2](https://user-images.githubusercontent.com/89033709/150877650-de7c1629-34c7-4dbc-b018-473526540913.png)

Assim como para o cadastro de assistência judiciária, vez que não há utilização do banco de dados públicos. 

![aaa](https://user-images.githubusercontent.com/89033709/150878093-853a783e-9055-4954-b1f5-f6f29ccd845c.png)
