### ISSUE TITLE
Retirar campo de área da demanda em Cadastro de Novo Atendido

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#41]
Durante o cadastro de um Novo Atendido, o formulário exige que se cadastre a Área da Demanda. Solicitamos a **exclusão** desse campo, pois ele já está presente na Orientação Jurídica:

![image](https://user-images.githubusercontent.com/55855370/111013509-6e9f8c80-837e-11eb-9a05-f12d461dd282.png)

Passo a passo: navegador chrome, logado como administrador, dentro da página de cadastrar Novo Atendido

**Comment by shevah7** [comment]
O campo ainda não foi excluído e continua disponível no cadastro de Novo Atendido.
![Captura de Tela (87)](https://user-images.githubusercontent.com/71346842/119350516-d115e280-bc75-11eb-8bca-180bf63fc6a7.png)

Usuário: Administrador
Navegador: Google Chrome

**Comment by elisacostab** [comment]
Reproduzi o relato e o campo parece ter sido excluído. 

![campo foi retirado](https://user-images.githubusercontent.com/89033709/133798874-5af35487-6cc8-4b55-b093-8d16f0dc626a.png)
