### ISSUE TITLE
Layout confuso na página de Associar Atendidos após cadastro de Nova Orientação Jurídica

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#42]
O atual layout da página de "associar atendidos à uma nova orientação jurídica" está confuso, pois entre o campo "Buscar Atendido" e "Atendido Selecionado", existe a caixa de seleção de Assistência Judiciária. Sugerimos colocar o campo Assistências Judiciárias (opcional) acima de todos os campos, para que não fique no meio deles.

![image](https://user-images.githubusercontent.com/55855370/111013775-7f9ccd80-837f-11eb-88be-59ba70418971.png)

**Comment by shevah7** [comment]
Testei e o layout permanece o mesmo:
![Captura de Tela (99)](https://user-images.githubusercontent.com/71346842/119357997-8a78b600-bc7e-11eb-9e08-71ebcdff682e.png)

**Comment by shevah7** [comment]
Testei e agora o layout aparece na ordem corrigida e mais intuitiva:
![Captura de Tela (159)](https://user-images.githubusercontent.com/71346842/134392496-2c5a29e8-2c44-411c-91a5-8a536e7ca3fe.png)
Porém, o campo "assistências judiciárias (opcional)" foi removido da página, assim como o campo "atendido selecionado".

@Ale-eloy

**Comment by Ale-eloy** [comment]
@shevah7, obrigado!

1. Em relação ao campo "atendido selecionado", já pontuamos essa questão em outro issue.
2. Em relação ao desaparecimento do campo "assistências judiciárias (opcional)", ele realmente sumiu e não estou encontrando essa possibilidade em nenhum outro lugar. Vou verificar aqui com a @Giuliana-Rezende e retorno!

**Comment by Ale-eloy** [comment]
Criei um novo issue 164 com uma explicação mais bem detalhada do problema.
