### ISSUE TITLE
Botão de excluir caso não funciona na aba "visualizar caso"

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#43]
Usuário: Administrador
Navegador: Chrome
casos/visualizar/42 
Quando clico excluir, o pop up aparece confirmando o pedido, porém depois que confirmo nada acontece. 
![image](https://user-images.githubusercontent.com/62401923/111032644-0c7d7080-83ec-11eb-850b-073f89f934a8.png)

**Comment by rvnovaes** [comment]
Corrigido
