### ISSUE TITLE
413 Request Entity Too Large - Redirecionamento para outra página quando tento upload de arquivo muito grande

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#44]
Usuário: Administrador
Navegador: Chrome
casos/editar_caso/37
![image](https://user-images.githubusercontent.com/62401923/111032707-4fd7df00-83ec-11eb-9997-626811188c2f.png)

Ao tentar upar um arquivo muito grande, na página de editar casos, sou levado para esse Erro. Talvez se especificasse o tamanho máximo permitido seria mais fácil administrar isso. Exemplo:
![image](https://user-images.githubusercontent.com/62401923/111032791-b5c46680-83ec-11eb-98af-0e5ea52015cd.png)

 Além disso um pop-up que notificasse o erro na própria página, ao invés de te levar para outra página seria mais confortável, pois esse processo de redirecionamento pode te fazer perder o que tinha escrito nos campos anteriores.

**Comment by rvnovaes** [comment]
Qual o tamanho máximo de arquivos necessário? Eu sugeriria arquivos de, no máx, 10 Mb.

**Comment by Ale-eloy** [comment]
Acreditamos que 10MB seja um bom limite para começarmos a trabalhar.

**Comment by Ana-Rafaela** [comment]
Usuário: Administrador
Navegador: Chrome

Ao tentar upar os arquivos, a aparência é de que tinha sido inserido com sucesso, tanto para arquivos maiores que 10 MB (testei com 11,5 MB e 25 MB), quanto menores (testei com 292 KB). Ao salvar, havia redirecionamento para a página de Gestão de Casos. Porém, independentemente do tamanho do arquivo, ao tentar visualizar depois, fazendo download, ocorria o erro 404. 

Isso seria um novo problema? Enseja a abertura de issue diferente?

![image](https://user-images.githubusercontent.com/71299300/119423320-66968e00-bcd9-11eb-9bfb-7280e54927b0.png)

![image](https://user-images.githubusercontent.com/71299300/119423427-9fcefe00-bcd9-11eb-817e-e6e524917790.png)

![image](https://user-images.githubusercontent.com/71299300/119423523-d86ed780-bcd9-11eb-85a2-7a24b28bbd5b.png)

**Comment by elisacostab** [comment]
Issue foi solucionado, sendo possível anexar o documento e baixar/visualizar, normalmente, existindo o tamanho máximo de 10MB sinalizado. 

![consegui anexar arquivo](https://user-images.githubusercontent.com/89033709/134786717-9ad23cdf-c70a-4b9a-bf4f-28af8ce973e6.png)
![anexouuuu](https://user-images.githubusercontent.com/89033709/134786721-09b5dee7-2512-4658-ad92-b96bed9eec9e.png)
![consegui baixar](https://user-images.githubusercontent.com/89033709/134786723-9a06123d-5702-4643-84a0-3f070b99e6bd.png)

Além disso, não é mais possível upar um arquivo maior que 10 MB, como foi relatado.
![maior que 10](https://user-images.githubusercontent.com/89033709/134786796-338f54a6-5d80-40e1-a7a1-1e2fcd78cba3.png)

**Comment by Ale-eloy** [comment]
O issue ainda não foi resolvido. Arquivos com mais de 10MB geram erro, conforme print abaixo:

![image](https://user-images.githubusercontent.com/55855366/135325793-31550bda-ac13-449c-973d-70ded3e99cb2.png)

Esse erro pode ser melhor tratado com um popup conforme sugerido no comentário inicial do issue.

**Comment by Ale-eloy** [comment]
Refiz o teste com um arquivo maior que 10MB e percebi que o sistema continua apresentando a página de erro. Ainda entendo que isso possa ser melhorado para mostrar apenas uma caixa de pop-up.

> O issue ainda não foi resolvido. Arquivos com mais de 10MB geram erro, conforme print abaixo:
> 
> ![image](https://user-images.githubusercontent.com/55855366/135325793-31550bda-ac13-449c-973d-70ded3e99cb2.png)
> 
> Esse erro pode ser melhor tratado com um popup conforme sugerido no comentário inicial do issue.

**Comment by luisaviterbo** [comment]
Para testar esse "issue", eu criei um novo caso "Caso 13", como mostrado no print. Como é possível ver, o caso foi criado com sucesso, com o upload de um arquivo dentro do limite de 10MB. Posteriormente, para visualizar o caso, é também possível verificar que eu conseguir fazer o download do arquivo para poder consultá-lo. Para fazer o teste com um arquivo maior que 10MB, eu fui tentar editar o Caso 13 para apenas trocar o arquivo, mas deu erro na hora de tentar editá-lo (seria esse um novo/ outro problema?) como podemos ver no penúltimo print. Então, eu tentei criar um novo caso para verificar essa questão de arquivos que excedem esse limite, e na hora de finalizar, deu o erro descrito no último print. Logo, está sendo possível criar casos com arquivos com tamanhos menores de 10MB, sendo possível visualizá-los posteriormente, mas não os editar. Também conclui que arquivos maiores de 10MB impedem a criação de um novo caso. 

![image](https://user-images.githubusercontent.com/108672047/198839063-3ff16091-fcf7-45d1-af44-5859b92d680e.png)
![image](https://user-images.githubusercontent.com/108672047/198839070-05c5166d-aee8-40fa-a587-3400a5c04e0f.png)
![image](https://user-images.githubusercontent.com/108672047/198839078-9d32a325-4d91-4bd5-ae8c-e3f05d8e08d4.png)

**Comment by Ale-eloy** [comment]
Issue transformado no issue 207. O internal server error mencionado pela Luisa será cadastrado em novo issue.
