### ISSUE TITLE
Qualquer formato é permitido para upload, apesar do site especificar apenas .pdf

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#45]
Usuário: Administrador
Navegador: Chrome
casos/editar_caso/37
![image](https://user-images.githubusercontent.com/62401923/111032839-fe7c1f80-83ec-11eb-81cd-8ad2705da85b.png)
Apesar de especificar apenas arquivos .pdf, o site me permitiu upar arquivos .jpg, ; .xlsl etc. na aba de editar casos.

**Comment by rvnovaes** [comment]
Quando é feito upload de arquivo no caso, retorna erro 500

**Comment by rvnovaes** [comment]
#46

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by lucasdeor** [comment]
Testei e parece que a issue foi corrigida.

**Comment by Ale-eloy** [comment]
Testei e também me parece que a issue foi corrigida.
