### ISSUE TITLE
O arquivo anexado tem o nome alterado quando faço uplaod pro site

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#46]
Usuário: Administrador
Navegador: Chrome
casos/editar_caso/37 e casos/visualizar/37
![image](https://user-images.githubusercontent.com/62401923/111032890-3f743400-83ed-11eb-8f5e-313c9a377954.png)

Quando faço upload de um arquivo em na aba "editar caso" seu nome é alterado.

**Comment by rvnovaes** [comment]
#45

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by lucasdeor** [comment]
Testei e parece que a issue foi corrigida

**Comment by Ale-eloy** [comment]
Testei e também me parece que a issue foi corrigida.
