### ISSUE TITLE
Não é permitido upar mais de um arquivo para um caso

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#47]
Usuário: Administrador
Navegador: Chrome
caso/visualizar/37
![image](https://user-images.githubusercontent.com/62401923/111032961-9f6ada80-83ed-11eb-9427-1dfd3a967664.png)

Para upar um arquivo, tenho que ir na aba "editar caso" e selecionar um novo. Porém caso salve a página sem adicionar outro arquivo, o anterior é deletado do caso. Além disso, se salvo a página com um novo arquivo, esse substitui o anterior.

**Comment by rvnovaes** [comment]
#45 #46

**Comment by lucasdeor** [comment]
Realizei teste novamente e erro persiste.

**Comment by diegopabulo** [comment]
Usuário: Administrador
Navegador: Chrome
Caso: 22 e 21

O problema parece ter sido resolvido. 
No caso já havia um arquivo. Então editei o caso, anexei um novo arquivo e salvei. O arquivo anterior não foi substituído, mas apenas adicionado um novo arquivo.

Também testei a outra situação. Cliquei em editar o caso e salvei sem ter adicionado um novo arquivo. Os dois arquivos permaneceram no caso e não foram deletados.

Todavia, encontrei um problema. Aparentemente não é possível excluir os arquivos adicionados ao caso.

![image](https://user-images.githubusercontent.com/89043822/133906052-7b71dd0a-174a-4edc-8900-706f4ed61465.png)
