### ISSUE TITLE
Caixa de "Assistidos" com tamanho sem padrão perde formato

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#48]
Usuário: Administrador
Navegador: Chrome
casos/visualizar/38
]![image](https://user-images.githubusercontent.com/62401923/111033028-fec8ea80-83ed-11eb-8752-67bc8d0d0a0d.png)

Formato da caixa poderia ser padrão, para não desformatar textos de tamanhos diferentes.

**Comment by shevah7** [comment]
Testei e a caixa continua perdendo a formatação quando há mais de um assistido.

![Captura de Tela (91)](https://user-images.githubusercontent.com/71346842/119353250-0bcd4a00-bc79-11eb-8d0b-7c5ec1189f6b.png)

Usuário: Administrador
Navegador: Google Chrome

**Comment by gabriela-lp** [comment]
Issue corrigida
![image](https://user-images.githubusercontent.com/70505460/134773937-31db020e-f256-42bb-a089-ee4f62bf87c2.png)
