### ISSUE TITLE
Quando acabo de editar um caso, sou redirecionado para aba “casos". 

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#49]
Usuário: Administrador
Navegador: Chrome
/casos/editar_caso/39
![image](https://user-images.githubusercontent.com/62401923/111033059-2ae46b80-83ee-11eb-8282-2a235656c62a.png)
Quando acabo de editar um caso, o site me redireciona para aba “casos”. É mais cômodo quando sou levado para o próprio caso que acabei de editar. A mesma coisa acontece quando crio um lembrete ou associo um processo.

**Comment by rvnovaes** [comment]
Duplicado de #84
