### ISSUE TITLE
Alteração de pop-up após editar caso.

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#50]
Usuário: Administrador
Navegador: Chrome
/casos/editar_caso/37 e /casos
![image](https://user-images.githubusercontent.com/62401923/111033211-cd9cea00-83ee-11eb-99c5-225cf4c91364.png)

A palavra "sucesso" repete muito perto uma da outra. Sugiro que a mensagem seja alterada para apenas: "Sucesso! O caso foi editado" ou "O caso foi editado com *sucesso*".

**Comment by rvnovaes** [comment]
Desnecessário.
