### ISSUE TITLE
Formatação de valor da causa em "Novo processo"

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#51]
Usuário: Administrador
Navegador: Chrome
casos/novo_processo/42
![image](https://user-images.githubusercontent.com/62401923/111033239-f45b2080-83ee-11eb-8bd4-abaab27ec2e2.png)
Valor da causa poderia ser formatado para R$XXXX,XX  da mesma forma que é na aba "visualizar processo" (/casos/processo/56?id_caso=42) 
![image](https://user-images.githubusercontent.com/62401923/111033328-8105de80-83ef-11eb-8534-1e0afab9b606.png)

**Comment by shevah7** [comment]
Testei e a formatação em R$XXXX,XX foi aplicada:
![Captura de Tela (93)](https://user-images.githubusercontent.com/71346842/119354270-42579480-bc7a-11eb-8a43-a77bd7b6d5f7.png)

Usuário: Administrador
Navegador: Google Chrome
