### ISSUE TITLE
Campos não comportam textos grandes na aba visualizar processos

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#52]
Usuário: Administrador
Navegador: Chrome
casos/processo/56?id_caso=42
![image](https://user-images.githubusercontent.com/62401923/111033352-9a0e8f80-83ef-11eb-82e1-5d5fc0cc27e1.png)
(1) Campos de “Observações” e “link” na aba de “visualizar processo” não comportam textos grandes.

**Comment by rvnovaes** [comment]
O campo link não precisa de ser text box. O de observações já foi alterado para text box.
