### ISSUE TITLE
Campos link e observações do processo estouram o tamanho da tela

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#53]
Usuário: Administrador
Navegador: Chrome
casos/processo/56?id_caso=42
![image](https://user-images.githubusercontent.com/62401923/111033369-b1e61380-83ef-11eb-8c38-305f70acc3a6.png)
(2)Data em formato não convencional

**Comment by rvnovaes** [comment]
O formato deve ser dd/mm/aaaa

**Comment by shevah7** [comment]
Testei novamente e a data permanece em formato não convencional.

![Captura de Tela (75)](https://user-images.githubusercontent.com/71346842/119345440-44682600-bc6f-11eb-8860-8b6dadd82d82.png)
Usuário: Administrador
Navegador: Google Chrome

**Comment by diegopabulo** [comment]
Usuário: Administrador
Navegador: Chrome

Testei novamente e, em relação ao formato da data, parece que foi corrigido, pois não está no formato americano. Porém, constatei que também foram mencionados outros tipos de dados, como o campo "observação" e o campo "link".

Veja no print que os dados informados nesses campos extrapolam o campo e não há quebra de página. Portanto, o problema ainda continua em relação aos campos "observação" e "link".

![image](https://user-images.githubusercontent.com/89043822/133906654-2703ed47-56e0-42ec-bea6-f1577b64dacd.png)

**Comment by RaphaGg** [comment]
Usuário: Administrador
Navegador: Chrome

Conforme pode ser visualizado no print, a seguir, a data foi adequada ao formato dd/mm/aaaa, porém, o problema dos dados extrapolarem o campo permanece.

![testandiii](https://user-images.githubusercontent.com/89051386/150855629-f860a028-a6e7-4782-8472-2ef44618088c.png)

**Comment by Ale-eloy** [comment]
Issue me parece ter sido resolvido. Não consegui reproduzir.

**Comment by quenyx** [comment]
![Captura de Tela (140)](https://github.com/gestaolegalufmg/gestaolegal/assets/129747233/218efe49-b422-40f3-991d-bb10a7e3b699)
![Captura de Tela (141)](https://github.com/gestaolegalufmg/gestaolegal/assets/129747233/37ecc91a-0414-4a85-bc49-9bb3d3ad60c4)

No caso em questão (53), ao tentar reproduzir o caminho até o erro, nada foi encontrado pois aparentemente o caso já não está mais no sistema. Contudo, ao usar para teste o caso de número 10, criei um processo e associei o assistido a ele. 
Link: https://gestaolegalteste.direito.ufmg.br/casos/processo/5?id_caso=10

A partir disso, é possível observar que os campos "observações" e "link" se encontram sem erros.

**Comment by quenyx** [comment]
No caso em questão (53), ao tentar reproduzir o caminho até o erro, nada foi encontrado pois aparentemente o caso já não está mais no sistema. Contudo, ao usar para teste o caso de número 10, criei um processo e associei o assistido a ele. 
Link: https://gestaolegalteste.direito.ufmg.br/casos/processo/5?id_caso=10

A partir disso, é possível observar que os campos "observações" e "link" se encontram sem erros. 

![Captura de Tela (140)](https://github.com/gestaolegalufmg/gestaolegal/assets/129747233/fb992fd5-4b3c-4d5d-aedb-7d07e659b1b4)
![Captura de Tela (141)](https://github.com/gestaolegalufmg/gestaolegal/assets/129747233/4b4a49a6-9186-4ce2-a27d-8fb201ccedf8)
