### ISSUE TITLE
Não consigo editar processo - Erro 500

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#54]
Usuário: Administrador
Navegador: Chrome
casos/editar_processo/56
![image](https://user-images.githubusercontent.com/62401923/111033440-f7a2dc00-83ef-11eb-837e-f50f5cd48918.png)
Ao tentar editar um processo sou levado para essa página de erro

**Comment by rvnovaes** [comment]
Duplicado de #87
