### ISSUE TITLE
Faltam campos na aba de "Cadastrar novo caso"

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#56]
Usuário: Administrador
Navegador: Chrome
casos/novo_caso
![image](https://user-images.githubusercontent.com/62401923/111033577-ae06c100-83f0-11eb-9380-1702daedaf67.png)
A aba de “novo caso” só me permite preencher 3 campos, sendo que um caso tem vários outros como orientador, estagiário etc.
Poderia ter os mesmos campos que a aba "editar caso"
![image](https://user-images.githubusercontent.com/62401923/111033613-d8587e80-83f0-11eb-807d-033dd18cda4b.png)

**Comment by rafaelvinisan** [comment]
A página de cadastro de casos nas versões antigas do sistema contava com estes campos, entretando em nossas reuniões ficou acordado que deveriam ter apenas no Editar pois não fazia sentido associar responsáveis por um caso assim que ele fosse criado, e que isso é discutido em uma reunião semanal.

**Comment by Ale-eloy** [comment]
Ei @rafaelvinisan! Nós conferimos aqui e concordamos que você tem razão, realmente o fluxo de trabalho atual deve ser feito da forma como está hoje. Obrigado pelo feedback!

Sugestão final @rvnovaes: fechar o issue;
