### ISSUE TITLE
Não há como editar notificações 

### ISSUE THREAD

**Issue by lucasdeor** [gestaolegalufmg/gestaolegal#58]
Usuário: Administrador
Navegador: Chrome
/notificacoes
![image](https://user-images.githubusercontent.com/62401923/111033941-2fab1e80-83f2-11eb-84d5-f58fffa220e4.png)
Não sei se essa é a intenção, mas não consigo editar/excluir/adicionar notificações na página

**Comment by rvnovaes** [comment]
Deve ser possível excluir notificações?

**Comment by Ale-eloy** [comment]
Iremos rodar mais testes na função de lembrete, pois há outros problemas que identificamos nela. Assim que terminados, vamos reportar se a edição deve ou não ser feita.
