### ISSUE TITLE
Não consigo excluir Assistências Judiciárias como Colaborador de Projeto

### ISSUE THREAD

**Issue by babilima** [gestaolegalufmg/gestaolegal#59]
Não encontrei a opção de excluir assistência judiciária como colaborador de projetos. Eu consigo editar, mas não consigo excluir.
Navegador: Chrome

**Comment by rvnovaes** [comment]
O colaborador de projeto não deve ter permissão para excluir assistências mesmo. Entretanto, se não pode excluir não deve também ter permissão para cadastrar.

**Comment by babilima** [comment]
Professor, na planilha de permissões está escrito que o Colaborador de projeto pode fazer cadastro, alterar e excluir assistências. Se ele não deve ter essa permissão, temos que mudar na planilha e bloquear as atividades de cadastro e alteração.

**Comment by rvnovaes** [comment]
Então ok. Entendido. O Colaborador deve ter as 3 permssões.

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Testei e me parece ter sido corrigida. 

![image](https://user-images.githubusercontent.com/55855366/119285000-6f269000-bc17-11eb-94b7-f9e35d1eaa72.png)
