### ISSUE TITLE
Redação da página com descrição de todos os fluxos mapeados do atendimento

### ISSUE THREAD

**Issue by gabriellasaffioti** [gestaolegalufmg/gestaolegal#6]
Criar página na wiki na qual serão colados todos os diagramas bizagi descritos no issues, será redigida pequena descrição e feitos os links para os artefatos de dados e outras páginas pertinentes.

**Comment by Alex19-tech** [comment]
https://github.com/rvnovaes/gestaolegal/wiki/Fluxos-Bizagi#fluxo-do-estagi%C3%A1rio-de-direito-no-atendimento-do-plant%C3%A3o
