### ISSUE TITLE
Mensagem de erro na tela de adicionar novo arquivo como Colaborador de Projeto

### ISSUE THREAD

**Issue by babilima** [gestaolegalufmg/gestaolegal#60]
Fui adicionar um novo arquivo e não fiz upload de nenhum documento dai apareceu uma mensagem de erro. Achei estanho pois existem outros arquivos que estão sem documento também. 
Navegador: Chrome
Usuário: Colaborador de projeto
![Captura de Tela (32)](https://user-images.githubusercontent.com/71464467/111042303-8547f100-841b-11eb-8822-f37ba992c8da.png)

**Comment by rvnovaes** [comment]
O erro 500 foi corrigido. Mas existe um erro de lógica.

Ao colaborador de projeto não é exibido o menu Cadastrar Arquivo, mas ele consegue cadastrar mesmo assim a partir da listagem de arquivos.

Ele deve ver o menu de cadastrar também.

![Screenshot from 2021-03-19 09-58-42](https://user-images.githubusercontent.com/374578/111784060-b2702580-8899-11eb-9ff7-a3e537ff14f4.png)

**Comment by babilima** [comment]
![Captura de Tela (44)](https://user-images.githubusercontent.com/71464467/119427314-3357fd00-bce1-11eb-81a6-3de98d5244f3.png)

Colaborador de Projetos ainda não possui opção de cadastrar arquivo na barra lateral

**Comment by Lucardoso06** [comment]
![image](https://user-images.githubusercontent.com/89036394/134352400-1114ca4f-d084-41ea-b6b0-4dfa9d4440e0.png)

Colaborador de Projetos agora possui a opção "cadastrar arquivo " na barra lateral. Issue corrigido.
