### ISSUE TITLE
Não consigo selecionar dias para fazer plantão como Colaborador de Projeto

### ISSUE THREAD

**Issue by babilima** [gestaolegalufmg/gestaolegal#61]
Não consigo selecionar dias para fazer plantão, pois aparece uma mensagem dizendo que só estagiário e orientador pode fazer isso.

**Comment by babilima** [comment]
![Uploading Captura de Tela (34).png…]()

**Comment by babilima** [comment]
![Captura de Tela (34)](https://user-images.githubusercontent.com/71464467/111042597-de645480-841c-11eb-8096-5c8e95b08163.png)

**Comment by Math-carvalho** [comment]
Realizei o teste e o problema do issue permanece (ainda não é possível selecionar dias para fazer plantão através do usuário Colaborador de Projeto)

![image](https://user-images.githubusercontent.com/71521066/119427754-f7716780-bce1-11eb-8d99-aa7ab274e788.png)

**Comment by Ana-Rafaela** [comment]
Inclusive, pelo que entendi, não seria um problema só do Colaborador de Projeto. Testei com _todos os usuários_ e realmente só funcionou com o de orientador e o de estagiário, quando, salvo melhor juízo, o esperado seria que todos pudessem fazer a marcação.

![image](https://user-images.githubusercontent.com/71299300/119427221-0d325d00-bce1-11eb-98ff-85e74ac6bbfb.png)
![image](https://user-images.githubusercontent.com/71299300/119427421-5e425100-bce1-11eb-88ea-4e0c765cfbd3.png)

Tabela de permissões ("Selecionar dias para fazer plantão"):
![image](https://user-images.githubusercontent.com/71299300/119428644-a6fb0980-bce3-11eb-98fb-06ad8ce37877.png)

**Comment by Ale-eloy** [comment]
@anarafaelafaria , você tem razão, **todos os usuários devem poder marcar registro de plantão no calendário**, segundo a planilha de permissões.
O anexo de CRUD menciona expressamente o orientador/estagiário apenas porque eles são os únicos usuários com limites de slots no plantão. Em relação a eles e ao limite de vagas, está tudo certo.
Porém, os outros usuários também devem ser capazes de registrar dia de plantão de forma simplificada, sem limite de vagas como ocorre no orientador/estagiário. Isso o sistema ainda não permite e precisa ser implementado.

**Comment by Ale-eloy** [comment]
Pessoal, vou fechar esse issue porque descobri que o mesmo problema também é relatado no issue #137 , então irei manter apenas aquele.
