### ISSUE TITLE
Não consigo confirmar presença no plantão como Colaborador de Projeto

### ISSUE THREAD

**Issue by babilima** [gestaolegalufmg/gestaolegal#62]
Não aparece a opção de confirmar presença no plantão, somente de registrar o meu plantão.
Navegador: Chrome
![Captura de Tela (35)](https://user-images.githubusercontent.com/71464467/111042639-1ff4ff80-841d-11eb-8f42-b4b400d05a14.png)

**Comment by Math-carvalho** [comment]
Realizei testes no issue e a situação permanece como foi descrito anteriormente.

**Comment by shevah7** [comment]
Testei o assunto do issue e a a situação permanece como descrita.
Consigo registrar o plantão, conforme o print:
![Captura de Tela (142)](https://user-images.githubusercontent.com/71346842/134267919-756eee4d-7574-490e-8f47-ffaa40450934.png)
Porém, não consigo confirmar a presença:
![Captura de Tela (143)](https://user-images.githubusercontent.com/71346842/134268017-5f918015-6b7d-402a-86b0-84dac05ea524.png)

Navegador: Chrome
Usuário: Colaborador de projeto

**Comment by guisouza3** [comment]
Realizei novamente o teste e continua não aparecendo a opção de confirmar presença no plantão, sendo apenas possível registrar o plantão.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/89096123/134439011-a99bcd05-77c6-436b-8b78-9900ebc603a5.png)

Da mesma forma, além de não ser possível a confirmação da presença, sinto que falta espaço para que seja possível  selecionar o plantão registrado.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89096123/134447774-d0c3f782-49c6-4338-8695-8e4a76599b78.png)

**Comment by Ale-eloy** [comment]
Ei pessoal!
Reproduzi os testes e acredito que houve um equívoco na hora de testar. A checagem de ponto exige uma série de etapas prévias para que ela possa aparecer, incluindo a abertura prévia do plantão por um usuário com autorização. Acredito que vocês talvez tenham se esquecido dessa etapa durante os testes e, por isso, vocês não conseguiram reproduzir o funcionamento do ponto.
Como tudo funcionou corretamente por aqui, irei fechar o issue.
