### ISSUE TITLE
Não é possível editar o cadastro de um assistido/atendido como Professor

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#63]
Segundo a planilha de permissões, o usuário do tipo Professor não pode cadastrar novos assistidos, mas pode alterar os dados dos já existentes:

![image](https://user-images.githubusercontent.com/55855366/111083112-8d229680-84ea-11eb-934c-9d2488b053f5.png)

Apesar disso, as opções de edição de cadastro não aparecem para mim quando estou logado como professor:

![image](https://user-images.githubusercontent.com/55855366/111083160-d7a41300-84ea-11eb-85e5-c8e626500f06.png)

Usuário: Professor
Navegador: Chrome

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Testei tanto o botão de edição quanto a edição de dados em si e me parece que a issue foi corrigida.

![image](https://user-images.githubusercontent.com/55855366/119281155-f28db480-bc0a-11eb-839c-c0c0a68d3fa2.png)
