### ISSUE TITLE
Não consigo cadastrar um novo Caso como Professor

### ISSUE THREAD

**Issue by Ale-eloy** [gestaolegalufmg/gestaolegal#64]
Segundo a planilha de permissões, o usuário do tipo Professor tem amplas autorizações na partes de Casos:

![image](https://user-images.githubusercontent.com/55855366/111083534-d4aa2200-84ec-11eb-9664-8760d72d15e3.png)

Entretanto, logado como Professor (professor@daj.com), não consigo (i) criar/cadastrar um novo Caso; nem (ii) associar Processo:

![image](https://user-images.githubusercontent.com/55855366/111083671-6fa2fc00-84ed-11eb-81a4-e6d8ca578214.png)

Usuário: Professor
Navegador: Chrome

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Realizei os testes e me parece que a issue foi corrigida.

![image](https://user-images.githubusercontent.com/55855366/119281257-6d56cf80-bc0b-11eb-93e2-09ed4414209a.png)
