### ISSUE TITLE
Meus casos - Colaborador de Projeto

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#67]
O colaborador de projeto não atua em nenhum caso. Por isso, acho que não precisa aparecer a aba "Meus casos" para ele.

![image](https://user-images.githubusercontent.com/71410583/111147623-740cfa80-8569-11eb-89a0-311a19122f3b.png)

**Comment by Ale-eloy** [comment]
Acho que podemos deixar como está, acredito que isso não prejudica a usabilidade do sistema para o Colaborador de Projeto de forma alguma.
