### ISSUE TITLE
Não consigo editar lembretes #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#68]
Não consigo editar lembretes

Depois de criado o lembrete, não consigo editá-lo..
Ao apertar em salvar, a tela carrega mas permanece no campo de edição.

![image](https://user-images.githubusercontent.com/71410583/111148668-aec36280-856a-11eb-9b34-03b5d74bcb1e.png)

A edição não é incorporada ao lembrete, ele permanece na forma original.
Navegador: Google Chrome
Usuário: Orientador

**Comment by rvnovaes** [comment]
Corrigido
