### ISSUE TITLE
Cadastro de usuários: Agenda de atendimento com campos incongruentes

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#70]
Navegador: Edge
Usuário: Professor

A agenda de atendimento é feita de forma genérica no cadastro. Na visualização do cadastro, há uma opção de dia do atendimento e horário de inicio de atendimento separados. Além disso, pelo que me lembro, essa agenda de atendimento é o horário que o usuário pretende ficar na DAJ e não o horário de início dos trabalhos (como uma folha de ponto, que justificaria o "início de atendimento".
![image](https://user-images.githubusercontent.com/71410583/111149756-0b734d00-856c-11eb-9dc2-35ebb267faf8.png)

**Comment by rvnovaes** [comment]
Como chegar a essa agenda? A questão da @taynaraginacio procede?

**Comment by Ale-eloy** [comment]
Ei pessoal! Estamos rodando testes na funcionalidade, pois encontramos outros problemas além do mencionado pela Taynara. Assim que terminados, vamos postar aqui nossos comentários!

**Comment by Ale-eloy** [comment]
Temos uma incongruência aqui: 

1. Durante o cadastro do novo usuário, existe apenas um campo chamado "Dia da semana e horário de atendimento" para preenchimento;
![image](https://user-images.githubusercontent.com/55855366/135157050-cdd5b1f3-14bc-45e8-b922-03bb2e26ffba.png)

2. Ocorre que, depois de cadastrado, um textbox extra aparece e agora a informação é dividida entre "Dia do atendimento" (que fica vazia) e "Horário de início do atendimento" (que passa a conter o input da caixa inicial):
![image](https://user-images.githubusercontent.com/55855366/135157386-94fc15e1-305b-415b-9a74-3c63f7dea42c.png)

**Comment by Ale-eloy** [comment]
A incongruência continua existindo.

1. Durante o cadastro, o sistema exige a informação de "dia da semana e horário de atendimento":

![image](https://user-images.githubusercontent.com/55855366/152336612-060a9a8a-6c63-42ab-ab05-4b1902dc3582.png)

2. Porém, após cadastrado, o card mostra o dia da semana separado horário de atendimento:

![image](https://user-images.githubusercontent.com/55855366/152336768-02637e33-142a-4398-aabf-bfa2911c9067.png)

Sugestão: a solução mais prática seria mudar o card de exibição para aglutinar dia da semana e horário de atendimento em um campo apenas, ou seja, excluir o campo"Dia de atendimento" que aparece no card de visualização. Obs.: eu sugiro antes conferir se não existe no Banco de Dados um campo específico pro dia do atendimento, porque se tiver, podemos excluir.

**Comment by gabrielathais** [comment]
Issue corrigida na versão de testes
(Testado com os usuários Administrador e Professor, nos navegadores Google Chrome e Microsoft Egde)
