### ISSUE TITLE
Edição de casos - Erro no salvamento

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#72]
i) Usuário Estagiario

Fiz a edição do caso 38 e só consegui editar a área do caso. A edição foi salva, fui redirecionada à página "Gestão de Casos" e, ao entrar novamente no caso, nao consigo verificar se a edição ocorreu, pois não é possível visualizar a área do caso. 

![image](https://user-images.githubusercontent.com/71410583/111151674-8c334880-856e-11eb-87ad-f36e57626cc8.png)

**Comment by rvnovaes** [comment]
Ao editar o caso e salvar, as informações são salvas, mas é exibida página de erro 500

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
> i) Usuário Estagiario
> 
> Fiz a edição do caso 38 e só consegui editar a área do caso. A edição foi salva, fui redirecionada à página "Gestão de Casos" e, ao entrar novamente no caso, nao consigo verificar se a edição ocorreu, pois não é possível visualizar a área do caso.
> 
> ![image](https://user-images.githubusercontent.com/71410583/111151674-8c334880-856e-11eb-87ad-f36e57626cc8.png)

Quanto à possibilidade de editar um caso sem dar erro 500, me parece que foi corrigida conforme issue #87 .

Ocorre que o comentário da @taynaraginacio também fazia menção ao fato dela "**só consegui editar a área do caso**".  Averiguei por alto a situação e me parece que a [planilha de permissões](https://github.com/gestaolegalufmg/gestaolegal/wiki/Permiss%C3%B5es-de-Usu%C3%A1rios) fazia referência a diferentes níveis de alteração a depender do tipo de usuário (e.g. o Estagiário de Direito somente pode alterar certos campos). Ocorre que pelo que averiguei as permissões estabelecidas não estão sendo respeitadas. Irei averiguar a fundo e criar um novo issue referente às permissões de usuários durante a edição dos casos. 

![image](https://user-images.githubusercontent.com/55855366/119280823-7e064600-bc09-11eb-958b-df514b98cc7d.png)

**Comment by ryanemmanuel** [comment]
![image](https://user-images.githubusercontent.com/4334173/119374804-6aea8900-bc90-11eb-9c92-c80ec0c64cf0.png)


### **Usuário: Estagiário de Direito - Erro de permissão – consegue alterar, quando não deveria.**
Botão editar está disponível e dá acesso a tela de edição. 
Se alterar área e clicar em salvar – erro 500 – mas a área é alterada
Se alterar orientador e clicar em salvar – erro 500 – mas o orientador é alterado
Se alterar estagiário e clicar em salvar – erro 500 – mas o estagiário é alterado
**O estagiário deve poder subir arquivos para o caso**
![image](https://user-images.githubusercontent.com/4334173/119374859-7ccc2c00-bc90-11eb-8a2e-a4034ab1df2a.png)

Quando vamos ver a informação do caso, nota-se que, apesar da tela de erro 500, as alterações foram efetivadas.
![image](https://user-images.githubusercontent.com/4334173/119374891-86ee2a80-bc90-11eb-8ca4-82233e5e2fb4.png)

Obs. O campo estagiário de direito responsável, na tela gestão de casos, está com erro, conforme issue #140. Na tela gestão de casos é possível ver que o estagiário de direito também foi alterado:

**Comment by ryanemmanuel** [comment]
### Usuário: Colaborador externo - Erro de permissão / alteração não produz efeito.

![image](https://user-images.githubusercontent.com/4334173/119378242-6de77880-bc94-11eb-9cd1-12396202dd85.png)
Botão editar está disponível e dá acesso a tela de edição. 

Ao clicar em editar, permite alterar o colaborar externo ligado ao caso - não deveria poder alterar.

![image](https://user-images.githubusercontent.com/4334173/119378312-86f02980-bc94-11eb-9e86-579b0f25bd38.png)
Importante: O colaborador externo deve poder subir arquivos para o caso
Ao alterar e clicar em salvar, aparece a animação e voltamos à mesma tela.

Entretanto, não produz qualquer efeito prático (o caso não é listado na tela meus casos do usuário “colaborador externo”.
![image](https://user-images.githubusercontent.com/4334173/119378420-a5eebb80-bc94-11eb-9163-d8bd4d4ea809.png)
(antes)
![image](https://user-images.githubusercontent.com/4334173/119378436-ad15c980-bc94-11eb-9317-9cb84d794bb8.png)
(depois)

**Comment by ryanemmanuel** [comment]
Usuário:  Administrador – ausência de permissões / funções:

![image](https://user-images.githubusercontent.com/4334173/119384027-7b076600-bc9a-11eb-9e48-46bfd423d5d7.png)

Deveria poder alterar os assistidos;
Deveria poder editar e excluir arquivos;

**Comment by Ale-eloy** [comment]
Acrescentei o label question porque acredito que os comentários feitos na verdade geram outros issues novos e não devem permanecer aqui. Por isso, irei organizar esse issue destacando os reports feitos nos comentários e, ao final, iremos conferir a demanda feita no comentário do Ryan em 24/05/2021.

**Comment by Ale-eloy** [comment]
> Acrescentei o label question porque acredito que os comentários feitos na verdade geram outros issues novos e não devem permanecer aqui. Por isso, irei organizar esse issue destacando os reports feitos nos comentários e, ao final, iremos conferir a demanda feita no comentário do Ryan em 24/05/2021.

Os issues presentes nesse issue foram bifurcados em outras anotações.
