### ISSUE TITLE
Não consigo “Cadastrar Assistência Judiciária” em PLANTÃO #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#75]
i) Ao tentar cadastrar uma Assistência Judiciária, fui direcionado para uma tela em branco e sem qualquer tipo de ação possível
ii) Login utilizado: Colaborador externo
iii) Navegador: Google Chrome

Passos:
I) Selecionar a opção "Plantão" no canto superior esquerdo da página inicial
II) Selecionar a opção secundária "Assistências Judiciárias"
III) Selecionar a opção "Cadastrar Assistência Judiciária" da nova página aberta
IV) Página em branco

![image](https://user-images.githubusercontent.com/71410583/111152962-1b8d2b80-8570-11eb-8b6d-0e1a843271e2.png)
![image](https://user-images.githubusercontent.com/71410583/111152976-1fb94900-8570-11eb-8dba-604d684a0a07.png)

![image](https://user-images.githubusercontent.com/71410583/111152989-247dfd00-8570-11eb-905e-7355d98cf9cf.png)

ATUALIZAÇÃO: A tela que aparece não é mas uma tela branca, mas uma tela de erro: 

![image](https://user-images.githubusercontent.com/71410583/111153111-48d9d980-8570-11eb-885c-72d8d9313825.png)

**Comment by rvnovaes** [comment]
Corrigido
