### ISSUE TITLE
Criar novo lembrete 

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#76]
Usuário: Colab externo

Não consigo criar um novo lembrete para um caso. Ao clicar em "Enviar", a tela carrega mas não sai dessa página. Também nao consegui adicionar usuários a serem notificados.

![image](https://user-images.githubusercontent.com/71410583/111153470-c1409a80-8570-11eb-9b66-d5cbc4880593.png)

**Comment by rvnovaes** [comment]
Corrigido
