### ISSUE TITLE
Não consigo “editar lembrete” criado em CASOS #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#77]
i) Ao tentar editar um lembrete, que eu mesmo criei, é possível inserir as modificações, mas ao salvar o documento, elas não ficam realmente salvas (há o retorno para o estado inicial do lembrete criado)
ii) Login utilizado: Colaborador externo
iii) Navegador: Google Chrome

Passos:
I) Selecionar a opção "Casos" no canto superior esquerdo da página inicial
II) Selecionar a opção secundária "Lembretes"
III) Criar um lembrete e "Enviar"
IV) Retornar para o menu principal e selecionar a opção "Casos"
V) Selecionar a opção "Visualizar" presente no Caso 1
VI) Selecionar a opção "Ver lembretes" presente em Dados do Caso
VII) "Editar" o lembrete criado, fazer a alteração e "Salvar"
VIII) Refazer os passos IV - VI
IX) Lembrete não editado

![image](https://user-images.githubusercontent.com/71410583/111153644-f9e07400-8570-11eb-8041-d134e12cd108.png)
![image](https://user-images.githubusercontent.com/71410583/111153671-006eeb80-8571-11eb-8a95-ced5e3e5b9b2.png)

![image](https://user-images.githubusercontent.com/71410583/111153695-06fd6300-8571-11eb-8516-e1046793c645.png)
![image](https://user-images.githubusercontent.com/71410583/111153729-0fee3480-8571-11eb-9087-9a924a199d89.png)
![image](https://user-images.githubusercontent.com/71410583/111153749-141a5200-8571-11eb-8c5b-3e3288ab6845.png)
![image](https://user-images.githubusercontent.com/71410583/111153770-1aa8c980-8571-11eb-93de-a55cb9aa4d63.png)
![image](https://user-images.githubusercontent.com/71410583/111153787-20061400-8571-11eb-96ec-9c58cb935c2d.png)

**Comment by rvnovaes** [comment]
Corrigido
