### ISSUE TITLE
Não consigo “excluir lembrete” criado em CASOS #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#78]
Não consigo “excluir lembrete” criado em CASOS

i) Ao selecionar a opção “Excluir (Em construção)” para apagar o lembrete criado (o mesmo lembrete citado no comentário anterior), há um retorno para o topo sem a exclusão do lembrete, que permanece ao final da página
ii) Login utilizado: Colaborador externo
iii) Navegador: Google Chrome

Passos:
I) Selecionar a opção "Casos" no menu principal
II) Selecionar a opção "Visualizar" presente no Caso 1
III) Selecionar a opção "Ver lembretes" presente em Dados do Caso
IV) Selecionar a opção “Excluir (Em construção)” no caso criado (foi utilizado o mesmo caso criado para o comentário anterior)
V) Lembrete não é excluído e permanece ao final da página
![image](https://user-images.githubusercontent.com/71410583/111153927-517edf80-8571-11eb-9d63-96c398207204.png)
![image](https://user-images.githubusercontent.com/71410583/111153940-55aafd00-8571-11eb-97f7-3417267dbd71.png)
![image](https://user-images.githubusercontent.com/71410583/111153954-59d71a80-8571-11eb-8fce-6a994e5381c1.png)
![image](https://user-images.githubusercontent.com/71410583/111153965-5e9bce80-8571-11eb-8231-659a494e545a.png)
![image](https://user-images.githubusercontent.com/71410583/111153978-62c7ec00-8571-11eb-8489-a4b1e773c571.png)

**Comment by rvnovaes** [comment]
Complemento: Quando um lembrete é criado, o usuário é redirecionado para a listagem de casos. Ele deve ser redirecionado para a página do caso.

Complemento: a página de lembretes só mostra a opção de criar lembretes quanto há pelo menos um lembrete cadastrado. Essa opção deve existir mesmo sem nenhum lembrete.
![Screenshot from 2021-03-19 09-11-54](https://user-images.githubusercontent.com/374578/111778273-31ae2b00-8893-11eb-8f68-fe0cd4eb439b.png)
![Screenshot from 2021-03-19 09-12-01](https://user-images.githubusercontent.com/374578/111778277-32df5800-8893-11eb-95da-2932a0d24184.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Em relação aos comentários do professor:

> O erro de não exclusão do lembrete foi corrigido. Entretanto, a navegação ainda apresenta problemas:
> 
> Complemento: Quando um lembrete é criado, o usuário é redirecionado para a listagem de casos. Ele deve ser redirecionado para a página do caso.
> 
> Complemento: a página de lembretes só mostra a opção de criar lembretes quanto há pelo menos um lembrete cadastrado. Essa opção deve existir mesmo sem nenhum lembrete.
> ![Screenshot from 2021-03-19 09-11-54](https://user-images.githubusercontent.com/374578/111778273-31ae2b00-8893-11eb-8f68-fe0cd4eb439b.png)
> ![Screenshot from 2021-03-19 09-12-01](https://user-images.githubusercontent.com/374578/111778277-32df5800-8893-11eb-95da-2932a0d24184.png)

1) Sobre "**Complemento: Quando um lembrete é criado, o usuário é redirecionado para a listagem de casos. Ele deve ser redirecionado para a página do caso.**": me parece ter sido corrigido. Ao criar novo lembrete, fui redirecionado para a página do próprio caso.

2) Sobre "**Complemento: a página de lembretes só mostra a opção de criar lembretes quanto há pelo menos um lembrete cadastrado. Essa opção deve existir mesmo sem nenhum lembrete.**": me parece ter sido resolvido. Criei um novo caso de n° 17, que não tem nenhum lembrete cadastrado. Ao criar um novo lembrete e em seguida excluí-lo, a página de lembrete continuou mostrando o botão "Criar lembrete".
