### ISSUE TITLE
Tipo valor R$ em valor da causa em associar processo como administrador #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#79]
Tipo valor R$ em valor da causa em associar processo como administrador
Logado como administrador (navegador chrome), depois de criado um caso, tentei associar um processo ao caso (casos/novo_processo/)
Sugestão modificar o item valor da causa, em amarelo, para que receba um valor monetário (R$), seja por meio de uma máscara ou por tipo monetário no banco de dados (se existir) - o objetivo é facilitar o preenchimento do usuário e ficar mais lúdico.
OBS: o valor em R$ só aparece após a edição do processo
![image](https://user-images.githubusercontent.com/71410583/111154357-e7b30580-8571-11eb-9a06-59b8aa53e314.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
A issue parece ter sido corrigida:

![image](https://user-images.githubusercontent.com/55855366/119282901-af830f80-bc11-11eb-94df-d33fb1a48729.png)
