### ISSUE TITLE
Bug ao inserir data no cadastro de processo judicial como administrador #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#81]
1.Logado como administrador (navegador chrome), depois de criado um caso, tentei associar um processo ao caso (casos/novo_processo/)
2.Eu inseri uma data de distribuição, mas não inseri uma data de transito em julgado, e o erro na imagem apareceu. A data é válida.
3.Suspeito que ele esteja colocando "Data de Transito em julgado" como obrigatória. Acontece que ela não pode ser obrigatória porque o transito em julgado demora muito para ocorrer (estamos falando de 5 até 10 anos em média). Logo, tem que ser opcional.
![image](https://user-images.githubusercontent.com/71410583/111154732-4e382380-8572-11eb-968c-ff4d306acd81.png)

**Comment by rvnovaes** [comment]
Duplicado de #86
