### ISSUE TITLE
Notificações - Ausência de opção da página de origem

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#82]
1. Usuário Estagiario
2. Ao acessar as notificações, não consigo acessar a página de origem delas. Assim, essa página se torna basicamente um relatório das atividades.
![image](https://user-images.githubusercontent.com/71410583/111155159-d8808780-8572-11eb-87fa-d592634e0386.png)

Pensando no Estagiário que usa esse site, não seria melhor que as notificações redirecionassem à página de origem, como estava em uma outra versão do software?
![image](https://user-images.githubusercontent.com/71410583/111155331-1087ca80-8573-11eb-97ba-2541f76f9f65.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
A issue não foi corrigida. Ela deve ser tratada conjuntamente com a issue #65 , na qual reportamos que ainda não existe o botão "Ir à página" ou qualquer hiperlink que direcione o lembrete ao caso correspondente.

**Comment by shevah7** [comment]
Testei a issue novamente e ela ainda não foi corrigida. A situação descrita permanece:
![Captura de Tela (150)](https://user-images.githubusercontent.com/71346842/134272200-d4936ea8-c49c-4561-8dcd-6298e73a89da.png)

Usuário: Estagiário.
Navegador: Chrome
