### ISSUE TITLE
Quadro de casos - página Gestão de casos #sugestao

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#83]
1. Usuário Estagiario
2. Seria possível dar um destaque ao "Caso XX" com o aumento da letra? Além disso, acho que seria ideal se houvesse um link para visualizar o caso na propria redação "Caso XX", de forma que poderiamos retirar o botao "visualizar".

![image](https://user-images.githubusercontent.com/71410583/111155657-7d02c980-8573-11eb-8ca9-2553c04db84f.png)

**Comment by torresnatela** [comment]
Usuário Estagiario
Seria possível dar um destaque ao "Caso XX" com o aumento da letra? Além disso, acho que seria ideal se houvesse um link para visualizar o caso na propria redação "Caso XX", de forma que poderiamos retirar o botao "visualizar".

**Comment by Ale-eloy** [comment]
Entendemos que a melhoria descrita não é prioritária para o momento, podendo ser desenvolvida futuramente.
