### ISSUE TITLE
Direcionamento de página após associação de processo #issueanterior

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#84]
Direcionamento de página após associação de processo
(I) Após associar um processo à um caso, fui redirecionado a tela de casos. Talvez seria mais conveniente se fosse redirecionado à página que estava anteriormente.
(II) Login: estagiário
(III) Navegador: Chrome

Passos: Páginal principal > /casos > Botão “visualizar” em um dos casos (http://localhost:5000/casos/visualizar/3) > Botão “associar processo” > Preenchimento dos dados e novamente botão “associar processo”
![image](https://user-images.githubusercontent.com/71410583/111155764-a4f22d00-8573-11eb-8f4e-5bed0b146e7d.png)

**Comment by rvnovaes** [comment]
Ou seja, o redirecionamento deve ser à página do caso, e não à listagem de processos.

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by rvnovaes** [comment]
Corrigido
