### ISSUE TITLE
Erro ao associar um processo

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#85]
- Orientador
Estou na conta do Orientador e tentei associar um processo para um caso aleatório, pois não há casos associados. Consegui fazer isso, mas não lembrava para qual caso tinha sido e tentei novamente no caso 38. Como já existe processos com o número 123, 1234, tentei o número 123456789123 e apareceu a seguinte mensagem na tela:
![image](https://user-images.githubusercontent.com/71410583/111157218-65c4db80-8575-11eb-9b3d-dc321be717b4.png)

**Comment by rvnovaes** [comment]
Duplicado do caso #87
