### ISSUE TITLE
Criação de processos - Necessidade de data para o trânsito em julgado

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#86]
- Orientador
Tentei associar um processo ao caso 36 imaginando a situação hipotética de uma causa judicial em curso. Porém, para associar um processo é necessário inserir uma data final. Acho que a exigência dessa data para o cadastro de um novo processo não é ideal, pois o trânsito em julgado é o momento final de uma causa.
![image](https://user-images.githubusercontent.com/71410583/111157288-7a08d880-8575-11eb-9d8a-d4a3989a067d.png)

**Comment by rvnovaes** [comment]
Acrescento que todas as mensagens de validação dessa página estão em inglês e precisam ser traduzidas.
![Screenshot from 2021-03-17 17-16-17](https://user-images.githubusercontent.com/374578/111533353-71ff9300-8745-11eb-9b92-98ae8b1ce809.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
> * Orientador
>   Tentei associar um processo ao caso 36 imaginando a situação hipotética de uma causa judicial em curso. Porém, para associar um processo é necessário inserir uma data final. Acho que a exigência dessa data para o cadastro de um novo processo não é ideal, pois o trânsito em julgado é o momento final de uma causa.
>   ![image](https://user-images.githubusercontent.com/71410583/111157288-7a08d880-8575-11eb-9d8a-d4a3989a067d.png)

Testei e o sistema não exige mais a data de trânsito em julgado.



> Acrescento que todas as mensagens de validação dessa página estão em inglês e precisam ser traduzidas.
> ![Screenshot from 2021-03-17 17-16-17](https://user-images.githubusercontent.com/374578/111533353-71ff9300-8745-11eb-9b92-98ae8b1ce809.png)

Testei e as validações do sistema agora aparecem em português.
