### ISSUE TITLE
Editar um processo - Existe apenas opção de associar e dá erro ao salvar

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#87]
- Orientador
Ao entrar no caso 35 e editar o processo, não há a opção de salvar as edições. O salvamento das minhas alterações até ocorreu, mas após eu ter tentado associar o processo, aparecendo uma tela de erro e, ao retornar para a página anterior, a mensagem de que as alterações foram salvas:
1. 
![image](https://user-images.githubusercontent.com/71410583/111157325-842ad700-8575-11eb-899d-19f11e5ce0ae.png)
2. 
![image](https://user-images.githubusercontent.com/71410583/111157337-88ef8b00-8575-11eb-989b-0049ce1f1b04.png)
3. 
![image](https://user-images.githubusercontent.com/71410583/111157350-8c831200-8575-11eb-9079-c8cb8e330cb8.png)

**Comment by rvnovaes** [comment]
Reproduzido na produção. A melhor solução seria exibir botão de "Salvar" em processo já associado, e não "Associar Processo". De fato, as alterações ficam salvas mas é exibida tela de erro.

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by lucasdeor** [comment]
Testei e parece que a issue for corrigida.

**Comment by Ale-eloy** [comment]
Fiz testes Orientador e como Administrador com o Caso 9 (que já existia no sistema antes da última entrega) e o erro 500 continuou aparecendo, embora ao voltar na página do caso fosse como se a edição tivesse funcionado.
Entretanto, criei um novo caso de n° 17 e repeti o processo mencionado, e aí nesse cenário o erro 500 não aconteceu comigo. Por outro lado, percebi que o erro #125 continua ocorrendo e é crítico.

**Comment by gabriela-lp** [comment]
Testei os casos nºs 17 e 9, como administrador no Chrome. Em ambos ocorreu o Erro 500, mas a modificação concretizou-se. @Ale-eloy 
![image](https://user-images.githubusercontent.com/70505460/134346704-ba43288c-f563-4a9b-9083-0066666bee41.png)
![image](https://user-images.githubusercontent.com/70505460/134347031-d6633735-9b8f-41dc-9021-600172f3e081.png)

**Comment by Ale-eloy** [comment]
@gabriela-lp você poderia tentar executar novamente as instruções da issue e ver se o problema permanece? Se sim, você poderia me explicar exatamente o que você alterou?
Nos meus testes aqui tudo funcionou normalmente, inclusive os casos 17 e 9 que você testou. Minha suspeita é que pode ter sido um bug, ou pode ser que seja alguma alteração específica que você tenha feito no caso que seja o gatilho do problema. Nessa hipótese, precisamos investigar.

**Comment by gabriela-lp** [comment]
@Ale-eloy testei novamente os casos 17 e 9 e o Erro 5000 não apresentou-se novamente, aparentemente a issue foi corrigida.
