### ISSUE TITLE
Cadastro de usuário a ser notificado - Novo Lembrete

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#88]
- Orientador
Ao criar um lembrete para um dos casos, não consegui associar outros usuários. Com isso, não consegui criar um lembrete para o caso.

OBS: tentei encontrar o termo "Professor" e o termo "Alcione", que era a assistida do caso.
![image](https://user-images.githubusercontent.com/71410583/111157464-aa507700-8575-11eb-990d-2004a1ba31a4.png)

**Comment by rvnovaes** [comment]
#93 #100 #103 #101 #104
