### ISSUE TITLE
Edição de evento criado pelo Orientador

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#89]
- Orientador 
Criei um evento para o caso 35. Inicialmente, ao visualizar esse evento não há opção de editá-lo, sendo necessário retornar à opção anterior para editar o evento.
Ah, o arquivo anexado abriu normalmente, na mesma guia. Particularmente, acho que seria melhor abrir em uma guia distinta.
![image](https://user-images.githubusercontent.com/71410583/111157509-b6d4cf80-8575-11eb-8f0a-820ec4e78dde.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
A issue parece ter sido corrigida. Entretanto, o design dos botões precisa ser melhorado, pois ainda está "quebrado".

![image](https://user-images.githubusercontent.com/55855366/119283140-7b5c1e80-bc12-11eb-9018-20058fd671cf.png)

**Comment by shevah7** [comment]
Testei novamente e a issue também parece ter sido corrigida, apenas o design do botão de "excluir" que permanece desalinhado. 
![Captura de Tela (146)](https://user-images.githubusercontent.com/71346842/134268766-89fbafb4-7ecd-4dbc-96e1-bbc37b8b6225.png)

Navegador: Chrome
Usuário: Orientador

**Comment by elisacostab** [comment]
Testei novamente, por meio do usuário orientador, criando um evento ao caso #32, e percebi que ainda permanece o problema quanto ao design do botão. 

![evento](https://user-images.githubusercontent.com/89033709/150882452-888793db-e6b5-4f71-98e4-c392cfbf710d.png)

**Comment by pedrohf03** [comment]
Ainda há o problema quanto ao design do botão.

**Comment by Ale-eloy** [comment]
Problema do botão transformando em issue apartado de n° 214 para fins de organização.
