### ISSUE TITLE
Edição de evento criado pelo orientador - arquivo anexado

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#91]
- Orientador 
O arquivo anexado na criação do evento desapareceu quando eu tentei editar esse evento:
![image](https://user-images.githubusercontent.com/71410583/111157617-d966e880-8575-11eb-99f4-7cbb67813442.png)
Apos salvar a ediçao, o arquivo inicialmente anexado não consta no evento:
![image](https://user-images.githubusercontent.com/71410583/111157634-dec43300-8575-11eb-9bf7-c79faab154a1.png)

**Comment by rvnovaes** [comment]
Corrigido
