### ISSUE TITLE
Edição de casos - Associar Assistido

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#93]
- Orientador

Na edição do caso não encontrei a opção relativa ao assistido.
![image](https://user-images.githubusercontent.com/71410583/111157754-04e9d300-8576-11eb-9708-baea8ae1b1eb.png)
Ao entrar no perfil de assistido aleatório também não encontrei opções para associa-lo a um caso:
![image](https://user-images.githubusercontent.com/71410583/111157773-09ae8700-8576-11eb-9875-5d2068314a06.png)

**Comment by rvnovaes** [comment]
É possível editar os assistidos do caso a partir da tela de listagem. Entretanto o mesmo problema de requisição AJAX permanece.

#100 #103 #104 #101 #93

![Screenshot from 2021-03-16 10-49-39](https://user-images.githubusercontent.com/374578/111320179-7e042b80-8645-11eb-80df-97b94afefc07.png)
