### ISSUE TITLE
Relógio - Registro de presença do orientador

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#95]
-Orientador 
O horário para a presença no Plantão não está acertado com a internet. Será que é possível manter a opção de editar o horário, mas que o horário automático esteja correto?
![image](https://user-images.githubusercontent.com/71410583/111157875-25b22880-8576-11eb-9cf7-648e6722b3b7.png)

**Comment by rafaelvinisan** [comment]
Issue Corrgida

**Comment by Ale-eloy** [comment]
Testei aqui e me pareceu que o relógio do registro de presença estava de acordo com o relógio do meu computador.
