### ISSUE TITLE
Repositório com lembretes e eventos #sugestão

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#96]
- Orientador 
Não encontrei um repositório com os eventos e lembretes criados durante a minha sessão. Pensando no estagiário, acho que seria uma boa opção ter esses eventos e lembretes para ele se organizar. Da forma como está, apenas entrando no caso é possível ver os eventos, o que me deixa um pouco insegura se essa opção será ou não usada por estar meio "inacessível".
![image](https://user-images.githubusercontent.com/71410583/111157930-38c4f880-8576-11eb-9d51-6baf6e42b200.png)

**Comment by torresnatela** [comment]
Orientador
Não encontrei um repositório com os eventos e lembretes criados durante a minha sessão. Pensando no estagiário, acho que seria uma boa opção ter esses eventos e lembretes para ele se organizar. Da forma como está, apenas entrando no caso é possível ver os eventos, o que me deixa um pouco insegura se essa opção será ou não usada por estar meio "inacessível".

**Comment by Ale-eloy** [comment]
Acreditamos que a função "eventos e lembretes criados durante a sessão" não seja necessária por enquanto.
