### ISSUE TITLE
Atendidos e Assistidos - Como identificar o perfil de cada um

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#97]
- Orientador
A primeira página de atendidos e assistidos não permite que se identifique qual pessoa tem qual característica. Só entrando no perfil é que é possivel identificar que uma pessoa é assistida pelo fato de uma das caixas conter "Dados de Assistido". Na verdade, não sei se essa frase é genérica e todos naquela página estão identificados como Assistido. Será que é possível inserir uma coluna com "Assistido/Atendido" ou uma com o número do caso?
![image](https://user-images.githubusercontent.com/71410583/111157953-41b5ca00-8576-11eb-9a9f-ab84a95357e1.png)

**Comment by rvnovaes** [comment]
É possível filtrar por tipo (Todos/Assistido/Atendido) na caixa de seleção no topo, ao lado do botaão Cadastrar Atendido. Isso soluciona o problema ou existe outra necessidade?

**Comment by Ale-eloy** [comment]
Entendemos que, embora seja mais prático visualizar na lista se se trata de um atendido ou assistido, a função da caixa de seleção no topo da página já serve bem a esse propósito por enquanto.

Sugestão: fechar issue.
