### ISSUE TITLE
Quadro "Dia do plantão" na Página do Plantão #sugestao

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#98]
- Orientador

No quadro "Dia do plantão" há dois número (1º) e (2º) que não trazem informação nenhuma. Eles só mudam de cor quando vamos fazer a escolha dos dias, e depois dessa escolha o quadrinho não tem finalidade. Acho que seria bom unir o quadro "Dia do plantao" com "Seus dias de plantão"

![image](https://user-images.githubusercontent.com/71410583/111158029-572af400-8576-11eb-9af2-e09269e64b0b.png)

**Comment by torresnatela** [comment]
No quadro "Dia do plantão" há dois número (1º) e (2º) que não trazem informação nenhuma. Eles só mudam de cor quando vamos fazer a escolha dos dias, e depois dessa escolha o quadrinho não tem finalidade. Acho que seria bom unir o quadro "Dia do plantao" com "Seus dias de plantão"
