### ISSUE TITLE
Editar informações do plantão

### ISSUE THREAD

**Issue by taynaraginacio** [gestaolegalufmg/gestaolegal#99]
Orientador 

Em alguns casos, o estagiário quer mudar apenas uma das datas de plantão, ou por que já realizou um atendimento ou por ter indisponibilidade em apenas um dia. Não seria melhor a edição de plantão, ao invés de zerar as opções do usuário, perguntar a ele quais dias ele quer mudar?
![image](https://user-images.githubusercontent.com/71410583/111158205-86416580-8576-11eb-96b8-4fcc453f7fec.png)

**Comment by Ale-eloy** [comment]
Entendemos que a opção editar apenas uma das datas seja prática, porém não essencial ao software. No momento, a possibilidade de zerar as datas marcadas se ajusta bem ao software, desde que (i) a edição somente possa ocorrer durante o período em que a marcação estiver ABERTA; e (ii) consequentemente, a edição das datas NÃO apague datas passadas nas quais o usuário tiver marcado presença (ou seja, outros períodos de marcação de pontos).
Sugestão: fechar o issue.
